// =========================================================================================
//								THIS FILE WAS GENERATED BY MIGI
// =========================================================================================
//
//	VScripts example, can be used on hosts to play around with entities.
//	They use a language called Squirrel and have its most basic functionalities.
//	For the rest use CS:GO's implementations listed bellow.
//	Not much can be done without events, no way to add them to this system for now.
//
//	Documentation:
// 
//		http://squirrel-lang.org/doc/squirrel2.html
//		https://developer.valvesoftware.com/wiki/List_of_Counter-Strike:_Global_Offensive_Script_Functions 
//		https://developer.valvesoftware.com/wiki/CSGO_Vscript_Examples
// 
//	- @ZooL_Smith
//
// =========================================================================================

// Example variable in the script scope
round_number <- 0;


// Function called by the main MIGI script each new round
function OnNewRound()
{
	round_number++;
	printl(">> This function has been called after a new round!");
	printl(">> Current rounds: " + round_number);
	
	printAllPlayersAndBots();
}

::imAGlobalFunction <- function()
{
	printl(">> Call me from anywhere! Use `script imAGlobalFunction()` in the console!");
}

imAGlobalFunction();

function printAllPlayersAndBots()
{
	foreach(m in ["player","cs_bot"])
	{
		local ply = null;
		while(ply = Entities.FindByClassname(ply, m))
		{
			printl(" - " + ply);
		}
	}
}

// The entity this script is contained in doesn't respawn on new rounds, be careful!
printl(">> I'm only called once in there!");
printl(">> I'm contained inside the entity: " + self );
printl(">> This is my table: " + this);


