// =========================================================================================
//								THIS FILE WAS GENERATED BY MIGI
// =========================================================================================
// 
//	Not much is known about this format, no documentation is available online.
// 
//	See "pak01_dir.vpk/resource/ui/econ/ItemModelPanelCharWeaponInspect.res" for more info
//	Use GCFScape to open .vpk files:
//
// 		https://developer.valvesoftware.com/wiki/GCFScape
// 
// 	When making viewmodels, simply position them around the same position as one from CS:GO
// 	and copy the corresponding entry inside ItemModelPanelCharWeaponInspect.res 
// 
// 
//	- @ZooL_Smith
//
// =========================================================================================

"Resource/UI/Econ/ItemModelPanelCharWeaponInspect.res"
{

	"mozambique"	// unique name for the entry, the name itself doesn't matter.
	{
		"rule"
		{
			"model" "v_pist_tec9"		// What viewmodel it replaces, seems to be based on substrings.
		}
			
		"config"		// Where the camera is placed and how it rotates.
		{
			"camera_offset"   "44.57 18.35 -5.47"
			"camera_orient"   "1.30 -135.29 0.00"
			"orbit_pivot"     "20.88 -5.10 -6.23"
			"item_rotate"	  "y[-360 360] x[ 0 0 ]"
		}
	}
	
}
