// Created by CrowbarDecompiler 0.71

$modelname "weapons\v_rif_m4a1.mdl"

$bodygroup "studio"
{
	studio "cf_native_vm.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\V_models\rif_m4a1\"
$cdmaterials "models\weapons\v_models\cf_leishen\"

$texturegroup "skinfamilies"
{
	{ "rif_m4a1" "cf_foxhand_bl" "cf_foxarm_bl" }
}

$attachment "1" "v_weapon.flash" 0 0 0 rotate 0 0 0
$attachment "2" "v_weapon.shelleject" 0 0 0 rotate 0 0 0
$attachment "stattrack" "v_weapon.stattrack" 0 0 0 rotate 0 0 0
$attachment "uid" "v_weapon.uid" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -30 -30 -30 30 30 30

$definebone "v_weapon" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Pelvis" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Spine" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Spine1" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Spine2" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Spine3" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_Neck" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Clavicle" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_UpperArm" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Forearm" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Hand" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_ForeTwist" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Clavicle" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_UpperArm" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Forearm" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Hand" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_ForeTwist" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger0" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger01" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger02" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger1" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger11" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger12" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger2" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger21" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger22" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger3" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger31" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger32" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger4" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger41" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_L_Finger42" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger0" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger01" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger02" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger1" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger11" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger12" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger2" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger21" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger22" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger3" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger31" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger32" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger4" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger41" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "v_weapon.Bip01_R_Finger42" "v_weapon" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "FvARM-bone" "v_weapon" -11.397009 -13.240152 -20.445601 3.266547 89.97816 1.027199 0 0 0 0 0 0
$definebone "FvARM-bone Pelvis" "FvARM-bone" 11.268987 6.724655 66.889542 88.154998 -33.955886 58.551414 0 0 0 0 0 0
$definebone "FvARM-bone Spine" "FvARM-bone Pelvis" -4.144737 0.144209 -0.086374 0.001776 0.04555 -0.000688 0 0 0 0 0 0
$definebone "FvARM-bone Spine1" "FvARM-bone Spine" -3.914295 0.031527 -0.077709 0 0 0 0 0 0 0 0 0
$definebone "FvARM-bone Neck" "FvARM-bone Spine1" -8.706161 0.953156 -0.205957 0.003667 0.097918 -0.001891 0 0 0 0 0 0
$definebone "FvARM-bone L Clavicle" "FvARM-bone Neck" 23.138367 -30.351055 21.453354 80.063286 -165.844301 16.988431 0 0 0 0 0 0
$definebone "FvARM-bone L UpperArm" "FvARM-bone L Clavicle" -8.079597 0.078562 0.89772 12.014637 -0.217552 0.081244 0 0 0 0 0 0
$definebone "FvARM-bone L ForeArm" "FvARM-bone L UpperArm" -7.389951 0.058182 -0.14666 -0.008309 -0.221907 0.004352 0 0 0 0 0 0
$definebone "FvARM-bone L Hand" "FvARM-bone L ForeArm" -7.141945 4.968269 34.131687 -1.493759 0.77292 89.931912 0 0 0 0 0 0
$definebone "FvARM-bone L Finger0" "FvARM-bone L Hand" 9.32875 -32.319218 2.054947 -13.011066 18.755481 -85.550162 0 0 0 0 0 0
$definebone "FvARM-bone L Finger01" "FvARM-bone L Finger0" -2.00732 -0.148418 -0.03368 0.103481 2.727106 -0.050883 0 0 0 0 0 0
$definebone "FvARM-bone L Finger02" "FvARM-bone L Finger01" -1.64978 -0.174263 -0.025711 0.117174 3.083255 -0.057128 0 0 0 0 0 0
$definebone "FvARM-bone L Finger1" "FvARM-bone L Hand" -1.151239 0.858086 -1.004429 -3.521856 -0.913982 0.618568 0 0 0 0 0 0
$definebone "FvARM-bone L Finger11" "FvARM-bone L Finger1" -1.757162 -0.171654 -0.02792 0.116081 3.054265 -0.056663 0 0 0 0 0 0
$definebone "FvARM-bone L Finger12" "FvARM-bone L Finger11" -3.393681 -0.660553 -0.041573 0.358328 9.210062 -0.151544 0 0 0 0 0 0
$definebone "FvARM-bone L Finger2" "FvARM-bone L Hand" -2.275904 0.919998 -0.223534 -1.471356 0.295073 0.411157 0 0 0 0 0 0
$definebone "FvARM-bone L Finger21" "FvARM-bone L Finger2" -1.517202 -0.085838 -0.026459 0.063656 1.684954 -0.032083 0 0 0 0 0 0
$definebone "FvARM-bone L Finger22" "FvARM-bone L Finger21" -2.861383 -0.466759 -0.038437 0.271123 7.02343 -0.120835 0 0 0 0 0 0
$definebone "FvARM-bone L Finger3" "FvARM-bone L Hand" -4.070364 0.882095 0.761581 4.022678 0.101987 0.454415 0 0 0 0 0 0
$definebone "FvARM-bone L Finger31" "FvARM-bone L Finger3" -2.095596 -0.257721 -0.031303 0.164896 4.316778 -0.078206 0 0 0 0 0 0
$definebone "FvARM-bone L Finger32" "FvARM-bone L Finger31" -4.035295 -0.904175 -0.044987 0.457907 11.672063 -0.182198 0 0 0 0 0 0
$definebone "FvARM-bone L Finger4" "FvARM-bone L Hand" -6.754801 0.863586 2.226116 12.782343 -0.22036 0.430065 0 0 0 0 0 0
$definebone "FvARM-bone L Finger41" "FvARM-bone L Finger4" -2.442366 -0.421021 -0.031963 0.248376 6.446747 -0.11224 0 0 0 0 0 0
$definebone "FvARM-bone L Finger42" "FvARM-bone L Finger41" -3.23838 -0.647484 -0.039032 0.352309 9.061667 -0.149597 0 0 0 0 0 0
$definebone "FvARM-bone L ForeTwist" "FvARM-bone L UpperArm" -7.389932 0.053125 -0.150448 -0.008195 -0.222193 -0.010431 0 0 0 0 0 0
$definebone "FvARM-bone R Clavicle" "FvARM-bone Neck" -13.924431 -30.376884 11.271997 -75.771605 172.647825 9.259229 0 0 0 0 0 0
$definebone "FvARM-bone R UpperArm" "FvARM-bone R Clavicle" -0.131354 -0.019442 -0.225739 -11.996818 0.692821 -0.185696 0 0 0 0 0 0
$definebone "FvARM-bone R ForeArm" "FvARM-bone R UpperArm" -7.38995 0.058178 -0.14666 -0.008307 -0.221907 0.004354 0 0 0 0 0 0
$definebone "FvARM-bone R Hand" "FvARM-bone R ForeArm" -6.808044 -34.228607 4.766365 -0.771143 -1.494675 -89.931974 0 0 0 0 0 0
$definebone "FvARM-bone R Finger0" "FvARM-bone R Hand" -4.515665 4.507805 34.267162 12.497643 19.959727 85.434656 0 0 0 0 0 0
$definebone "FvARM-bone R Finger01" "FvARM-bone R Finger0" -2.007322 -0.148399 -0.033676 0.103529 2.72705 -0.05082 0 0 0 0 0 0
$definebone "FvARM-bone R Finger02" "FvARM-bone R Finger01" -1.649775 -0.174286 -0.025734 0.117165 3.083316 -0.05718 0 0 0 0 0 0
$definebone "FvARM-bone R Finger1" "FvARM-bone R Hand" -3.51046 0.572945 0.932203 3.44296 -1.196506 -0.585849 0 0 0 0 0 0
$definebone "FvARM-bone R Finger11" "FvARM-bone R Finger1" -1.757168 -0.171661 -0.027915 0.116025 3.054267 -0.056608 0 0 0 0 0 0
$definebone "FvARM-bone R Finger12" "FvARM-bone R Finger11" -3.393681 -0.660553 -0.041579 0.358386 9.210064 -0.151604 0 0 0 0 0 0
$definebone "FvARM-bone R Finger2" "FvARM-bone R Hand" -3.264673 0.650002 0.070083 1.488659 0.167477 -0.42204 0 0 0 0 0 0
$definebone "FvARM-bone R Finger21" "FvARM-bone R Finger2" -1.517202 -0.085846 -0.026432 0.063656 1.684955 -0.031971 0 0 0 0 0 0
$definebone "FvARM-bone R Finger22" "FvARM-bone R Finger21" -2.861385 -0.466782 -0.038451 0.271124 7.023432 -0.120894 0 0 0 0 0 0
$definebone "FvARM-bone R Finger3" "FvARM-bone R Hand" -1.371159 0.525497 -0.825925 -4.004402 0.385945 -0.473206 0 0 0 0 0 0
$definebone "FvARM-bone R Finger31" "FvARM-bone R Finger3" -2.0956 -0.257759 -0.03131 0.164897 4.316778 -0.078266 0 0 0 0 0 0
$definebone "FvARM-bone R Finger32" "FvARM-bone R Finger31" -4.03529 -0.904167 -0.044987 0.45785 11.672061 -0.182201 0 0 0 0 0 0
$definebone "FvARM-bone R Finger4" "FvARM-bone R Hand" 1.741884 0.440269 -1.427472 -12.763036 0.736481 -0.545112 0 0 0 0 0 0
$definebone "FvARM-bone R Finger41" "FvARM-bone R Finger4" -2.442369 -0.421028 -0.031964 0.24832 6.446748 -0.112185 0 0 0 0 0 0
$definebone "FvARM-bone R Finger42" "FvARM-bone R Finger41" -3.238379 -0.647491 -0.039029 0.35237 9.06167 -0.149599 0 0 0 0 0 0
$definebone "FvARM-bone R ForeTwist" "FvARM-bone R UpperArm" -7.389964 0.063234 -0.142883 -0.008422 -0.221563 0.019137 0 0 0 0 0 0
$definebone "FvARM-bone Prop1" "FvARM-bone" -4.009437 -30.344385 15.288361 -0.227407 1.399392 -91.622657 0 0 0 0 0 0
$definebone "Dummy01" "FvARM-bone Prop1" -9.606464 -1.491556 0.06278 2.908391 -0.463409 1.608063 0 0 0 0 0 0
$definebone "Bone02" "Dummy01" 14.88632 -1.080346 0.350275 0.066119 1.748896 -0.033174 0 0 0 0 0 0
$definebone "Box001" "Bone02" 8.467159 3.803825 22.105753 88.123832 -33.740906 60.284547 0 0 0 0 0 0
$definebone "Box002" "Bone02" 9.861919 3.949635 21.338112 88.119535 -33.70865 60.548691 0 0 0 0 0 0
$definebone "Box003" "Bone02" -1.437462 -2.574752 34.511307 50.954461 85.770463 179.739379 0 0 0 0 0 0
$definebone "Box005" "Bone02" 0.389074 -5.578572 36.377625 40.961789 86.314146 -179.797708 0 0 0 0 0 0
$definebone "Box006" "Bone02" -0.432925 -30.202703 32.287167 -39.014478 88.340868 -179.075839 0 0 0 0 0 0
$definebone "Box004" "Bone02" -2.411184 -31.931969 29.334709 -49.01173 88.653308 -179.223208 0 0 0 0 0 0
$definebone "Bone04" "Dummy01" 8.970018 -2.348264 0.327314 -0.056207 -1.509572 0.030252 0 0 0 0 0 0
$definebone "Bone06" "Dummy01" -10.141367 -12.614876 0.246809 3.266547 89.97816 1.027199 0 0 0 0 0 0
$definebone "v_weapon.flash" "Dummy01" -10.411726 0.894689 24.052322 1.855982 177.325344 -87.100239 0 0 0 0 0 0
$definebone "v_weapon.shelleject" "Dummy01" 6.24435 -0.043256 25.337194 -72.803055 -98.661557 96.285559 0 0 0 0 0 0
$definebone "v_weapon.stattrack" "Dummy01" 5.371284 0.686714 23.963764 86.557594 -60.080352 32.62153 0 0 0 0 0 0
$definebone "v_weapon.uid" "Dummy01" 10.209586 -0.057246 24.004221 86.557594 -60.080352 32.62153 0 0 0 0 0 0

$bonemerge "v_weapon"
$bonemerge "v_weapon.Bip01"
$bonemerge "v_weapon.Bip01_Pelvis"
$bonemerge "v_weapon.Bip01_Spine"
$bonemerge "v_weapon.Bip01_Spine1"
$bonemerge "v_weapon.Bip01_Spine2"
$bonemerge "v_weapon.Bip01_Spine3"
$bonemerge "v_weapon.Bip01_Neck"
$bonemerge "v_weapon.Bip01_L_Clavicle"
$bonemerge "v_weapon.Bip01_L_UpperArm"
$bonemerge "v_weapon.Bip01_L_Forearm"
$bonemerge "v_weapon.Bip01_L_Hand"
$bonemerge "v_weapon.Bip01_L_ForeTwist"
$bonemerge "v_weapon.Bip01_R_Clavicle"
$bonemerge "v_weapon.Bip01_R_UpperArm"
$bonemerge "v_weapon.Bip01_R_Forearm"
$bonemerge "v_weapon.Bip01_R_Hand"
$bonemerge "v_weapon.Bip01_R_ForeTwist"
$bonemerge "v_weapon.Bip01_L_Finger0"
$bonemerge "v_weapon.Bip01_L_Finger01"
$bonemerge "v_weapon.Bip01_L_Finger02"
$bonemerge "v_weapon.Bip01_L_Finger1"
$bonemerge "v_weapon.Bip01_L_Finger11"
$bonemerge "v_weapon.Bip01_L_Finger12"
$bonemerge "v_weapon.Bip01_L_Finger2"
$bonemerge "v_weapon.Bip01_L_Finger21"
$bonemerge "v_weapon.Bip01_L_Finger22"
$bonemerge "v_weapon.Bip01_L_Finger3"
$bonemerge "v_weapon.Bip01_L_Finger31"
$bonemerge "v_weapon.Bip01_L_Finger32"
$bonemerge "v_weapon.Bip01_L_Finger4"
$bonemerge "v_weapon.Bip01_L_Finger41"
$bonemerge "v_weapon.Bip01_L_Finger42"
$bonemerge "v_weapon.Bip01_R_Finger0"
$bonemerge "v_weapon.Bip01_R_Finger01"
$bonemerge "v_weapon.Bip01_R_Finger02"
$bonemerge "v_weapon.Bip01_R_Finger1"
$bonemerge "v_weapon.Bip01_R_Finger11"
$bonemerge "v_weapon.Bip01_R_Finger12"
$bonemerge "v_weapon.Bip01_R_Finger2"
$bonemerge "v_weapon.Bip01_R_Finger21"
$bonemerge "v_weapon.Bip01_R_Finger22"
$bonemerge "v_weapon.Bip01_R_Finger3"
$bonemerge "v_weapon.Bip01_R_Finger31"
$bonemerge "v_weapon.Bip01_R_Finger32"
$bonemerge "v_weapon.Bip01_R_Finger4"
$bonemerge "v_weapon.Bip01_R_Finger41"
$bonemerge "v_weapon.Bip01_R_Finger42"


// The 32 below is a guess until further is known about the format.
$animblocksize 32

$bonesaveframe "v_weapon" position
$bonesaveframe "FvARM-bone Pelvis" position
$bonesaveframe "FvARM-bone Spine1" position
$bonesaveframe "FvARM-bone L Clavicle" position
$bonesaveframe "FvARM-bone L UpperArm" position
$bonesaveframe "FvARM-bone L ForeArm" position
$bonesaveframe "FvARM-bone L Hand" position
$bonesaveframe "FvARM-bone L Finger0" position
$bonesaveframe "FvARM-bone L Finger01" position
$bonesaveframe "FvARM-bone L Finger02" position
$bonesaveframe "FvARM-bone L Finger1" position
$bonesaveframe "FvARM-bone L Finger11" position
$bonesaveframe "FvARM-bone L Finger12" position
$bonesaveframe "FvARM-bone L Finger2" position
$bonesaveframe "FvARM-bone L Finger21" position
$bonesaveframe "FvARM-bone L Finger22" position
$bonesaveframe "FvARM-bone L Finger3" position
$bonesaveframe "FvARM-bone L Finger31" position
$bonesaveframe "FvARM-bone L Finger32" position
$bonesaveframe "FvARM-bone L Finger4" position
$bonesaveframe "FvARM-bone L Finger41" position
$bonesaveframe "FvARM-bone L ForeTwist" position
$bonesaveframe "FvARM-bone R UpperArm" position
$bonesaveframe "FvARM-bone R ForeArm" position
$bonesaveframe "FvARM-bone R Hand" position
$bonesaveframe "FvARM-bone R Finger0" position
$bonesaveframe "FvARM-bone R Finger01" position
$bonesaveframe "FvARM-bone R Finger02" position
$bonesaveframe "FvARM-bone R Finger1" position
$bonesaveframe "FvARM-bone R Finger11" position
$bonesaveframe "FvARM-bone R Finger12" position
$bonesaveframe "FvARM-bone R Finger2" position
$bonesaveframe "FvARM-bone R Finger21" position
$bonesaveframe "FvARM-bone R Finger22" position
$bonesaveframe "FvARM-bone R Finger3" position
$bonesaveframe "FvARM-bone R Finger31" position
$bonesaveframe "FvARM-bone R Finger32" position
$bonesaveframe "FvARM-bone R Finger4" position
$bonesaveframe "FvARM-bone R Finger41" position
$bonesaveframe "FvARM-bone R Finger42" position
$bonesaveframe "FvARM-bone R ForeTwist" position
$bonesaveframe "FvARM-bone Prop1" position
$bonesaveframe "Dummy01" position
$bonesaveframe "Box001" position
$bonesaveframe "Box003" position
$bonesaveframe "Box005" position
$bonesaveframe "Box006" position
$bonesaveframe "Box004" position
$bonesaveframe "Bone04" position
$bonesaveframe "Bone06" position

$sectionframes 30 64

$sequence "idle" {
	"v_rif_m4a1_anims\idle.smd"
	activity "ACT_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "shoot1" {
	"v_rif_m4a1_anims\shoot1.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	{ event 5001 0 "1" }
	{ event AE_CLIENT_EJECT_BRASS 0 "" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "shoot2" {
	"v_rif_m4a1_anims\shoot2.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	{ event 5001 0 "1" }
	{ event AE_CLIENT_EJECT_BRASS 0 "" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "shoot3" {
	"v_rif_m4a1_anims\shoot3.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	{ event 5001 0 "1" }
	{ event AE_CLIENT_EJECT_BRASS 0 "" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "reload" {
	"v_rif_m4a1_anims\reload.smd"
	activity "ACT_VM_RELOAD" 1
	{ event 5004 19 "Weapon_M4A1.Clipout" }
	{ event 5004 72 "Weapon_M4A1.Clipin" }
	{ event 5004 121 "Weapon_M4A1.ClipHit" }
	{ event AE_WPN_COMPLETE_RELOAD 121 "" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "draw" {
	"v_rif_m4a1_anims\draw.smd"
	activity "ACT_VM_DRAW" 1
	{ event 5004 0 "Weapon_M4A1.Draw" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 100
}

$sequence "lookat01" {
	"v_rif_m4a1_anims\lookat01.smd"
	fadein 0.3
	fadeout 0.3
	fps 100
}

$sequence "lookat01_prepare" {
	"v_rif_m4a1_anims\lookat01_prepare.smd"
	fadein 0.2
	fadeout 0.2
	fps 100
}

$sequence "lookat01_loop" {
	"v_rif_m4a1_anims\lookat01_loop.smd"
	fadein 0.2
	fadeout 0.2
	fps 100
}

$keyvalues
{
	qc_path 
	{
		"value"		"d:\project\cf_to_csgo\work\p5_leishen\p7_s05\source1\v_rif_m4a1.qc"
	}
}
