# -*- coding: utf-8 -*-
"""投掷物 + 炸弹 变体台词。"""

LINES = {
    # ---- 投掷物 ----
    "t_smoke01": "桃桃甜心烟雾～咻！",
    "t_smoke02": "吃烟去吧！桃桃掩护你！",
    "t_smoke03": "烟雾弹来咯，躲好呀！",
    "t_smoke04": "桃桃放烟，谁都别想看清！",
    "t_smoke05": "咻～烟雾缭绕，桃桃出击！",
    "t_flashbang01": "桃桃爆闪！Biang～闪瞎你们！",
    "t_flashbang02": "看招！白屏警告！",
    "t_flashbang03": "闪光弹！快闭眼！",
    "t_flashbang04": "Biang～桃桃的闪，亮不亮！",
    "t_grenade01": "桃桃飞雷，走你！",
    "t_grenade02": "吃桃桃一雷！",
    "t_grenade03": "小心！雷来啦！",
    "t_grenade04": "轰！给你个惊喜！",
    "t_grenade05": "手雷去咯，别躲！",
    "t_grenade06": "爆炸吧！桃桃的怒火！",
    "t_molotov01": "桃桃火球，轰隆隆～烧起来！",
    "t_molotov02": "烧烤时间到！躲远点！",
    "t_molotov03": "着火啦！桃桃请你吃火！",
    "t_molotov04": "燃烧瓶，烫烫烫！",
    "t_molotov05": "火海来啦，快跑！",
    "t_molotov06": "桃桃的火，谁也灭不了！",
    "t_molotov07": "烤焦他们！嘻嘻！",
    "t_molotov08": "火势凶猛，桃桃干的！",
    "t_molotov11": "来场火雨吧！",
    "t_decoy01": "小玩具上！迷惑他们去！",
    "t_decoy02": "诱饵弹，装模作样！",
    "t_decoy03": "让假桃桃去吸引火力！",
    "t_decoy04": "砰！假的！逗你们玩！",

    # ---- 炸弹 ----
    "plantingbomb01": "桃桃在放包啦，守好我哦！",
    "plantingbomb02": "安包中…都别打扰桃桃！",
    "plantingbomb03": "桃桃正在放包，掩护一下！",
    "plantingbomb04": "包在装啦，再给桃桃几秒！",
    "plantingbomb05": "放包放包！桃桃手可稳啦！",
    "goingtoplantbomb01": "桃桃去放包咯！",
    "goingtoplantbomb02": "走，桃桃带你们安包去！",
    "goingtoplantbomb03": "放包计划启动！跟上桃桃！",
    "goingtoplantbomba01": "A 点！桃桃带你们去放包！",
    "goingtoplantbomba02": "去 A 安包，跟着桃桃！",
    "goingtoplantbomba03": "A 区走起，包来啦！",
    "goingtoplantbombb01": "B 点走起，桃桃放包去！",
    "goingtoplantbombb02": "B 区安包，桃桃开路！",
    "goingtoplantbombc01": "C 点！桃桃冲啦！",
    "goingtoplantbombc02": "去 C 区安包！",
    "goingtoplantbombc03": "C 点放包，走！",
    "bombtickingdown01": "包在倒数啦！桃桃好紧张！",
    "bombtickingdown02": "包快炸了！撑住呀！",
    "bombtickingdown03": "滴答滴答…桃桃好慌！",
    "bombtickingdown04": "要炸啦！快清点！",
    "bombtickingdown05": "倒计时中，桃桃捂耳朵！",
    "bombtickingdown06": "快炸快炸！顶住顶住！",
    "defendingbombsitea01": "A 点桃桃守着，谁也别想过来！",
    "defendingbombsitea02": "守 A！桃桃在！",
    "defendingbombsitea03": "A 点安全，桃桃看着！",
    "defendingbombsitea04": "别靠近 A！桃桃盯着呢！",
    "defendingbombsitea05": "A 点，桃桃的领地！",
    "defendingbombsiteb01": "B 点交给桃桃啦！",
    "defendingbombsiteb02": "守 B！桃桃堵着呢！",
    "defendingbombsiteb03": "B 点有桃桃，放心！",
    "defendingbombsiteb04": "B 区桃桃守着！",
    "defendingbombsiteb05": "想进 B 点？先过桃桃这关！",
    "goingtodefendbombsite01": "桃桃去守包点咯！",
    "goingtodefendbombsite02": "守点去！桃桃来啦！",
    "goingtodefendbombsite03": "桃桃回防包点！",
    "goingtodefendbombsite04": "去守包点，桃桃安排！",
    "goingtodefendbombsite05": "包点我来守！",
    "spottedloosebomb01": "发现掉包的啦！桃桃看到咯！",
    "spottedloosebomb02": "有个包掉地上！",
    "spottedloosebomb03": "桃桃发现丢在地上的包！",
    "spottedloosebomb04": "包掉了！快捡！",
    "spottedloosebomb05": "咦，有包躺地上！",
    "spottedloosebomb06": "地上有包！桃桃注意啦！",
    "spottedloosebomb07": "掉落的包！桃桃上报！",
    "spottedloosebomb08": "发现无人看管的包！",
}
