# -*- coding: utf-8 -*-
"""BOT 语音（C）：好枪/安包系列/被闪/询问/集结。"""

LINES = {
    "radiobotniceshot01": "漂亮！桃桃给你点赞！",
    "radiobotniceshot02": "好枪！桃桃夸你！",
    "radiobotniceshot03": "这枪绝了！桃桃服气！",
    "radiobotniceshot04": "帅！桃桃也想要这手感！",
    "radiobotniceshot05": "厉害！桃桃鼓掌！",
    "radiobotniceshot06": "妙啊！桃桃记住了！",
    "radiobotniceshot07": "完美一击！桃桃喝彩！",
    "radiobotniceshot08": "这枪桃桃甘拜下风！",
    "radiobotniceshot09": "一枪一个！桃桃惊叹！",
    "radiobotniceshot10": "漂亮漂亮！桃桃学起来！",
    "radiobotniceshot11": "好准！桃桃羡慕！",
    "radiobotniceshot12": "神枪手！桃桃拜服！",
    "radiobotniceshot13": "这操作！桃桃吹爆！",
    "radiobotplanting01": "桃桃在放包！",
    "radiobotplanting02": "安包中！桃桃行动！",
    "radiobotplanting03": "桃桃装包啦！",
    "radiobotplanting04": "放包放包！桃桃手快！",
    "radiobotplanting05": "桃桃在装 C4！",
    "radiobotplanting06": "安包！桃桃正在进行！",
    "radiobotplanting07": "包在装！桃桃盯着进度！",
    "radiobotplantinggo01": "桃桃去放包！",
    "radiobotplantinggo02": "放包去咯！桃桃出发！",
    "radiobotplantinggo03": "桃桃安包去！",
    "radiobotplantinggoa01": "桃桃去 A 点放包！",
    "radiobotplantinggoa02": "A 点安包！桃桃去！",
    "radiobotplantinggob01": "桃桃去 B 点放包！",
    "radiobotplantinggob02": "B 点安包！桃桃去！",
    "radiobotplantinggoc01": "桃桃去 C 点放包！",
    "radiobotplantinggoc02": "C 点安包！桃桃去！",
    "radiobotplantinggoc03": "C 区放包！桃桃冲！",
    "radiobotplantinggosafe01": "安全啦！快放包！",
    "radiobotplantinggosafe02": "放包安全！桃桃掩护！",
    "radiobotplantinggosafe03": "环境安全！桃桃让安包！",
    "radiobotpostflash01": "桃桃中闪了！看不清啦！",
    "radiobotpostflash02": "白屏！桃桃被闪啦！",
    "radiobotpostflash03": "闪瞎桃桃了！缓一缓！",
    "radiobotpostflash04": "眼睛！桃桃被闪到啦！",
    "radiobotquery01": "情况怎么样呀？桃桃问问！",
    "radiobotquery02": "报个情况！桃桃想知道！",
    "radiobotquery03": "什么情况？桃桃问！",
    "radiobotquery04": "进展如何？桃桃打听！",
    "radiobotquery05": "状况如何？桃桃要听！",
    "radiobotregroup01": "都来桃桃这集合！",
    "radiobotregroup02": "集合集合！桃桃在这！",
    "radiobotregroup03": "大家过来！桃桃说！",
    "radiobotregroup04": "归队！桃桃指挥！",
}
