# -*- coding: utf-8 -*-
"""BOT 语音（B）：跟随/前进/看守/击杀/击杀数。"""

LINES = {
    "radiobotfollowme01": "跟着桃桃！",
    "radiobotfollowme02": "跟上来！桃桃带路！",
    "radiobotfollowme03": "这边走！桃桃在前！",
    "radiobotfollowme04": "别掉队！跟桃桃！",
    "radiobotfollowme06": "桃桃开路，跟上！",
    "radiobotfollowyou01": "桃桃随你行动！",
    "radiobotfollowyou02": "你带路，桃桃跟上！",
    "radiobotfollowyou03": "桃桃跟着你！",
    "radiobotfollowyou04": "你去哪桃桃去哪！",
    "radiobotfollowyou05": "好，桃桃随你行动！",
    "radiobotgo01": "走！桃桃开路！",
    "radiobotgo02": "前进！桃桃先行！",
    "radiobotgo03": "出发！桃桃带头！",
    "radiobotgo04": "上！桃桃冲第一！",
    "radiobotgo05": "走啦走啦！桃桃在！",
    "radiobotgo06": "行动！桃桃领队！",
    "radiobotgo07": "开拔！桃桃领头！",
    "radiobotgo08": "冲！桃桃不怕！",
    "radiobotgo09": "前进前进！桃桃打头！",
    "radiobotguarding01": "桃桃看着呢！",
    "radiobotguarding02": "桃桃守着这里！",
    "radiobotguarding03": "有人来桃桃拦！",
    "radiobotguarding04": "桃桃盯紧啦！",
    "radiobotguarding05": "看住！桃桃不放！",
    "radiobotguarding06": "桃桃在这守着！",
    "radiobotguarding07": "盯梢中！桃桃专注！",
    "radiobotguardinga01": "桃桃守着 A 点！",
    "radiobotguardinga02": "A 点桃桃看着！",
    "radiobotguardinga03": "A 点归桃桃管！",
    "radiobotguardingb01": "桃桃守着 B 点！",
    "radiobotguardingb02": "B 点桃桃看着！",
    "radiobotguardingb03": "守 B！桃桃在！",
    "radiobotguardingc01": "桃桃守着 C 点！",
    "radiobotguardingc02": "C 点桃桃看着！",
    "radiobotguardingc03": "守 C！桃桃在！",
    "radiobothear01": "桃桃听到动静啦！",
    "radiobothear02": "有声音！桃桃注意！",
    "radiobothear03": "桃桃听见脚步声！",
    "radiobothear04": "什么动静？桃桃警惕！",
    "radiobothear05": "有人！桃桃听到了！",
    "radiobothear06": "那边有响动！桃桃上报！",
    "radiobothold01": "都给桃桃守住！",
    "radiobothold02": "稳住别动！桃桃看着！",
    "radiobothold03": "守好！桃桃下命令！",
    "radiobothold04": "顶住！桃桃挺你！",
    "radiobotkill01": "桃桃干掉一个！",
    "radiobotkill04": "又解决一个！桃桃出手！",
    "radiobotkill06": "桃桃的枪不是吃素的！",
    "radiobotkill07": "放倒！桃桃来报！",
    "radiobotkill08": "搞定！桃桃继续！",
    "radiobotkill09": "一个倒下！桃桃锁下个！",
    "radiobotkill10": "桃桃又立功啦！",
    "radiobotkill11": "敌人倒下！桃桃数着！",
    "radiobotkillcount02": "两个！桃桃棒棒！",
    "radiobotkillcount03": "三个！桃桃超厉害！",
    "radiobotkillcount04": "四个！桃桃手感火热！",
    "radiobotkillcount05": "五个！桃桃停不下来！",
    "radiobotkillcount07": "七个！桃桃封神啦！",
    "radiobotkillcount09": "九个！桃桃无敌！",
    "radiobotkillcount10": "十个！桃桃数到手软！",
    "radiobotkillcount12": "十二个！桃桃自己都怕！",
    "radiobotkillcount13": "十三个！桃桃杀疯了！",
    "radiobotkillcount15": "十五个！桃桃战神附体！",
    "radiobotkillcount16": "十六个！桃桃破纪录！",
    "radiobotkillcount18": "十八个！桃桃心满意足！",
    "radiobotkillcount19": "十九个！桃桃还在打！",
    "radiobotkillcount21": "二十一个！桃桃眼睛都红了！",
    "radiobotkillcount22": "二十二个！桃桃手好酸！",
    "radiobotkillcount24": "二十四个！桃桃超常发挥！",
    "radiobotkillcount25": "二十五个！桃桃问还有谁！",
    "radiobotkillcount27": "二十七个！桃桃今天封神！",
    "radiobotkillsniper01": "狙击手被桃桃解决啦！",
    "radiobotkillsniper02": "那个狙！桃桃放倒啦！",
    "radiobotkillsniper03": "狙击手倒下！桃桃报！",
    "radiobotkillsniper04": "远处的狙，桃桃干掉了！",
    "radiobotkillsniper05": "狙没了！桃桃立大功！",
    "radiobotkillsniper06": "狙击手清除！桃桃笑！",
}
