//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float3 ColorLimit;
//   float ColorRate;
//   float GlobalDiffuseAlpha;
//   float Sprinker;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   ColorLimit              c1       1
//   theAccumTime            c2       1
//   GlobalDiffuseAlpha      c3       1
//   TexturePanningVelocityU c4       1
//   TexturePanningVelocityV c5       1
//   ColorRate               c6       1
//   Sprinker                c7       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   ColorLimit
//     c1   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c2   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c3   = { 1, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c4   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c5   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c6   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c7   = { 0, 0, 0, 0 };
//

    preshader
    mul c0.x, c2.x, c7.x
    neg r0.x, c7.x
    max c1.x, r0.x, c7.x
    mul c4.x, c2.x, c4.x
    mul c4.y, c2.x, c5.x
    mul c5.x, c2.x, (0.55)
    neg r0.x, c5.x
    max r1.x, r0.x, c5.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c4.x
    max r1.y, r0.x, c4.x
    neg r0.x, r1.y
    cmp c6.x, r0.x, (-0), r1.x
    neg r0.x, c6.x
    add r1.x, r0.x, (0.6)
    add r1.y, r0.x, (1)
    mul r0.xyz, r1.y, c0.xyz
    max r0.w, r1.x, (0)
    min r1.x, r0.w, (1)
    mul r0.w, r1.x, (-2)
    mul r2.x, r1.x, r1.x
    add r1.x, r0.w, (3)
    mul r0.w, r2.x, r1.x
    mul c10.x, r0.w, (5)
    neg r1.x, r0.x
    add r2.x, r1.x, c1.x
    cmp c11.x, r2.x, c1.x, r0.x
    neg r1.x, r0.y
    add r2.x, r1.x, c1.y
    cmp c11.y, r2.x, c1.y, r0.y
    neg r1.x, r0.z
    add r2.x, r1.x, c1.z
    cmp c11.z, r2.x, c1.z, r0.z
    mov c12.xyz, r0.xyz
    mul r1.x, r0.w, r0.w
    mul r2.x, r0.w, r1.x
    mul r0.x, r2.x, (3)
    neg r0.y, c3.x
    add r1.x, r0.y, r0.x
    cmp r2.x, r1.x, c3.x, r0.x
    add c13.x, r2.x, c3.x

// approximately 42 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float GhostOverlayBrightness;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   bool IsGradation;
//   bool IsScanner;
//   sampler2D OverlayMapSampler;
//   sampler2D OverlayMapSampler2;
//   float Sprinker;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   IsGradation            b0       1
//   HightLightColor        c14      1
//   GlobalDiffuseAlpha     c15      1
//   IsScanner              c16      1
//   TextureTileX           c17      1
//   TextureTileY           c18      1
//   Sprinker               c19      1
//   EffectAlpha            c20      1
//   HightLightPower        c21      1
//   GhostOverlayBrightness c22      1
//   DiffuseMapSampler      s0       1
//   AlphaMapSampler2       s1       1
//   OverlayMapSampler      s2       1
//   OverlayMapSampler2     s3       1
//
//
// Default values:
//
//   IsGradation
//     b0   = false;
//
//   HightLightColor
//     c14  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c15  = { 1, 0, 0, 0 };
//
//   IsScanner
//     c16  = { 0, 0, 0, 0 };
//
//   TextureTileX
//     c17  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c18  = { 1, 0, 0, 0 };
//
//   Sprinker
//     c19  = { 0, 0, 0, 0 };
//
//   EffectAlpha
//     c20  = { 0, 0, 0, 0 };
//
//   HightLightPower
//     c21  = { 0, 0, 0, 0 };
//
//   GhostOverlayBrightness
//     c22  = { 4, 0, 0, 0 };
//

    ps_3_0
    def c23, 1, 0.5, 0, 0.300000012
    def c24, 0.150000006, 0.00100000005, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    texld r0, v0, s0
    add r1.x, -c0.x, v0.x
    mov r1.y, v0.y
    texld r1, r1, s3
    mul r1, r1, c19.x
    mul r1, r1, c23.xxxy
    mov r2.z, c23.z
    cmp r1, -c19.x, r2.z, r1
    mad r2, r0, c23.y, c23.w
    max r3, r2, c23.z
    min r2, r3, c24.x
    add r2, r1, r2
    cmp r1, -c16.x, r1, r2
    mul r2.x, c17.x, v0.x
    mul r2.y, c18.x, v0.y
    add r2.zw, r2.xyxy, c4.xyxy
    add r2.xy, r2, c5.x
    cmp r2.xy, c6.x, r2, r2.zwzw
    texld r2, r2, s2
    mad r2, r2, c20.x, r1
    cmp r1, -c1.x, r2, r1
    if b0
      texld r2, v0, s1
      mul r3.w, r2.y, c21.x
      mul r3.xyz, r3.w, c14
      cmp r3, -r2.y, c23.z, r3
      mul r4, r1, r2.z
      mul r2.x, r4.w, c22.x
      max r4.w, r2.z, c24.y
      mov r5.x, c22.x
      mad r5.xyz, r4, r5.x, c11
      mad r5.w, c10.x, r4.w, r2.x
      add r2, r3, r5
      mul oC0.w, r2.w, c15.x
      mov oC0.xyz, r2
    else
      add r0.xyz, r0, c12
      add oC0.xyz, r1, r0
      add r0.x, r1.w, c13.x
      mul oC0.w, r0.w, r0.x
    endif

// approximately 43 instruction slots used (4 texture, 39 arithmetic)
