//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float Sprinker;
//   float theAccumTime;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   theAccumTime c0       1
//   Sprinker     c1       1
//
//
// Default values:
//
//   theAccumTime
//     c0   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c1   = { 0, 0, 0, 0 };
//

    preshader
    mul c0.x, c0.x, c1.x
    mul c1.x, c1.x, c1.x
    mul c2.x, c0.x, (0.55)

// approximately 3 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float GlobalDiffuseAlpha;
//   bool IsScanner;
//   sampler2D OverlayMapSampler;
//   sampler2D OverlayMapSampler2;
//   float Sprinker;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   GlobalDiffuseAlpha c3       1
//   IsScanner          c4       1
//   Sprinker           c5       1
//   EffectAlpha        c6       1
//   DiffuseMapSampler  s0       1
//   OverlayMapSampler  s1       1
//   OverlayMapSampler2 s2       1
//
//
// Default values:
//
//   GlobalDiffuseAlpha
//     c3   = { 1, 0, 0, 0 };
//
//   IsScanner
//     c4   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c5   = { 0, 0, 0, 0 };
//
//   EffectAlpha
//     c6   = { 0, 0, 0, 0 };
//

    ps_2_0
    def c7, 0, 0.300000012, 0, 0
    def c8, 1, 1, 1, 0.5
    dcl t0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    texld r0, t0, s0
    add r1.y, t0.y, -c0.x
    mov r1.x, t0.x
    add r2.xy, t0, c2.x
    texld r1, r1, s2
    texld r2, r2, s1
    mul r1, r1, c5.x
    mul r1, r1, c8
    mov r3.w, c5.x
    cmp r1, -r3.w, c7.x, r1
    mad r3, r0, c8.w, r1
    add r3, r3, c7.y
    cmp r1, -c4.x, r1, r3
    mad r2, r2, c6.x, r1
    cmp r1, -c1.x, r2, r1
    add r0.xyz, r0, r1
    add r0.w, r1.w, c3.x
    mov oC0, r0

// approximately 18 instruction slots used (3 texture, 15 arithmetic)
