//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float2 RefractionParam;
//   float4 RimLightParam;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   theAccumTime            c0       1
//   TexturePanningVelocityU c1       1
//   TexturePanningVelocityV c2       1
//   RefractionParam         c3       1
//   RimLightParam           c4       1
//
//
// Default values:
//
//   theAccumTime
//     c0   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c1   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c2   = { 0, 0, 0, 0 };
//
//   RefractionParam
//     c3   = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c4   = { 0, 0, 0, 0 };
//

    preshader
    mul c0.x, c0.x, c1.x
    mul c0.y, c0.x, c2.x
    mul c1.x, c0.x, (0.55)
    neg r0.x, c2.x
    max r1.x, r0.x, c2.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c1.x
    max r1.y, r0.x, c1.x
    neg r0.x, r1.y
    cmp c2.x, r0.x, (-0), r1.x
    mul c3.x, c3.y, (0.015625)
    neg r0.x, c4.w
    add r1.x, r0.x, (1)
    neg r0.x, r1.x
    mov c4.x, r1.x
    add r1.x, r0.x, (1)
    rcp c5.x, r1.x

// approximately 18 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float GlobalDiffuseAlpha;
//   bool IsGradation;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   sampler2D OverlayMapSampler;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   float TextureTileX;
//   float TextureTileY;
//   float4x4 ViewProjectionMatrix;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   IsGradation          b0       1
//   ViewProjectionMatrix c6       4
//   GlobalDiffuseAlpha   c10      1
//   NormalMappingFactor  c11      1
//   TextureTileX         c12      1
//   TextureTileY         c13      1
//   EffectAlpha          c14      1
//   RefractionParam      c15      1
//   RimLightParam        c16      1
//   DiffuseMapSampler    s0       1
//   NormalMapSampler     s1       1
//   AlphaMapSampler      s2       1
//   AlphaMapSampler2     s3       1
//   OverlayMapSampler    s4       1
//
//
// Default values:
//
//   IsGradation
//     b0   = false;
//
//   ViewProjectionMatrix
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 0, 0, 0, 0 };
//     c8   = { 0, 0, 0, 0 };
//     c9   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c10  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c11  = { 1, 0, 0, 0 };
//
//   TextureTileX
//     c12  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c13  = { 1, 0, 0, 0 };
//
//   EffectAlpha
//     c14  = { 0, 0, 0, 0 };
//
//   RefractionParam
//     c15  = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c16  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c17, 2, -1, 1, 0.5
    def c18, -2, 3, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    texld r0, v0, s0
    texld r1, v0, s1
    mad r1.xy, r1, c17.x, c17.y
    texld r2, v0, s2
    mul r1.yzw, r1.y, v4.xxyz
    mad r1.xyz, v3, r1.x, r1.yzww
    mad r1.xyz, r1, c11.x, v1
    nrm r3.xyz, r1
    mul r1.x, c12.x, v0.x
    mul r1.y, c13.x, v0.y
    add r1.zw, r1.xyxy, c0.xyxy
    add r1.xy, r1, c1.x
    cmp r1.xy, c2.x, r1, r1.zwzw
    texld r1, r1, s4
    mul r1, r1.wxyz, c14.x
    if b0
      texld r4, v0, s3
      mul r1.x, r1.x, r4.z
    endif
    add r0, r0, r1.yzwx
    mul r0.w, r0.w, c10.x
    mov r1.z, c17.z
    mad r1.x, c15.x, -r2.y, r1.z
    mul r1.x, r0.w, r1.x
    dp3 r4.x, r3, c6
    dp3 r4.y, r3, c7
    dp3 r1.y, r3, c9
    rcp r1.y, r1.y
    mad r1.yz, r4.xxyw, r1.y, c17.z
    mul r4.xy, r1.yzzw, c17.w
    mul r4.z, r2.y, c3.x
    dp3 r1.y, v2, r3
    add r1.z, -r1.y, c17.z
    cmp r1.y, r1.y, r1.z, c17.z
    add r1.y, r1.y, -c4.x
    mul_sat r1.y, r1.y, c5.x
    mad r1.z, r1.y, c18.x, c18.y
    mul r1.y, r1.y, r1.y
    mul r1.y, r1.y, r1.z
    mul r3.xyz, r1.y, c16
    mov r4.w, c3.x
    cmp oC1, -r2.y, c18.z, r4
    mov r3.w, c17.w
    cmp oC2, -r2.y, c18.z, r3
    cmp oC0.w, -r2.y, r0.w, r1.x
    mov oC0.xyz, r0

// approximately 50 instruction slots used (5 texture, 45 arithmetic)
