//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float ColorRate;
//   float GlobalDiffuseAlpha;
//   float Sprinker;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   theAccumTime            c1       1
//   GlobalDiffuseAlpha      c2       1
//   TexturePanningVelocityU c3       1
//   TexturePanningVelocityV c4       1
//   ColorRate               c5       1
//   Sprinker                c6       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c1   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c2   = { 1, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c3   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c4   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c5   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c6   = { 0, 0, 0, 0 };
//

    preshader
    mul c0.x, c1.x, c6.x
    neg r0.x, c6.x
    max c1.x, r0.x, c6.x
    mul c4.x, c1.x, c3.x
    mul c4.y, c1.x, c4.x
    mul c5.x, c1.x, (0.55)
    neg r0.x, c4.x
    max r1.x, r0.x, c4.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c3.x
    max r1.y, r0.x, c3.x
    neg r0.x, r1.y
    cmp c6.x, r0.x, (-0), r1.x
    neg r0.x, c5.x
    add r1.x, r0.x, (1)
    add r1.y, r0.x, (0.6)
    max r0.x, r1.y, (0)
    min r1.y, r0.x, (1)
    mul c8.xyz, r1.x, c0.xyz
    mul r0.x, r1.y, (-2)
    mul r0.y, r1.y, r1.y
    add r1.x, r0.x, (3)
    mul r2.x, r0.y, r1.x
    mul r0.x, r2.x, r2.x
    mul r1.x, r0.x, r2.x
    mov c7.x, r2.x
    mul r0.x, r1.x, (3)
    neg r0.y, c2.x
    add r1.x, r0.y, r0.x
    cmp r2.x, r1.x, c2.x, r0.x
    add c9.x, r2.x, c2.x

// approximately 32 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float GhostOverlayBrightness;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   bool IsGradation;
//   bool IsScanner;
//   sampler2D OverlayMapSampler;
//   sampler2D OverlayMapSampler2;
//   float Sprinker;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   IsGradation            b0       1
//   HightLightColor        c10      1
//   GlobalDiffuseAlpha     c11      1
//   IsScanner              c12      1
//   TextureTileX           c13      1
//   TextureTileY           c14      1
//   Sprinker               c15      1
//   EffectAlpha            c16      1
//   HightLightPower        c17      1
//   GhostOverlayBrightness c18      1
//   DiffuseMapSampler      s0       1
//   AlphaMapSampler2       s1       1
//   OverlayMapSampler      s2       1
//   OverlayMapSampler2     s3       1
//
//
// Default values:
//
//   IsGradation
//     b0   = false;
//
//   HightLightColor
//     c10  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c11  = { 1, 0, 0, 0 };
//
//   IsScanner
//     c12  = { 0, 0, 0, 0 };
//
//   TextureTileX
//     c13  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c14  = { 1, 0, 0, 0 };
//
//   Sprinker
//     c15  = { 0, 0, 0, 0 };
//
//   EffectAlpha
//     c16  = { 0, 0, 0, 0 };
//
//   HightLightPower
//     c17  = { 0, 0, 0, 0 };
//
//   GhostOverlayBrightness
//     c18  = { 4, 0, 0, 0 };
//

    ps_3_0
    def c19, 1, 0.5, 0, 0.300000012
    def c20, 0.150000006, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    texld r0, v0, s0
    add r1.x, -c0.x, v0.x
    mov r1.y, v0.y
    texld r1, r1, s3
    mul r1, r1, c15.x
    mul r1, r1, c19.xxxy
    mov r2.z, c19.z
    cmp r1, -c15.x, r2.z, r1
    mad r2, r0, c19.y, c19.w
    max r3, r2, c19.z
    min r2, r3, c20.x
    add r2, r1, r2
    cmp r1, -c12.x, r1, r2
    mul r2.x, c13.x, v0.x
    mul r2.y, c14.x, v0.y
    add r2.zw, r2.xyxy, c4.xyxy
    add r2.xy, r2, c5.x
    cmp r2.xy, c6.x, r2, r2.zwzw
    texld r2, r2, s2
    mad r2, r2, c16.x, r1
    cmp r1, -c1.x, r2, r1
    if b0
      texld r2, v0, s1
      mul r3.w, r2.y, c17.x
      mul r3.xyz, r3.w, c10
      cmp r3, -r2.y, c19.z, r3
      mul r2, r1, r2.z
      add r4.x, r0.x, c7.x
      mad r4.x, r2.x, c18.x, r4.x
      mad r4.yz, r2, c18.x, r0
      mov r2.x, c18.x
      mad r4.w, r2.w, r2.x, c11.x
      add r2, r3, r4
      mul oC0.w, r0.w, r2.w
      mov oC0.xyz, r2
    else
      add r0.xyz, r0, c8
      add oC0.xyz, r1, r0
      add r0.x, r1.w, c9.x
      mul oC0.w, r0.w, r0.x
    endif

// approximately 43 instruction slots used (4 texture, 39 arithmetic)
