//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float3 ColorLimit;
//   float ColorRate;
//   float EmissiveMapThreshold;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   ColorLimit              c1       1
//   theAccumTime            c2       1
//   TexturePanningVelocityU c3       1
//   TexturePanningVelocityV c4       1
//   ColorRate               c5       1
//   MapEnableState          c6       1
//   EmissiveMapThreshold    c7       1
//   NoiseMapUVFlowSpeed     c8       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   ColorLimit
//     c1   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c2   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c3   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c4   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c5   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c6   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c7   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c8   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c6.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c2.x, c8.xy
    mul c4.x, c2.x, c3.x
    mul c4.y, c2.x, c4.x
    mul c5.x, c2.x, (0.55)
    neg r0.x, c4.x
    max r1.x, r0.x, c4.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c3.x
    max r1.y, r0.x, c3.x
    neg r0.x, r1.y
    cmp c6.x, r0.x, (-0), r1.x
    neg r0.x, c5.x
    add r1.x, r0.x, (0.6)
    add r1.y, r0.x, (1)
    mul r0.xyz, r1.y, c0.xyz
    max r0.w, r1.x, (0)
    min r1.x, r0.w, (1)
    mul r0.w, r1.x, (-2)
    mul r2.x, r1.x, r1.x
    add r1.x, r0.w, (3)
    mul r0.w, r2.x, r1.x
    mul c10.x, r0.w, (5)
    neg r1.x, r0.x
    add r0.w, r1.x, c1.x
    cmp c11.x, r0.w, c1.x, r0.x
    neg r1.x, r0.y
    add r0.x, r1.x, c1.y
    cmp c11.y, r0.x, c1.y, r0.y
    neg r1.x, r0.z
    add r0.x, r1.x, c1.z
    cmp c11.z, r0.x, c1.z, r0.z
    neg r0.x, c7.x
    add c12.x, r0.x, (1)

// approximately 36 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float EmissiveMapIntensity;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D OverlayMapSampler;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   HightLightColor      c13      1
//   GlobalDiffuseAlpha   c14      1
//   TextureTileX         c15      1
//   TextureTileY         c16      1
//   EffectAlpha          c17      1
//   HightLightPower      c18      1
//   MapEnableState       c19      1
//   EmissiveMapIntensity c20      1
//   DiffuseMapSampler    s0       1
//   AlphaMapSampler2     s1       1
//   OverlayMapSampler    s2       1
//   MaskMapSampler       s3       1
//   NoiseMapSampler      s4       1
//
//
// Default values:
//
//   HightLightColor
//     c13  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c14  = { 1, 0, 0, 0 };
//
//   TextureTileX
//     c15  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c16  = { 1, 0, 0, 0 };
//
//   EffectAlpha
//     c17  = { 0, 0, 0, 0 };
//
//   HightLightPower
//     c18  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c19  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c20  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c21, 1, 0, 0.00100000005, 0
    def c22, 0.212599993, 0.715200007, 0.0722000003, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    texld r0, v0, s0
    if b0
      texld r1, v0, s3
      mov r0.w, r1.y
    else
      mov r0.w, c21.x
    endif
    add r1.xy, c1, v0
    texld r1, r1, s4
    mov r2.x, c21.x
    cmp r1.x, -c19.y, r2.x, r1.x
    mul r2.x, c15.x, v0.x
    mul r2.y, c16.x, v0.y
    add r1.yz, r2.xxyw, c4.xxyw
    add r2.xy, r2, c5.x
    cmp r1.yz, c6.x, r2.xxyw, r1
    texld r2, r1.yzzw, s2
    mul r2, r2, c17.x
    texld r3, v0, s1
    mul r4.w, r3.y, c18.x
    mul r4.xyz, r4.w, c13
    cmp r4, -r3.y, c21.y, r4
    mul r1.y, r2.w, r3.z
    max r1.z, r3.z, c21.z
    add r2.xyz, r2, c11
    mad r2.w, c10.x, r1.z, r1.y
    add r2, r4, r2
    mul oC0.w, r2.w, c14.x
    dp3 r1.y, r0, c22
    add r1.y, r1.y, -c12.x
    mul r0.w, r0.w, r1.x
    mul r0.w, r0.w, c20.x
    mul r0.xyz, r0.w, r0
    cmp oC1.xyz, r1.y, r0, c21.y
    mov oC1.w, c21.x
    mov oC0.xyz, r2

// approximately 38 instruction slots used (5 texture, 33 arithmetic)
