//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 LightDirection;
//   float4 MapEnableState;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   LightDirection      c0       1
//   SpecularPower       c1       1
//   MapEnableState      c2       1
//   gLightCount         c3       1
//   gOverrideColorRatio c4       1
//   gOverrideColor      c5       1
//   gFogMode            c6       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c1   = { 8, 0, 0, 0 };
//
//   MapEnableState
//     c2   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c3   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c4   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c5   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c6   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c2.xyz, r0.w, r0.xyz
    add r0.x, c3.x, (-8)
    neg r0.y, c3.x
    cmp c0.x, r0.x, (-8), r0.y
    neg r0.x, c2.x
    cmp ob1.x, r0.x, (0), (1)
    mul c3.x, c1.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c4.xyz, r1.x, c0.xyz
    max r0.x, c4.x, (0)
    min r1.x, r0.x, (1)
    mul c7.xyz, r1.x, c5.xyz
    neg r0.x, r1.x
    add c6.x, r0.x, (1)
    add r0.x, c6.x, (-3)
    neg r1.x, r0.x
    max c8.x, r0.x, r1.x
    add r0.x, c6.x, (-1)
    neg r1.x, r0.x
    max c9.x, r0.x, r1.x
    add r0.x, c6.x, (-2)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x

// approximately 27 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   sampler2D MaskMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gOverrideAlpha;
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b0       1
//   gLightType            c11      8
//   gLightDiffuse         c19      8
//   gLightAmbient         c27      8
//   gLightPos             c35      8
//   gLightDir             c43      8
//   gRange                c51      8
//   gAttenuation0         c59      8
//   gAttenuation1         c67      8
//   gAttenuation2         c75      8
//   GlobalDiffuseAlpha    c83      1
//   SpecularBacklighting  c84      1
//   EnvCubeMapBrightness  c85      1
//   LightBrightness       c86      1
//   DiffuseBoost          c87      1
//   AmbientLightColor     c88      1
//   DiffuseMappingFactor  c89      1
//   NormalMappingFactor   c90      1
//   SpecularMappingFactor c91      1
//   EnvCubeMappingFactor  c92      1
//   HalfLambertPower      c93      1
//   HalfLambertBase       c94      1
//   SpecularLength        c95      1
//   SpecularHighlight     c96      1
//   gOverrideAlpha        c97      1
//   gFogColor             c98      1
//   gFogRange             c99      1
//   gFogDensity           c100     1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   AlphaMapSampler       s4       1
//   MaskMapSampler        s5       1
//
//
// Default values:
//
//   gUseMapLight
//     b0   = false;
//
//   gLightType
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//
//   gRange
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c83  = { 1, 0, 0, 0 };
//
//   SpecularBacklighting
//     c84  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c85  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c86  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c87  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c88  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c89  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c90  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c91  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c93  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c94  = { 0.5, 0, 0, 0 };
//
//   SpecularLength
//     c95  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c96  = { 1, 0, 0, 0 };
//
//   gOverrideAlpha
//     c97  = { 0, 0, 0, 0 };
//
//   gFogColor
//     c98  = { 0, 0, 0, 0 };
//
//   gFogRange
//     c99  = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c100 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c101, -4, -5, -6, -7
    def c102, 0.5, 1.44269502, 0, 0
    def c103, 2, -1, 0, 0
    def c104, -0, -1, -2, -3
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c103.x, c103.y
    texld r2, v0, s4
    mul r1.yzw, r1.y, v4.xxyz
    mad r1.xyz, v3, r1.x, r1.yzww
    mad r1.xyz, r1, c90.x, v1
    nrm r3.xyz, r1
    if b0
      mov r1.xyz, c103.w
      mov r4.xyz, c103.w
      mov r0.w, c103.w
      rep i0
        add r1.w, r0.w, c0.x
        cmp r1.w, r1.w, c103_abs.y, c103_abs.w
        break_ne r1.w, -r1.w
        add r5, r0.w, c104
        add r6, r0.w, c101
        mov r1.w, c103.w
        cmp r2.w, -r5_abs.x, c11.x, r1.w
        cmp r2.w, -r5_abs.y, c12.x, r2.w
        cmp r2.w, -r5_abs.z, c13.x, r2.w
        cmp r2.w, -r5_abs.w, c14.x, r2.w
        cmp r2.w, -r6_abs.x, c15.x, r2.w
        cmp r2.w, -r6_abs.y, c16.x, r2.w
        cmp r2.w, -r6_abs.z, c17.x, r2.w
        cmp r2.w, -r6_abs.w, c18.x, r2.w
        if_eq r2.w, -c104.w
          cmp r7.xyz, -r5_abs.x, c43, r1.w
          cmp r7.xyz, -r5_abs.y, c44, r7
          cmp r7.xyz, -r5_abs.z, c45, r7
          cmp r7.xyz, -r5_abs.w, c46, r7
          cmp r7.xyz, -r6_abs.x, c47, r7
          cmp r7.xyz, -r6_abs.y, c48, r7
          cmp r7.xyz, -r6_abs.z, c49, r7
          cmp r7.xyz, -r6_abs.w, c50, r7
          dp3 r3.w, r7, r3
          mov r7.x, c102.x
          mad r3.w, r3.w, r7.x, c94.x
          pow r4.w, r3_abs.w, c93.x
          mul r3.w, r4.w, c86.x
          cmp r7.xyz, -r5_abs.x, c19, r1.w
          cmp r7.xyz, -r5_abs.y, c20, r7
          cmp r7.xyz, -r5_abs.z, c21, r7
          cmp r7.xyz, -r5_abs.w, c22, r7
          cmp r7.xyz, -r6_abs.x, c23, r7
          cmp r7.xyz, -r6_abs.y, c24, r7
          cmp r7.xyz, -r6_abs.z, c25, r7
          cmp r7.xyz, -r6_abs.w, c26, r7
          mad r1.xyz, r3.w, r7, r1
          cmp r7.xyz, -r5_abs.x, c27, r1.w
          cmp r7.xyz, -r5_abs.y, c28, r7
          cmp r7.xyz, -r5_abs.z, c29, r7
          cmp r7.xyz, -r5_abs.w, c30, r7
          cmp r7.xyz, -r6_abs.x, c31, r7
          cmp r7.xyz, -r6_abs.y, c32, r7
          cmp r7.xyz, -r6_abs.z, c33, r7
          cmp r7.xyz, -r6_abs.w, c34, r7
          add r4.xyz, r4, r7
        else
          add r2.w, r2.w, c103.y
          cmp r7.xyz, -r5_abs.x, c35, r1.w
          cmp r7.xyz, -r5_abs.y, c36, r7
          cmp r7.xyz, -r5_abs.z, c37, r7
          cmp r7.xyz, -r5_abs.w, c38, r7
          cmp r7.xyz, -r6_abs.x, c39, r7
          cmp r7.xyz, -r6_abs.y, c40, r7
          cmp r7.xyz, -r6_abs.z, c41, r7
          cmp r7.xyz, -r6_abs.w, c42, r7
          add r7.xyz, r7, -v5
          dp3 r3.w, r7, r7
          rsq r3.w, r3.w
          rcp r4.w, r3.w
          cmp r7.w, -r5_abs.x, c51.x, r1.w
          cmp r7.w, -r5_abs.y, c52.x, r7.w
          cmp r7.w, -r5_abs.z, c53.x, r7.w
          cmp r7.w, -r5_abs.w, c54.x, r7.w
          cmp r7.w, -r6_abs.x, c55.x, r7.w
          cmp r7.w, -r6_abs.y, c56.x, r7.w
          cmp r7.w, -r6_abs.z, c57.x, r7.w
          cmp r7.w, -r6_abs.w, c58.x, r7.w
          add r7.w, r4.w, -r7.w
          cmp r8.x, -r5_abs.x, c59.x, r1.w
          cmp r8.x, -r5_abs.y, c60.x, r8.x
          cmp r8.x, -r5_abs.z, c61.x, r8.x
          cmp r8.x, -r5_abs.w, c62.x, r8.x
          cmp r8.x, -r6_abs.x, c63.x, r8.x
          cmp r8.x, -r6_abs.y, c64.x, r8.x
          cmp r8.x, -r6_abs.z, c65.x, r8.x
          cmp r8.x, -r6_abs.w, c66.x, r8.x
          cmp r8.y, -r5_abs.x, c67.x, r1.w
          cmp r8.y, -r5_abs.y, c68.x, r8.y
          cmp r8.y, -r5_abs.z, c69.x, r8.y
          cmp r8.y, -r5_abs.w, c70.x, r8.y
          cmp r8.y, -r6_abs.x, c71.x, r8.y
          cmp r8.y, -r6_abs.y, c72.x, r8.y
          cmp r8.y, -r6_abs.z, c73.x, r8.y
          cmp r8.y, -r6_abs.w, c74.x, r8.y
          mad r8.x, r8.y, r4.w, r8.x
          cmp r8.y, -r5_abs.x, c75.x, r1.w
          cmp r8.y, -r5_abs.y, c76.x, r8.y
          cmp r8.y, -r5_abs.z, c77.x, r8.y
          cmp r8.y, -r5_abs.w, c78.x, r8.y
          cmp r8.y, -r6_abs.x, c79.x, r8.y
          cmp r8.y, -r6_abs.y, c80.x, r8.y
          cmp r8.y, -r6_abs.z, c81.x, r8.y
          cmp r8.y, -r6_abs.w, c82.x, r8.y
          mul r4.w, r4.w, r4.w
          mad r4.w, r4.w, r8.y, r8.x
          rcp r4.w, r4.w
          mul r7.xyz, r3.w, r7
          cmp r8.xyz, -r5_abs.x, c19, r1.w
          cmp r8.xyz, -r5_abs.y, c20, r8
          cmp r8.xyz, -r5_abs.z, c21, r8
          cmp r8.xyz, -r5_abs.w, c22, r8
          cmp r8.xyz, -r6_abs.x, c23, r8
          cmp r8.xyz, -r6_abs.y, c24, r8
          cmp r8.xyz, -r6_abs.z, c25, r8
          cmp r8.xyz, -r6_abs.w, c26, r8
          mul r8.xyz, r4.w, r8
          dp3_sat r3.w, r7, r3
          mad r7.xyz, r8, r3.w, r1
          cmp r8.xyz, -r5_abs.x, c27, r1.w
          cmp r8.xyz, -r5_abs.y, c28, r8
          cmp r5.xyz, -r5_abs.z, c29, r8
          cmp r5.xyz, -r5_abs.w, c30, r5
          cmp r5.xyz, -r6_abs.x, c31, r5
          cmp r5.xyz, -r6_abs.y, c32, r5
          cmp r5.xyz, -r6_abs.z, c33, r5
          cmp r5.xyz, -r6_abs.w, c34, r5
          mad r5.xyz, r5, r4.w, r4
          cmp r6.xyz, r7.w, r1, r7
          cmp r5.xyz, r7.w, r4, r5
          cmp r1.xyz, -r2_abs.w, r6, r1
          cmp r4.xyz, -r2_abs.w, r5, r4
        endif
        add r0.w, r0.w, -c103.y
      endrep
      if b1
        texld r5, v0, s5
        cmp r1.xyz, -r1_abs.x, r5.x, r1
      endif
    else
      dp3 r0.w, c2, r3
      mov r5.x, c102.x
      mad r0.w, r0.w, r5.x, c94.x
      pow r1.w, r0_abs.w, c93.x
      mul r1.xyz, r1.w, c86.x
      mov r4.xyz, c88.x
    endif
    mul r0.xyz, r0, c89.x
    add r5.xyz, r1, c87.x
    mad r0.xyz, r0, r5, r4
    mul r0.w, r2.x, c83.x
    add r1.x, r1.y, r1.x
    add r1.x, r1.z, r1.x
    dp3 r1.y, r3, c2
    mul r1.y, r1.y, -c101.x
    mad r1.yzw, r1.y, r3.xxyz, -c2.xxyz
    dp3 r1.y, r1.yzww, v2
    add r1.y, r1.y, -c95.x
    mov_sat r1.z, r1.y
    cmp r1.y, -c84.x, r1.z, r1.y
    mul r1.y, r1.y, c96.x
    pow r2.x, r1_abs.y, c3.x
    texld r4, v0, s1
    mul r1.yzw, r2.x, r4.xxyz
    dp3 r2.x, c4, r3
    add r2.x, r2.x, r2.x
    mad r3.xyz, r3, -r2.x, c4
    texld r3, r3, s2
    mul r1.yzw, r1, c91.x
    mul r3.xyz, r3, c85.x
    mul r3.xyz, r3, c92.x
    mul r2.xzw, r2.z, r3.xyyz
    mad r1.yzw, r1, r2.y, r2.xxzw
    add r1.yzw, r0.xxyz, r1
    cmp r0.xyz, -r1.x, r0, r1.yzww
    mov r1.x, c6.x
    mad r0.xyz, r0, r1.x, c7
    mul oC0.w, r0.w, c97.x
    mad r0.w, v5.w, c99.y, c99.x
    mul r1.x, c100.x, v5.w
    mul r1.y, r1.x, c102.y
    exp r1.y, r1.y
    rcp r1.y, r1.y
    mul r1.x, r1.x, r1.x
    mul r1.x, r1.x, c102.y
    exp r1.x, r1.x
    rcp r1.x, r1.x
    mov r2.y, c103.y
    cmp r1.x, -c10.x, r1.x, -r2.y
    cmp r1.x, -c9.x, r1.y, r1.x
    cmp_sat r0.w, -c8.x, r0.w, r1.x
    lrp oC0.xyz, r0.w, r0, c98

// approximately 214 instruction slots used (6 texture, 208 arithmetic)
