//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float ColorRate;
//   float2 gPixeloffset;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Color        c0       1
//   ColorRate    c1       1
//   gPixeloffset c2       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c1   = { 0, 0, 0, 0 };
//
//   gPixeloffset
//     c2   = { 0.00195313, 0.00195313, 0, 0 };
//

    preshader
    neg r0.x, c1.x
    add r1.x, r0.x, (1)
    mul c7.xyz, r1.x, c0.xyz
    mov c6.x, r1.x
    mul c0.xy, c2.xy, (0, -1)
    mul c1.x, c2.x, (1)
    mul c1.y, c2.y, (-1)
    mul c2.x, c2.x, (-1)
    mul c2.y, c2.y, (0)
    mul c3.xy, c2.xy, (1, 0)
    mul c4.x, c2.x, (-1)
    mul c4.y, c2.y, (1)
    mul c5.x, c2.x, (0)
    mul c5.y, c2.y, (1)

// approximately 14 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D DiffuseMapSampler;
//   float InlineAlpha;
//   float3x3 Kx;
//   float3x3 Ky;
//   float2 gPixeloffset;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   Kx                c8       3
//   Ky                c11      3
//   InlineAlpha       c14      1
//   gPixeloffset      c15      1
//   DiffuseMapSampler s0       1
//
//
// Default values:
//
//   Kx
//     c8   = { -1, -2, -1, 0 };
//     c9   = { 0, 0, 0, 0 };
//     c10  = { 1, 2, 1, 0 };
//
//   Ky
//     c11  = { 1, 0, -1, 0 };
//     c12  = { 2, 0, -2, 0 };
//     c13  = { 1, 0, -1, 0 };
//
//   InlineAlpha
//     c14  = { 0, 0, 0, 0 };
//
//   gPixeloffset
//     c15  = { 0.00195313, 0.00195313, 0, 0 };
//

    ps_2_0
    def c16, 0.300000012, 0.589999974, 0.109999999, 0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    add r1.xy, t0, c0
    add r2.xy, t0, -c15
    add r3.xy, t0, c1
    add r4.xy, t0, c2
    add r5.xy, t0, c3
    add r6.xy, t0, c4
    add r7.xy, t0, c5
    add r8.xy, t0, c15
    texld r1, r1, s0
    texld r2, r2, s0
    texld r3, r3, s0
    texld r4, r4, s0
    texld r5, r5, s0
    texld r6, r6, s0
    texld r7, r7, s0
    texld r8, r8, s0
    dp3 r0.w, r1, c16
    mul r2.w, r0.w, c12.x
    mul r0.w, r0.w, c9.x
    dp3 r3.w, r2, c16
    mad r4.w, r3.w, c11.x, r2.w
    mad r0.w, r3.w, c8.x, r0.w
    dp3 r5.w, r3, c16
    mad r4.w, r5.w, c13.x, r4.w
    mad r0.w, r5.w, c10.x, r0.w
    dp3 r5.w, r4, c16
    mad r6.w, r5.w, c11.y, r4.w
    mad r0.w, r5.w, c8.y, r0.w
    dp3 r5.w, r0, c16
    mad r6.w, r5.w, c12.y, r6.w
    mad r5.w, r5.w, c9.y, r0.w
    dp3 r7.w, r5, c16
    mad r6.w, r7.w, c13.y, r6.w
    mad r7.w, r7.w, c10.y, r5.w
    dp3 r8.w, r6, c16
    mad r0.x, r8.w, c11.z, r6.w
    mad r7.w, r8.w, c8.z, r7.w
    dp3 r8.w, r7, c16
    mad r0.x, r8.w, c12.z, r0.x
    mad r8.w, r8.w, c9.z, r7.w
    dp3 r0.y, r8, c16
    mad r0.x, r0.y, c13.z, r0.x
    mad r0.y, r0.y, c10.z, r8.w
    mul r0.x, r0.x, r0.x
    mad r0.x, r0.y, r0.y, r0.x
    rsq r0.x, r0.x
    rcp r0.x, r0.x
    mul r0.x, r0.x, c14.x
    mul r0.w, r0.x, c6.x
    mov r0.xyz, c7
    mov oC0, r0

// approximately 52 instruction slots used (9 texture, 43 arithmetic)
