//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 LightDirection;
//   float4 MapEnableState;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   float SpecularPower;
//   int gLightCount;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   LightDirection  c0       1
//   SpecularPower   c1       1
//   RefractionParam c2       1
//   RimLightParam   c3       1
//   MapEnableState  c4       1
//   gLightCount     c5       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c1   = { 8, 0, 0, 0 };
//
//   RefractionParam
//     c2   = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c3   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c4   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c5   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c4.x
    cmp ob0.x, r0.x, (0), (1)
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c65.xyz, r0.w, r0.xyz
    add r0.x, c5.x, (-8)
    neg r0.y, c5.x
    cmp c66.x, r0.x, (-8), r0.y
    mul c67.x, c1.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c68.xyz, r1.x, c0.xyz
    mul c69.x, c2.y, (0.015625)
    neg r0.x, c3.w
    add r1.x, r0.x, (1)
    neg r0.x, r1.x
    mov c70.x, r1.x
    add r1.x, r0.x, (1)
    rcp c71.x, r1.x

// approximately 20 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float4x4 ViewProjectionMatrix;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b1       1
//   gLightType            c0       8
//   gLightDiffuse         c8       8
//   gLightPos             c16      8
//   gLightDir             c24      8
//   gRange                c32      8
//   gAttenuation0         c40      8
//   gAttenuation1         c48      8
//   gAttenuation2         c56      8
//   ViewProjectionMatrix  c72      4
//   GlobalDiffuseAlpha    c76      1
//   SpecularBacklighting  c77      1
//   EnvCubeMapBrightness  c78      1
//   LightBrightness       c79      1
//   DiffuseBoost          c80      1
//   AmbientLightColor     c81      1
//   DiffuseMappingFactor  c82      1
//   NormalMappingFactor   c83      1
//   SpecularMappingFactor c84      1
//   EnvCubeMappingFactor  c85      1
//   HalfLambertPower      c86      1
//   HalfLambertBase       c87      1
//   SpecularLength        c88      1
//   SpecularHighlight     c89      1
//   RefractionParam       c90      1
//   RimLightParam         c91      1
//   MapEnableState        c92      1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   AlphaMapSampler       s4       1
//   MaskMapSampler        s5       1
//
//
// Default values:
//
//   gUseMapLight
//     b1   = false;
//
//   gLightType
//     c0   = { 0, 0, 0, 0 };
//     c1   = { 0, 0, 0, 0 };
//     c2   = { 0, 0, 0, 0 };
//     c3   = { 0, 0, 0, 0 };
//     c4   = { 0, 0, 0, 0 };
//     c5   = { 0, 0, 0, 0 };
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c8   = { 0, 0, 0, 0 };
//     c9   = { 0, 0, 0, 0 };
//     c10  = { 0, 0, 0, 0 };
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//
//   gRange
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//
//   ViewProjectionMatrix
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c76  = { 1, 0, 0, 0 };
//
//   SpecularBacklighting
//     c77  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c78  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c79  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c80  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c81  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c82  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c83  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c84  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c85  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c86  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c87  = { 0.5, 0, 0, 0 };
//
//   SpecularLength
//     c88  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c89  = { 1, 0, 0, 0 };
//
//   RefractionParam
//     c90  = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c91  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c92  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c93, -0, -1, -2, -3
    def c94, -4, -5, -6, -7
    def c95, 2, -1, 4, 0.5
    def c96, 0, 0, 1, 3
    def c97, -2, 3, 0, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c95.x, c95.y
    texld r2, v0, s4
    texld r3, v0, s5
    if !b0
    endif
    mul r1.yzw, r1.y, v4.xxyz
    mad r1.xyz, v3, r1.x, r1.yzww
    mad r1.xyz, r1, c83.x, v1
    nrm r4.xyz, r1
    dp3 r0.w, c65, r4
    mul r1.x, r0.w, c95.z
    mov r1.yw, c95
    mad r0.w, r0.w, r1.w, c87.x
    pow r1.z, r0_abs.w, c86.x
    mul r3.yzw, r1.z, c79.x
    if b1
      mov r5.xyz, c96.y
      mov r0.w, c96.y
      rep i0
        add r2.w, r0.w, c66.x
        cmp r2.w, r2.w, c96.z, c96.y
        break_ne r2.w, -r2.w
        add r6, r0.w, c93
        add r7, r0.w, c94
        mov r8.y, c96.y
        cmp r2.w, -r6_abs.x, c0.x, r8.y
        cmp r2.w, -r6_abs.y, c1.x, r2.w
        cmp r2.w, -r6_abs.z, c2.x, r2.w
        cmp r2.w, -r6_abs.w, c3.x, r2.w
        cmp r2.w, -r7_abs.x, c4.x, r2.w
        cmp r2.w, -r7_abs.y, c5.x, r2.w
        cmp r2.w, -r7_abs.z, c6.x, r2.w
        cmp r2.w, -r7_abs.w, c7.x, r2.w
        if_eq r2.w, c96.w
          cmp r8.xzw, -r6_abs.x, c24.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c25.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c26.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c27.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c28.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c29.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c30.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c31.xyyz, r8
          dp3 r4.w, r8.xzww, r4
          mad r4.w, r4.w, r1.w, c87.x
          pow r5.w, r4_abs.w, c86.x
          mul r4.w, r5.w, c79.x
          cmp r8.xzw, -r6_abs.x, c8.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c9.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c10.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c11.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c12.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c13.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c14.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c15.xyyz, r8
          mad r5.xyz, r4.w, r8.xzww, r5
        else
          add r2.w, r2.w, c95.y
          cmp r8.xzw, -r6_abs.x, c16.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c17.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c18.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c19.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c20.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c21.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c22.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c23.xyyz, r8
          add r8.xzw, r8, -v5.xyyz
          dp3 r4.w, r8.xzww, r8.xzww
          rsq r4.w, r4.w
          rcp r5.w, r4.w
          cmp r9.x, -r6_abs.x, c32.x, r8.y
          cmp r9.x, -r6_abs.y, c33.x, r9.x
          cmp r9.x, -r6_abs.z, c34.x, r9.x
          cmp r9.x, -r6_abs.w, c35.x, r9.x
          cmp r9.x, -r7_abs.x, c36.x, r9.x
          cmp r9.x, -r7_abs.y, c37.x, r9.x
          cmp r9.x, -r7_abs.z, c38.x, r9.x
          cmp r9.x, -r7_abs.w, c39.x, r9.x
          add r9.x, r5.w, -r9.x
          cmp r9.y, -r6_abs.x, c40.x, r8.y
          cmp r9.y, -r6_abs.y, c41.x, r9.y
          cmp r9.y, -r6_abs.z, c42.x, r9.y
          cmp r9.y, -r6_abs.w, c43.x, r9.y
          cmp r9.y, -r7_abs.x, c44.x, r9.y
          cmp r9.y, -r7_abs.y, c45.x, r9.y
          cmp r9.y, -r7_abs.z, c46.x, r9.y
          cmp r9.y, -r7_abs.w, c47.x, r9.y
          cmp r9.z, -r6_abs.x, c48.x, r8.y
          cmp r9.z, -r6_abs.y, c49.x, r9.z
          cmp r9.z, -r6_abs.z, c50.x, r9.z
          cmp r9.z, -r6_abs.w, c51.x, r9.z
          cmp r9.z, -r7_abs.x, c52.x, r9.z
          cmp r9.z, -r7_abs.y, c53.x, r9.z
          cmp r9.z, -r7_abs.z, c54.x, r9.z
          cmp r9.z, -r7_abs.w, c55.x, r9.z
          mad r9.y, r9.z, r5.w, r9.y
          cmp r9.z, -r6_abs.x, c56.x, r8.y
          cmp r9.z, -r6_abs.y, c57.x, r9.z
          cmp r9.z, -r6_abs.z, c58.x, r9.z
          cmp r9.z, -r6_abs.w, c59.x, r9.z
          cmp r9.z, -r7_abs.x, c60.x, r9.z
          cmp r9.z, -r7_abs.y, c61.x, r9.z
          cmp r9.z, -r7_abs.z, c62.x, r9.z
          cmp r9.z, -r7_abs.w, c63.x, r9.z
          mul r5.w, r5.w, r5.w
          mad r5.w, r5.w, r9.z, r9.y
          rcp r5.w, r5.w
          mul r8.xzw, r4.w, r8
          cmp r9.yzw, -r6_abs.x, c8.xxyz, r8.y
          cmp r9.yzw, -r6_abs.y, c9.xxyz, r9
          cmp r6.xyz, -r6_abs.z, c10, r9.yzww
          cmp r6.xyz, -r6_abs.w, c11, r6
          cmp r6.xyz, -r7_abs.x, c12, r6
          cmp r6.xyz, -r7_abs.y, c13, r6
          cmp r6.xyz, -r7_abs.z, c14, r6
          cmp r6.xyz, -r7_abs.w, c15, r6
          mul r6.xyz, r5.w, r6
          dp3_sat r4.w, r8.xzww, r4
          mad r6.xyz, r6, r4.w, r5
          cmp r6.xyz, r9.x, r5, r6
          cmp r5.xyz, -r2_abs.w, r6, r5
        endif
        add r0.w, r0.w, -c95.y
      endrep
      cmp r6.xyz, -r5_abs.x, r3.x, r5
      cmp r3.yzw, -c92.x, r5.xxyz, r6.xxyz
    endif
    mul r0.xyz, r0, c82.x
    mov r3.x, c79.x
    mad r0.w, r1.z, r3.x, c80.x
    mad r0.xyz, r0, r0.w, c81.x
    mul r0.w, r2.x, c76.x
    add r1.z, r3.z, r3.y
    add r1.z, r3.w, r1.z
    mad r3.xyz, r1.x, r4, -c65
    dp3 r1.x, r3, v2
    add r1.x, r1.x, -c88.x
    mov_sat r1.w, r1.x
    cmp r1.x, -c77.x, r1.w, r1.x
    mul r1.x, r1.x, c89.x
    pow r2.x, r1_abs.x, c67.x
    texld r3, v0, s1
    mul r3.xyz, r2.x, r3
    dp3 r1.x, c68, r4
    add r1.x, r1.x, r1.x
    mad r5.xyz, r4, -r1.x, c68
    texld r5, r5, s2
    mul r5.xyz, r5, c78.x
    mul r5.xyz, r5, c85.x
    mul r2.xzw, r2.z, r5.xyyz
    mad r2.xzw, r3.xyyz, c84.x, r2
    add r2.xzw, r0.xyyz, r2
    cmp oC0.xyz, -r1.z, r0, r2.xzww
    mad r0.x, c90.x, -r2.y, -r1.y
    dp3 r1.x, r4, c72
    dp3 r1.y, r4, c73
    dp3 r0.y, r4, c75
    rcp r0.y, r0.y
    mad r0.yz, r1.xxyw, r0.y, -c95.y
    mul r1.xy, r0.yzzw, c95.w
    mul r1.z, r2.y, c69.x
    dp3 r0.y, v2, r4
    add r0.z, -r0.y, -c95.y
    cmp r0.y, r0.y, r0.z, -c95.y
    add r0.y, r0.y, -c70.x
    mul_sat r0.y, r0.y, c71.x
    mad r0.z, r0.y, c97.x, c97.y
    mul r0.y, r0.y, r0.y
    mul r0.xy, r0, r0.wzzw
    mul r3.xyz, r0.y, c91
    mov r1.w, c69.x
    cmp oC1, -r2.y, c96.y, r1
    mov r3.w, c95.w
    cmp oC2, -r2.y, c96.y, r3
    cmp oC0.w, -r2.y, r0.w, r0.x

// approximately 195 instruction slots used (6 texture, 189 arithmetic)
