//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float ColorRate;
//   float EmissiveMapThreshold;
//   float GlobalDiffuseAlpha;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float Sprinker;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   theAccumTime            c1       1
//   GlobalDiffuseAlpha      c2       1
//   TexturePanningVelocityU c3       1
//   TexturePanningVelocityV c4       1
//   ColorRate               c5       1
//   Sprinker                c6       1
//   MapEnableState          c7       1
//   EmissiveMapThreshold    c8       1
//   NoiseMapUVFlowSpeed     c9       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c1   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c2   = { 1, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c3   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c4   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c5   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c6   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c7   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c8   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c9   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c7.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c1.x, c9.xy
    mul c2.x, c1.x, c6.x
    neg r0.x, c6.x
    max c3.x, r0.x, c6.x
    mul c6.x, c1.x, c3.x
    mul c6.y, c1.x, c4.x
    mul c7.x, c1.x, (0.55)
    neg r0.x, c4.x
    max r1.x, r0.x, c4.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c3.x
    max r1.y, r0.x, c3.x
    neg r0.x, r1.y
    cmp c8.x, r0.x, (-0), r1.x
    neg r0.x, c8.x
    add c9.x, r0.x, (1)
    neg r0.x, c5.x
    add r1.x, r0.x, (1)
    add r1.y, r0.x, (0.6)
    max r0.x, r1.y, (0)
    min r1.y, r0.x, (1)
    mul c11.xyz, r1.x, c0.xyz
    mul r0.x, r1.y, (-2)
    mul r0.y, r1.y, r1.y
    add r1.x, r0.x, (3)
    mul r2.x, r0.y, r1.x
    mul r0.x, r2.x, r2.x
    mul r1.x, r0.x, r2.x
    mov c10.x, r2.x
    mul r0.x, r1.x, (3)
    neg r0.y, c2.x
    add r1.x, r0.y, r0.x
    cmp r2.x, r1.x, c2.x, r0.x
    add c12.x, r2.x, c2.x

// approximately 37 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float EmissiveMapIntensity;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   bool IsGradation;
//   bool IsScanner;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D OverlayMapSampler;
//   sampler2D OverlayMapSampler2;
//   float Sprinker;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   IsGradation          b1       1
//   HightLightColor      c13      1
//   GlobalDiffuseAlpha   c14      1
//   IsScanner            c15      1
//   TextureTileX         c16      1
//   TextureTileY         c17      1
//   Sprinker             c18      1
//   EffectAlpha          c19      1
//   HightLightPower      c20      1
//   MapEnableState       c21      1
//   EmissiveMapIntensity c22      1
//   DiffuseMapSampler    s0       1
//   AlphaMapSampler2     s1       1
//   OverlayMapSampler    s2       1
//   OverlayMapSampler2   s3       1
//   MaskMapSampler       s4       1
//   NoiseMapSampler      s5       1
//
//
// Default values:
//
//   IsGradation
//     b1   = false;
//
//   HightLightColor
//     c13  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c14  = { 1, 0, 0, 0 };
//
//   IsScanner
//     c15  = { 0, 0, 0, 0 };
//
//   TextureTileX
//     c16  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c17  = { 1, 0, 0, 0 };
//
//   Sprinker
//     c18  = { 0, 0, 0, 0 };
//
//   EffectAlpha
//     c19  = { 0, 0, 0, 0 };
//
//   HightLightPower
//     c20  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c21  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c22  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c23, 1, 0.5, 0, 0.300000012
    def c24, 0.150000006, 0.212599993, 0.715200007, 0.0722000003
    def c25, 4, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    texld r0, v0, s0
    if b0
      texld r1, v0, s4
      mov r1.x, r1.y
    else
      mov r1.x, c23.x
    endif
    add r1.yz, c1.xxyw, v0.xxyw
    texld r2, r1.yzzw, s5
    mov r3.xz, c23
    cmp r1.y, -c21.y, r3.x, r2.x
    add r2.x, -c2.x, v0.x
    mov r2.y, v0.y
    texld r2, r2, s3
    mul r2, r2, c18.x
    mul r2, r2, c23.xxxy
    cmp r2, -c18.x, r3.z, r2
    mad r3, r0, c23.y, c23.w
    max r4, r3, c23.z
    min r3, r4, c24.x
    add r3, r2, r3
    cmp r2, -c15.x, r2, r3
    mul r3.x, c16.x, v0.x
    mul r3.y, c17.x, v0.y
    add r1.zw, r3.xyxy, c6.xyxy
    add r3.xy, r3, c7.x
    cmp r1.zw, c8.x, r3.xyxy, r1
    texld r3, r1.zwzw, s2
    mad r3, r3, c19.x, r2
    cmp r2, -c3.x, r3, r2
    dp3 r1.z, r0, c24.yzww
    add r1.z, r1.z, -c9.x
    mul r1.x, r1.y, r1.x
    mul r1.x, r1.x, c22.x
    mul r1.xyw, r0.xyzz, r1.x
    cmp r1.xyz, r1.z, r1.xyww, c23.z
    mov r1.w, c23.x
    if b1
      texld r3, v0, s1
      mul r4.w, r3.y, c20.x
      mul r4.xyz, r4.w, c13
      cmp r4, -r3.y, c23.z, r4
      mul r3, r2, r3.z
      add r5.x, r0.x, c10.x
      mad r5.x, r3.x, c25.x, r5.x
      mad r5.yz, r3, c25.x, r0
      mov r3.x, c25.x
      mad r5.w, r3.w, r3.x, c14.x
      add r3, r4, r5
      mul oC0.w, r0.w, r3.w
      mov oC0.xyz, r3
      mov oC1, r1
    else
      add r0.xyz, r0, c11
      add oC0.xyz, r2, r0
      add r0.x, r2.w, c12.x
      mul oC0.w, r0.w, r0.x
      mov oC1, r1
    endif

// approximately 63 instruction slots used (6 texture, 57 arithmetic)
