//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float EmissiveMapThreshold;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   float SpecularPower;
//   int gLightCount;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   LightDirection       c0       1
//   theAccumTime         c1       1
//   SpecularPower        c2       1
//   RefractionParam      c3       1
//   RimLightParam        c4       1
//   MapEnableState       c5       1
//   EmissiveMapThreshold c6       1
//   NoiseMapUVFlowSpeed  c7       1
//   gLightCount          c8       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c1   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c2   = { 8, 0, 0, 0 };
//
//   RefractionParam
//     c3   = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c4   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c5   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c6   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c7   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c8   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c5.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c1.x, c7.xy
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c2.xyz, r0.w, r0.xyz
    add r0.x, c8.x, (-8)
    neg r0.y, c8.x
    cmp c3.x, r0.x, (-8), r0.y
    mul c4.x, c2.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c5.xyz, r1.x, c0.xyz
    mul c6.x, c3.y, (0.015625)
    neg r0.x, c4.w
    add r1.x, r0.x, (1)
    neg r0.x, r1.x
    mov c7.x, r1.x
    add r1.x, r0.x, (1)
    rcp c8.x, r1.x
    neg r0.x, c6.x
    add c9.x, r0.x, (1)

// approximately 23 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EmissiveMapIntensity;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float4x4 ViewProjectionMatrix;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b1       1
//   gLightType            c10      8
//   gLightDiffuse         c18      8
//   gLightPos             c26      8
//   gLightDir             c34      8
//   gRange                c42      8
//   gAttenuation0         c50      8
//   gAttenuation1         c58      8
//   gAttenuation2         c66      8
//   ViewProjectionMatrix  c74      4
//   GlobalDiffuseAlpha    c78      1
//   SpecularBacklighting  c79      1
//   EnvCubeMapBrightness  c80      1
//   LightBrightness       c81      1
//   DiffuseBoost          c82      1
//   AmbientLightColor     c83      1
//   DiffuseMappingFactor  c84      1
//   NormalMappingFactor   c85      1
//   SpecularMappingFactor c86      1
//   EnvCubeMappingFactor  c87      1
//   HalfLambertPower      c88      1
//   HalfLambertBase       c89      1
//   SpecularLength        c90      1
//   SpecularHighlight     c91      1
//   RefractionParam       c92      1
//   RimLightParam         c93      1
//   MapEnableState        c94      1
//   EmissiveMapIntensity  c95      1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   AlphaMapSampler       s4       1
//   MaskMapSampler        s5       1
//   NoiseMapSampler       s6       1
//
//
// Default values:
//
//   gUseMapLight
//     b1   = false;
//
//   gLightType
//     c10  = { 0, 0, 0, 0 };
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//
//   gRange
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//
//   ViewProjectionMatrix
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c78  = { 1, 0, 0, 0 };
//
//   SpecularBacklighting
//     c79  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c80  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c81  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c82  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c83  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c84  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c85  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c86  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c87  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c88  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c89  = { 0.5, 0, 0, 0 };
//
//   SpecularLength
//     c90  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c91  = { 1, 0, 0, 0 };
//
//   RefractionParam
//     c92  = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c93  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c94  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c95  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c96, 0.5, 0, 0, 1
    def c97, -0, -1, -2, -3
    def c98, -4, -5, -6, -7
    def c99, 2, -1, 1, 4
    def c100, -2, 3, 0, 0
    def c101, 0.212599993, 0.715200007, 0.0722000003, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c99.x, c99.y
    texld r2, v0, s4
    texld r3, v0, s5
    if b0
      mov r0.w, r3.y
    else
      mov r0.w, r3.y
    endif
    add r1.zw, c1.xyxy, v0.xyxy
    texld r4, r1.zwzw, s6
    mov r1.z, c99.z
    cmp r1.w, -c94.y, r1.z, r4.x
    mul r3.yzw, r1.y, v4.xxyz
    mad r3.yzw, v3.xxyz, r1.x, r3
    mad r3.yzw, r3, c85.x, v1.xxyz
    nrm r4.xyz, r3.yzww
    dp3 r1.x, c2, r4
    mul r1.y, r1.x, c99.w
    mov r5.xz, c96
    mad r1.x, r1.x, r5.x, c89.x
    pow r2.w, r1_abs.x, c88.x
    mul r3.yzw, r2.w, c81.x
    if b1
      mov r6.xyz, c96.z
      mov r1.x, c96.z
      rep i0
        add r4.w, r1.x, c3.x
        cmp r4.w, r4.w, c96.w, c96.z
        break_ne r4.w, -r4.w
        add r7, r1.x, c97
        add r8, r1.x, c98
        cmp r4.w, -r7_abs.x, c10.x, r5.z
        cmp r4.w, -r7_abs.y, c11.x, r4.w
        cmp r4.w, -r7_abs.z, c12.x, r4.w
        cmp r4.w, -r7_abs.w, c13.x, r4.w
        cmp r4.w, -r8_abs.x, c14.x, r4.w
        cmp r4.w, -r8_abs.y, c15.x, r4.w
        cmp r4.w, -r8_abs.z, c16.x, r4.w
        cmp r4.w, -r8_abs.w, c17.x, r4.w
        if_eq r4.w, -c97.w
          cmp r9.xyz, -r7_abs.x, c34, r5.z
          cmp r9.xyz, -r7_abs.y, c35, r9
          cmp r9.xyz, -r7_abs.z, c36, r9
          cmp r9.xyz, -r7_abs.w, c37, r9
          cmp r9.xyz, -r8_abs.x, c38, r9
          cmp r9.xyz, -r8_abs.y, c39, r9
          cmp r9.xyz, -r8_abs.z, c40, r9
          cmp r9.xyz, -r8_abs.w, c41, r9
          dp3 r5.y, r9, r4
          mad r5.y, r5.y, r5.x, c89.x
          pow r6.w, r5_abs.y, c88.x
          mul r5.y, r6.w, c81.x
          cmp r9.xyz, -r7_abs.x, c18, r5.z
          cmp r9.xyz, -r7_abs.y, c19, r9
          cmp r9.xyz, -r7_abs.z, c20, r9
          cmp r9.xyz, -r7_abs.w, c21, r9
          cmp r9.xyz, -r8_abs.x, c22, r9
          cmp r9.xyz, -r8_abs.y, c23, r9
          cmp r9.xyz, -r8_abs.z, c24, r9
          cmp r9.xyz, -r8_abs.w, c25, r9
          mad r6.xyz, r5.y, r9, r6
        else
          add r4.w, r4.w, c99.y
          cmp r9.xyz, -r7_abs.x, c26, r5.z
          cmp r9.xyz, -r7_abs.y, c27, r9
          cmp r9.xyz, -r7_abs.z, c28, r9
          cmp r9.xyz, -r7_abs.w, c29, r9
          cmp r9.xyz, -r8_abs.x, c30, r9
          cmp r9.xyz, -r8_abs.y, c31, r9
          cmp r9.xyz, -r8_abs.z, c32, r9
          cmp r9.xyz, -r8_abs.w, c33, r9
          add r9.xyz, r9, -v5
          dp3 r5.y, r9, r9
          rsq r5.y, r5.y
          rcp r5.w, r5.y
          cmp r6.w, -r7_abs.x, c42.x, r5.z
          cmp r6.w, -r7_abs.y, c43.x, r6.w
          cmp r6.w, -r7_abs.z, c44.x, r6.w
          cmp r6.w, -r7_abs.w, c45.x, r6.w
          cmp r6.w, -r8_abs.x, c46.x, r6.w
          cmp r6.w, -r8_abs.y, c47.x, r6.w
          cmp r6.w, -r8_abs.z, c48.x, r6.w
          cmp r6.w, -r8_abs.w, c49.x, r6.w
          add r6.w, r5.w, -r6.w
          cmp r9.w, -r7_abs.x, c50.x, r5.z
          cmp r9.w, -r7_abs.y, c51.x, r9.w
          cmp r9.w, -r7_abs.z, c52.x, r9.w
          cmp r9.w, -r7_abs.w, c53.x, r9.w
          cmp r9.w, -r8_abs.x, c54.x, r9.w
          cmp r9.w, -r8_abs.y, c55.x, r9.w
          cmp r9.w, -r8_abs.z, c56.x, r9.w
          cmp r9.w, -r8_abs.w, c57.x, r9.w
          cmp r10.x, -r7_abs.x, c58.x, r5.z
          cmp r10.x, -r7_abs.y, c59.x, r10.x
          cmp r10.x, -r7_abs.z, c60.x, r10.x
          cmp r10.x, -r7_abs.w, c61.x, r10.x
          cmp r10.x, -r8_abs.x, c62.x, r10.x
          cmp r10.x, -r8_abs.y, c63.x, r10.x
          cmp r10.x, -r8_abs.z, c64.x, r10.x
          cmp r10.x, -r8_abs.w, c65.x, r10.x
          mad r9.w, r10.x, r5.w, r9.w
          cmp r10.x, -r7_abs.x, c66.x, r5.z
          cmp r10.x, -r7_abs.y, c67.x, r10.x
          cmp r10.x, -r7_abs.z, c68.x, r10.x
          cmp r10.x, -r7_abs.w, c69.x, r10.x
          cmp r10.x, -r8_abs.x, c70.x, r10.x
          cmp r10.x, -r8_abs.y, c71.x, r10.x
          cmp r10.x, -r8_abs.z, c72.x, r10.x
          cmp r10.x, -r8_abs.w, c73.x, r10.x
          mul r5.w, r5.w, r5.w
          mad r5.w, r5.w, r10.x, r9.w
          rcp r5.w, r5.w
          mul r9.xyz, r5.y, r9
          cmp r10.xyz, -r7_abs.x, c18, r5.z
          cmp r10.xyz, -r7_abs.y, c19, r10
          cmp r7.xyz, -r7_abs.z, c20, r10
          cmp r7.xyz, -r7_abs.w, c21, r7
          cmp r7.xyz, -r8_abs.x, c22, r7
          cmp r7.xyz, -r8_abs.y, c23, r7
          cmp r7.xyz, -r8_abs.z, c24, r7
          cmp r7.xyz, -r8_abs.w, c25, r7
          mul r7.xyz, r5.w, r7
          dp3_sat r5.y, r9, r4
          mad r7.xyz, r7, r5.y, r6
          cmp r7.xyz, r6.w, r6, r7
          cmp r6.xyz, -r4_abs.w, r7, r6
        endif
        add r1.x, r1.x, c99.z
      endrep
      cmp r5.xyz, -r6_abs.x, r3.x, r6
      cmp r3.yzw, -c94.x, r6.xxyz, r5.xxyz
    endif
    mul r5.xyz, r0, c84.x
    mov r1.x, c81.x
    mad r1.x, r2.w, r1.x, c82.x
    mad r5.xyz, r5, r1.x, c83.x
    mul r1.x, r2.x, c78.x
    add r2.x, r3.z, r3.y
    add r2.x, r3.w, r2.x
    mad r3.xyz, r1.y, r4, -c2
    dp3 r1.y, r3, v2
    add r1.y, r1.y, -c90.x
    mov_sat r2.w, r1.y
    cmp r1.y, -c79.x, r2.w, r1.y
    mul r1.y, r1.y, c91.x
    pow r2.w, r1_abs.y, c4.x
    texld r3, v0, s1
    mul r3.xyz, r2.w, r3
    dp3 r1.y, c5, r4
    add r1.y, r1.y, r1.y
    mad r6.xyz, r4, -r1.y, c5
    texld r6, r6, s2
    mul r6.xyz, r6, c80.x
    mul r6.xyz, r6, c87.x
    mul r6.xyz, r2.z, r6
    mad r3.xyz, r3, c86.x, r6
    add r3.xyz, r3, r5
    cmp oC0.xyz, -r2.x, r5, r3
    mad r1.y, c92.x, -r2.y, r1.z
    mul r1.y, r1.y, r1.x
    dp3 r3.x, r4, c74
    dp3 r3.y, r4, c75
    dp3 r1.z, r4, c77
    rcp r1.z, r1.z
    mad r2.xz, r3.xyyw, r1.z, c99.z
    mul r3.xy, r2.xzzw, c96.x
    mul r3.z, r2.y, c6.x
    dp3 r1.z, v2, r4
    add r2.x, -r1.z, c99.z
    cmp r1.z, r1.z, r2.x, c99.z
    add r1.z, r1.z, -c7.x
    mul_sat r1.z, r1.z, c8.x
    mad r2.x, r1.z, c100.x, c100.y
    mul r1.z, r1.z, r1.z
    mul r1.z, r1.z, r2.x
    mul r4.xyz, r1.z, c93
    mov r3.w, c6.x
    cmp oC1, -r2.y, c96.z, r3
    mov r4.w, c96.x
    cmp oC2, -r2.y, c96.z, r4
    cmp oC0.w, -r2.y, r1.x, r1.y
    dp3 r1.x, r0, c101
    add r1.x, r1.x, -c9.x
    mul r0.w, r0.w, r1.w
    mul r0.w, r0.w, c95.x
    mul r0.xyz, r0.w, r0
    cmp oC3.xyz, r1.x, r0, c96.z
    mov oC3.w, c99.z

// approximately 209 instruction slots used (7 texture, 202 arithmetic)
