//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 LightDirection;
//   float RefractionIndex;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   LightDirection      c0       1
//   SpecularPower       c1       1
//   RefractionIndex     c2       1
//   gLightCount         c3       1
//   gOverrideColorRatio c4       1
//   gOverrideColor      c5       1
//   gFogMode            c6       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c1   = { 8, 0, 0, 0 };
//
//   RefractionIndex
//     c2   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c3   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c4   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c5   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c6   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c0.xyz, r0.w, r0.xyz
    mul c1.x, c1.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c2.xyz, r1.x, c0.xyz
    mul c3.x, c2.x, c2.x
    add r0.x, c3.x, (-8)
    neg r0.y, c3.x
    cmp c4.x, r0.x, (-8), r0.y
    max r0.x, c4.x, (0)
    min r1.x, r0.x, (1)
    mul c7.xyz, r1.x, c5.xyz
    neg r0.x, r1.x
    add c6.x, r0.x, (1)
    add r0.x, c6.x, (-3)
    neg r1.x, r0.x
    max c8.x, r0.x, r1.x
    add r0.x, c6.x, (-1)
    neg r1.x, r0.x
    max c9.x, r0.x, r1.x
    add r0.x, c6.x, (-2)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x

// approximately 26 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float NormalBoost;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float RefractionIndex;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gCamPos;
//   float4 gDefaultAmbient;
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   float4 gLightSpecular[8];
//   int gLightType[8];
//   float4 gMaterialAmbient;
//   float4 gMaterialDiffuse;
//   float4 gMaterialEmissive;
//   float4 gMaterialSpecular;
//   float gMaterialSpecularPower;
//   float gModulate;
//   float gOverrideAlpha;
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   gUseMapLight           b0       1
//   gLightType             c11      8
//   gLightDiffuse          c19      8
//   gLightSpecular         c27      8
//   gLightAmbient          c35      8
//   gLightPos              c43      8
//   gLightDir              c51      8
//   gRange                 c59      8
//   gAttenuation0          c67      8
//   gAttenuation1          c75      8
//   gAttenuation2          c83      8
//   GlobalDiffuseAlpha     c91      1
//   NormalBoost            c92      1
//   EnvCubeMapBrightness   c93      1
//   LightBrightness        c94      1
//   DiffuseBoost           c95      1
//   AmbientLightColor      c96      1
//   DiffuseMappingFactor   c97      1
//   NormalMappingFactor    c98      1
//   SpecularMappingFactor  c99      1
//   EnvCubeMappingFactor   c100     1
//   HalfLambertPower       c101     1
//   HalfLambertBase        c102     1
//   RefractionIndex        c103     1
//   gCamPos                c104     1
//   gDefaultAmbient        c105     1
//   gMaterialDiffuse       c106     1
//   gMaterialAmbient       c107     1
//   gMaterialSpecular      c108     1
//   gMaterialSpecularPower c109     1
//   gMaterialEmissive      c110     1
//   gModulate              c111     1
//   gOverrideAlpha         c112     1
//   gFogColor              c113     1
//   gFogRange              c114     1
//   gFogDensity            c115     1
//   DiffuseMapSampler      s0       1
//   SpecularMapSampler     s1       1
//   CubeMapSampler         s2       1
//   NormalMapSampler       s3       1
//   AlphaMapSampler        s4       1
//
//
// Default values:
//
//   gUseMapLight
//     b0   = false;
//
//   gLightType
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//
//   gLightSpecular
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//
//   gRange
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c83  = { 0, 0, 0, 0 };
//     c84  = { 0, 0, 0, 0 };
//     c85  = { 0, 0, 0, 0 };
//     c86  = { 0, 0, 0, 0 };
//     c87  = { 0, 0, 0, 0 };
//     c88  = { 0, 0, 0, 0 };
//     c89  = { 0, 0, 0, 0 };
//     c90  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c91  = { 1, 0, 0, 0 };
//
//   NormalBoost
//     c92  = { 1, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c93  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c94  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c95  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c96  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c97  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c98  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c99  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c100 = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c101 = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c102 = { 0.5, 0, 0, 0 };
//
//   RefractionIndex
//     c103 = { 0, 0, 0, 0 };
//
//   gCamPos
//     c104 = { 0, 0, 0, 0 };
//
//   gDefaultAmbient
//     c105 = { 0, 0, 0, 0 };
//
//   gMaterialDiffuse
//     c106 = { 0, 0, 0, 0 };
//
//   gMaterialAmbient
//     c107 = { 0, 0, 0, 0 };
//
//   gMaterialSpecular
//     c108 = { 0, 0, 0, 0 };
//
//   gMaterialSpecularPower
//     c109 = { 0, 0, 0, 0 };
//
//   gMaterialEmissive
//     c110 = { 0, 0, 0, 0 };
//
//   gModulate
//     c111 = { 2, 0, 0, 0 };
//
//   gOverrideAlpha
//     c112 = { 0, 0, 0, 0 };
//
//   gFogColor
//     c113 = { 0, 0, 0, 0 };
//
//   gFogRange
//     c114 = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c115 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c116, 2, -1, 4, 0.5
    def c117, -0, -1, -2, -3
    def c118, -4, -5, -6, -7
    def c119, 1.44269502, 0, 0, 0
    def c120, 1, 0, 0, 3
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord5 v3
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c116.x, c116.y
    texld r2, v0, s4
    add r0.w, r1.y, r1.x
    mad r1.xyz, r0.w, c98.x, v1
    nrm r3.xyz, r1
    mul r1.xyz, r3, c92.x
    dp3 r0.w, c0, r1
    mul r1.w, r0.w, c116.z
    mov r3.yw, c116
    mad r0.w, r0.w, r3.w, c102.x
    pow r2.w, r0_abs.w, c101.x
    mul r0.w, r2.w, c94.x
    mul r3.xzw, r0.xyyz, r0.w
    mul r0.xyz, r0, c95.x
    mul r0.xyz, r0, c97.x
    mad r0.xyz, r3.xzww, c97.x, r0
    add r0.xyz, r0, c96.x
    mul r2.x, r2.x, c91.x
    mad r3.xzw, r1.w, r1.xyyz, -c0.xyyz
    dp3 r1.w, r3.xzww, v2
    pow r2.w, r1_abs.w, c1.x
    texld r4, v0, s1
    mul r3.xzw, r2.w, r4.xyyz
    dp3 r1.w, c2, r1
    mad r2.w, r1.w, -r1.w, -c116.y
    mad r2.w, c3.x, -r2.w, -r3.y
    cmp r4.x, r2.w, c120.x, c120.y
    mul r2.w, r2.w, r4.x
    mul r4.x, r4.x, c103.x
    rsq r2.w, r2.w
    rcp r2.w, r2.w
    mad r1.w, r4.x, r1.w, r2.w
    mul r4.yzw, r1.xxyz, r1.w
    mad r4.xyz, r4.x, c2, -r4.yzww
    texld r4, r4, s2
    mul r3.xzw, r3, c99.x
    mul r4.xyz, r4, c93.x
    mul r4.xyz, r4, c100.x
    mul r4.xyz, r2.z, r4
    mad r2.yzw, r3.xxzw, r2.y, r4.xxyz
    add r2.yzw, r0.xxyz, r2
    cmp r0.xyz, -r0.w, r0, r2.yzww
    if b0
      nrm r4.xyz, r1
      add r1.xyz, c104, -v3
      dp3 r0.w, r1, r1
      rsq r0.w, r0.w
      mov r2.yzw, c120.y
      mov r3.xzw, c105.xyyz
      mov r5.xyz, c120.y
      mov r1.w, c120.y
      rep i0
        add r4.w, r1.w, c4.x
        cmp r4.w, r4.w, c120.x, c120.y
        break_ne r4.w, -r4.w
        add r6, r1.w, c117
        add r7, r1.w, c118
        mov r8.y, c120.y
        cmp r4.w, -r6_abs.x, c11.x, r8.y
        cmp r4.w, -r6_abs.y, c12.x, r4.w
        cmp r4.w, -r6_abs.z, c13.x, r4.w
        cmp r4.w, -r6_abs.w, c14.x, r4.w
        cmp r4.w, -r7_abs.x, c15.x, r4.w
        cmp r4.w, -r7_abs.y, c16.x, r4.w
        cmp r4.w, -r7_abs.z, c17.x, r4.w
        cmp r4.w, -r7_abs.w, c18.x, r4.w
        if_eq r4.w, c120.w
          cmp r8.xzw, -r6_abs.x, c19.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c20.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c21.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c22.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c23.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c24.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c25.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c26.xyyz, r8
          cmp r9.xyz, -r6_abs.x, c51, r8.y
          cmp r9.xyz, -r6_abs.y, c52, r9
          cmp r9.xyz, -r6_abs.z, c53, r9
          cmp r9.xyz, -r6_abs.w, c54, r9
          cmp r9.xyz, -r7_abs.x, c55, r9
          cmp r9.xyz, -r7_abs.y, c56, r9
          cmp r9.xyz, -r7_abs.z, c57, r9
          cmp r9.xyz, -r7_abs.w, c58, r9
          dp3_sat r5.w, r9, r4
          mad r2.yzw, r8.xxzw, r5.w, r2
          cmp r8.xzw, -r6_abs.x, c35.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c36.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c37.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c38.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c39.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c40.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c41.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c42.xyyz, r8
          add r3.xzw, r3, r8
          cmp r8.xzw, -r6_abs.x, c27.xyyz, r8.y
          cmp r8.xzw, -r6_abs.y, c28.xyyz, r8
          cmp r8.xzw, -r6_abs.z, c29.xyyz, r8
          cmp r8.xzw, -r6_abs.w, c30.xyyz, r8
          cmp r8.xzw, -r7_abs.x, c31.xyyz, r8
          cmp r8.xzw, -r7_abs.y, c32.xyyz, r8
          cmp r8.xzw, -r7_abs.z, c33.xyyz, r8
          cmp r8.xzw, -r7_abs.w, c34.xyyz, r8
          mad r9.xyz, r1, r0.w, r9
          nrm r10.xyz, r9
          dp3_sat r5.w, r4, r10
          pow r9.x, r5.w, c109.x
          mul r8.xzw, r8, r9.x
          cmp r8.xzw, -c109.x, r8.y, r8
          add r5.xyz, r5, r8.xzww
        else
          if_eq r4.w, -c116.y
            cmp r8.xzw, -r6_abs.x, c43.xyyz, r8.y
            cmp r8.xzw, -r6_abs.y, c44.xyyz, r8
            cmp r8.xzw, -r6_abs.z, c45.xyyz, r8
            cmp r8.xzw, -r6_abs.w, c46.xyyz, r8
            cmp r8.xzw, -r7_abs.x, c47.xyyz, r8
            cmp r8.xzw, -r7_abs.y, c48.xyyz, r8
            cmp r8.xzw, -r7_abs.z, c49.xyyz, r8
            cmp r8.xzw, -r7_abs.w, c50.xyyz, r8
            add r8.xzw, r8, -v3.xyyz
            dp3 r4.w, r8.xzww, r8.xzww
            rsq r4.w, r4.w
            rcp r5.w, r4.w
            cmp r9.x, -r6_abs.x, c59.x, r8.y
            cmp r9.x, -r6_abs.y, c60.x, r9.x
            cmp r9.x, -r6_abs.z, c61.x, r9.x
            cmp r9.x, -r6_abs.w, c62.x, r9.x
            cmp r9.x, -r7_abs.x, c63.x, r9.x
            cmp r9.x, -r7_abs.y, c64.x, r9.x
            cmp r9.x, -r7_abs.z, c65.x, r9.x
            cmp r9.x, -r7_abs.w, c66.x, r9.x
            if_lt r5.w, r9.x
              cmp r9.x, -r6_abs.x, c67.x, r8.y
              cmp r9.x, -r6_abs.y, c68.x, r9.x
              cmp r9.x, -r6_abs.z, c69.x, r9.x
              cmp r9.x, -r6_abs.w, c70.x, r9.x
              cmp r9.x, -r7_abs.x, c71.x, r9.x
              cmp r9.x, -r7_abs.y, c72.x, r9.x
              cmp r9.x, -r7_abs.z, c73.x, r9.x
              cmp r9.x, -r7_abs.w, c74.x, r9.x
              cmp r9.y, -r6_abs.x, c75.x, r8.y
              cmp r9.y, -r6_abs.y, c76.x, r9.y
              cmp r9.y, -r6_abs.z, c77.x, r9.y
              cmp r9.y, -r6_abs.w, c78.x, r9.y
              cmp r9.y, -r7_abs.x, c79.x, r9.y
              cmp r9.y, -r7_abs.y, c80.x, r9.y
              cmp r9.y, -r7_abs.z, c81.x, r9.y
              cmp r9.y, -r7_abs.w, c82.x, r9.y
              mad r9.x, r9.y, r5.w, r9.x
              cmp r9.y, -r6_abs.x, c83.x, r8.y
              cmp r9.y, -r6_abs.y, c84.x, r9.y
              cmp r9.y, -r6_abs.z, c85.x, r9.y
              cmp r9.y, -r6_abs.w, c86.x, r9.y
              cmp r9.y, -r7_abs.x, c87.x, r9.y
              cmp r9.y, -r7_abs.y, c88.x, r9.y
              cmp r9.y, -r7_abs.z, c89.x, r9.y
              cmp r9.y, -r7_abs.w, c90.x, r9.y
              mul r5.w, r5.w, r5.w
              mad r5.w, r5.w, r9.y, r9.x
              rcp r5.w, r5.w
              mul r8.xzw, r4.w, r8
              cmp r9.xyz, -r6_abs.x, c19, r8.y
              cmp r9.xyz, -r6_abs.y, c20, r9
              cmp r9.xyz, -r6_abs.z, c21, r9
              cmp r9.xyz, -r6_abs.w, c22, r9
              cmp r9.xyz, -r7_abs.x, c23, r9
              cmp r9.xyz, -r7_abs.y, c24, r9
              cmp r9.xyz, -r7_abs.z, c25, r9
              cmp r9.xyz, -r7_abs.w, c26, r9
              mul r9.xyz, r5.w, r9
              dp3_sat r4.w, r8.xzww, r4
              mad r2.yzw, r9.xxyz, r4.w, r2
              cmp r8.xzw, -r6_abs.x, c35.xyyz, r8.y
              cmp r8.xzw, -r6_abs.y, c36.xyyz, r8
              cmp r8.xzw, -r6_abs.z, c37.xyyz, r8
              cmp r8.xzw, -r6_abs.w, c38.xyyz, r8
              cmp r8.xzw, -r7_abs.x, c39.xyyz, r8
              cmp r8.xzw, -r7_abs.y, c40.xyyz, r8
              cmp r8.xzw, -r7_abs.z, c41.xyyz, r8
              cmp r8.xzw, -r7_abs.w, c42.xyyz, r8
              mad r3.xzw, r8, r5.w, r3
              cmp r8.xzw, -r6_abs.x, c27.xyyz, r8.y
              cmp r8.xzw, -r6_abs.y, c28.xyyz, r8
              cmp r8.xzw, -r6_abs.z, c29.xyyz, r8
              cmp r8.xzw, -r6_abs.w, c30.xyyz, r8
              cmp r8.xzw, -r7_abs.x, c31.xyyz, r8
              cmp r8.xzw, -r7_abs.y, c32.xyyz, r8
              cmp r8.xzw, -r7_abs.z, c33.xyyz, r8
              cmp r8.xzw, -r7_abs.w, c34.xyyz, r8
              cmp r9.xyz, -r6_abs.x, c51, r8.y
              cmp r9.xyz, -r6_abs.y, c52, r9
              cmp r6.xyz, -r6_abs.z, c53, r9
              cmp r6.xyz, -r6_abs.w, c54, r6
              cmp r6.xyz, -r7_abs.x, c55, r6
              cmp r6.xyz, -r7_abs.y, c56, r6
              cmp r6.xyz, -r7_abs.z, c57, r6
              cmp r6.xyz, -r7_abs.w, c58, r6
              mad r6.xyz, r1, r0.w, r6
              nrm r7.xyz, r6
              dp3_sat r4.w, r4, r7
              pow r6.x, r4.w, c109.x
              mul r6.xyz, r6.x, r8.xzww
              cmp r6.xyz, -c109.x, r8.y, r6
              mad r5.xyz, r6, r5.w, r5
            endif
          endif
        endif
        add r1.w, r1.w, -c116.y
      endrep
      mul r1.xyz, r3.xzww, c107
      mad r1.xyz, r2.yzww, c106, r1
      max r2.yzw, r1.xxyz, c120.y
      mov r1.xyz, c108
      mad r1.xyz, r5, r1, c110
      mad r1.xyz, r0, r2.yzww, r1
      mul r0.xyz, r1, c111.x
    endif
    mov r1.x, c6.x
    mad r0.xyz, r0, r1.x, c7
    mul oC0.w, r2.x, c112.x
    mad r0.w, v3.w, c114.y, c114.x
    mul r1.x, c115.x, v3.w
    mul r1.y, r1.x, c119.x
    exp r1.y, r1.y
    rcp r1.y, r1.y
    mul r1.x, r1.x, r1.x
    mul r1.x, r1.x, c119.x
    exp r1.x, r1.x
    rcp r1.x, r1.x
    cmp r1.x, -c10.x, r1.x, -r3.y
    cmp r1.x, -c9.x, r1.y, r1.x
    cmp_sat r0.w, -c8.x, r0.w, r1.x
    lrp oC0.xyz, r0.w, r0, c113

// approximately 264 instruction slots used (5 texture, 259 arithmetic)
