//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float GlobalDiffuseAlpha;
//   float3 LightDirection;
//   int gFogMode;
//   int gLightCount;
//   float gOverrideAlpha;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   LightDirection      c0       1
//   GlobalDiffuseAlpha  c1       1
//   gLightCount         c2       1
//   gOverrideColorRatio c3       1
//   gOverrideColor      c4       1
//   gOverrideAlpha      c5       1
//   gFogMode            c6       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c1   = { 1, 0, 0, 0 };
//
//   gLightCount
//     c2   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c3   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c4   = { 0, 0, 0, 0 };
//
//   gOverrideAlpha
//     c5   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c6   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c0.xyz, r0.w, r0.xyz
    add r0.x, c2.x, (-8)
    neg r0.y, c2.x
    cmp c1.x, r0.x, (-8), r0.y
    max r0.x, c3.x, (0)
    min r1.x, r0.x, (1)
    mul c4.xyz, r1.x, c4.xyz
    neg r0.x, r1.x
    add c3.x, r0.x, (1)
    mul c8.x, c1.x, c5.x
    add r0.x, c6.x, (-3)
    neg r1.x, r0.x
    max c5.x, r0.x, r1.x
    add r0.x, c6.x, (-1)
    neg r1.x, r0.x
    max c6.x, r0.x, r1.x
    add r0.x, c6.x, (-2)
    neg r1.x, r0.x
    max c7.x, r0.x, r1.x

// approximately 22 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float AmbientLightColor;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gCamPos;
//   float4 gDefaultAmbient;
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   float4 gLightSpecular[8];
//   int gLightType[8];
//   float4 gMaterialAmbient;
//   float4 gMaterialDiffuse;
//   float4 gMaterialEmissive;
//   float4 gMaterialSpecular;
//   float gMaterialSpecularPower;
//   float gModulate;
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   gUseMapLight           b0       1
//   gLightType             c9       8
//   gLightDiffuse          c17      8
//   gLightSpecular         c25      8
//   gLightAmbient          c33      8
//   gLightPos              c41      8
//   gLightDir              c49      8
//   gRange                 c57      8
//   gAttenuation0          c65      8
//   gAttenuation1          c73      8
//   gAttenuation2          c81      8
//   LightBrightness        c89      1
//   DiffuseBoost           c90      1
//   AmbientLightColor      c91      1
//   DiffuseMappingFactor   c92      1
//   HalfLambertPower       c93      1
//   HalfLambertBase        c94      1
//   gCamPos                c95      1
//   gDefaultAmbient        c96      1
//   gMaterialDiffuse       c97      1
//   gMaterialAmbient       c98      1
//   gMaterialSpecular      c99      1
//   gMaterialSpecularPower c100     1
//   gMaterialEmissive      c101     1
//   gModulate              c102     1
//   gFogColor              c103     1
//   gFogRange              c104     1
//   gFogDensity            c105     1
//   DiffuseMapSampler      s0       1
//
//
// Default values:
//
//   gUseMapLight
//     b0   = false;
//
//   gLightType
//     c9   = { 0, 0, 0, 0 };
//     c10  = { 0, 0, 0, 0 };
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//
//   gLightSpecular
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//
//   gRange
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//     c83  = { 0, 0, 0, 0 };
//     c84  = { 0, 0, 0, 0 };
//     c85  = { 0, 0, 0, 0 };
//     c86  = { 0, 0, 0, 0 };
//     c87  = { 0, 0, 0, 0 };
//     c88  = { 0, 0, 0, 0 };
//
//   LightBrightness
//     c89  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c90  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c91  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c93  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c94  = { 0.5, 0, 0, 0 };
//
//   gCamPos
//     c95  = { 0, 0, 0, 0 };
//
//   gDefaultAmbient
//     c96  = { 0, 0, 0, 0 };
//
//   gMaterialDiffuse
//     c97  = { 0, 0, 0, 0 };
//
//   gMaterialAmbient
//     c98  = { 0, 0, 0, 0 };
//
//   gMaterialSpecular
//     c99  = { 0, 0, 0, 0 };
//
//   gMaterialSpecularPower
//     c100 = { 0, 0, 0, 0 };
//
//   gMaterialEmissive
//     c101 = { 0, 0, 0, 0 };
//
//   gModulate
//     c102 = { 2, 0, 0, 0 };
//
//   gFogColor
//     c103 = { 0, 0, 0, 0 };
//
//   gFogRange
//     c104 = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c105 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c106, 0.5, 0, 0, 1
    def c107, -0, -1, -2, -3
    def c108, -4, -5, -6, -7
    def c109, 1.44269502, 0, 0, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord1 v0.xyz
    dcl_texcoord5 v1.xy
    dcl_texcoord6 v2
    dcl_2d s0
    texld r0, v1, s0
    dp3 r0.w, c0, v0
    mov r1.xzw, c106
    mad r0.w, r0.w, r1.x, c94.x
    pow r1.x, r0_abs.w, c93.x
    mul r0.w, r1.x, c89.x
    mul r2.xyz, r0, r0.w
    mul r0.xyz, r0, c90.x
    mul r0.xyz, r0, c92.x
    mad r0.xyz, r2, c92.x, r0
    add r0.xyz, r0, c91.x
    if b0
      nrm r2.xyz, v0
      add r3.xyz, c95, -v2
      dp3 r0.w, r3, r3
      rsq r0.w, r0.w
      mov r4.xyz, c106.z
      mov r5.xyz, c96
      mov r6.xyz, c106.z
      mov r1.x, c106.z
      rep i0
        add r1.y, r1.x, c1.x
        cmp r1.y, r1.y, c106.w, c106.z
        break_ne r1.y, -r1.y
        add r7, r1.x, c107
        add r8, r1.x, c108
        cmp r1.y, -r7_abs.x, c9.x, r1.z
        cmp r1.y, -r7_abs.y, c10.x, r1.y
        cmp r1.y, -r7_abs.z, c11.x, r1.y
        cmp r1.y, -r7_abs.w, c12.x, r1.y
        cmp r1.y, -r8_abs.x, c13.x, r1.y
        cmp r1.y, -r8_abs.y, c14.x, r1.y
        cmp r1.y, -r8_abs.z, c15.x, r1.y
        cmp r1.y, -r8_abs.w, c16.x, r1.y
        if_eq r1.y, -c107.w
          cmp r9.xyz, -r7_abs.x, c17, r1.z
          cmp r9.xyz, -r7_abs.y, c18, r9
          cmp r9.xyz, -r7_abs.z, c19, r9
          cmp r9.xyz, -r7_abs.w, c20, r9
          cmp r9.xyz, -r8_abs.x, c21, r9
          cmp r9.xyz, -r8_abs.y, c22, r9
          cmp r9.xyz, -r8_abs.z, c23, r9
          cmp r9.xyz, -r8_abs.w, c24, r9
          cmp r10.xyz, -r7_abs.x, c49, r1.z
          cmp r10.xyz, -r7_abs.y, c50, r10
          cmp r10.xyz, -r7_abs.z, c51, r10
          cmp r10.xyz, -r7_abs.w, c52, r10
          cmp r10.xyz, -r8_abs.x, c53, r10
          cmp r10.xyz, -r8_abs.y, c54, r10
          cmp r10.xyz, -r8_abs.z, c55, r10
          cmp r10.xyz, -r8_abs.w, c56, r10
          dp3_sat r2.w, r10, r2
          mad r4.xyz, r9, r2.w, r4
          cmp r9.xyz, -r7_abs.x, c33, r1.z
          cmp r9.xyz, -r7_abs.y, c34, r9
          cmp r9.xyz, -r7_abs.z, c35, r9
          cmp r9.xyz, -r7_abs.w, c36, r9
          cmp r9.xyz, -r8_abs.x, c37, r9
          cmp r9.xyz, -r8_abs.y, c38, r9
          cmp r9.xyz, -r8_abs.z, c39, r9
          cmp r9.xyz, -r8_abs.w, c40, r9
          add r5.xyz, r5, r9
          cmp r9.xyz, -r7_abs.x, c25, r1.z
          cmp r9.xyz, -r7_abs.y, c26, r9
          cmp r9.xyz, -r7_abs.z, c27, r9
          cmp r9.xyz, -r7_abs.w, c28, r9
          cmp r9.xyz, -r8_abs.x, c29, r9
          cmp r9.xyz, -r8_abs.y, c30, r9
          cmp r9.xyz, -r8_abs.z, c31, r9
          cmp r9.xyz, -r8_abs.w, c32, r9
          mad r10.xyz, r3, r0.w, r10
          nrm r11.xyz, r10
          dp3_sat r2.w, r2, r11
          pow r3.w, r2.w, c100.x
          mul r9.xyz, r3.w, r9
          cmp r9.xyz, -c100.x, r1.z, r9
          add r6.xyz, r6, r9
        else
          if_eq r1.y, c106.w
            cmp r9.xyz, -r7_abs.x, c41, r1.z
            cmp r9.xyz, -r7_abs.y, c42, r9
            cmp r9.xyz, -r7_abs.z, c43, r9
            cmp r9.xyz, -r7_abs.w, c44, r9
            cmp r9.xyz, -r8_abs.x, c45, r9
            cmp r9.xyz, -r8_abs.y, c46, r9
            cmp r9.xyz, -r8_abs.z, c47, r9
            cmp r9.xyz, -r8_abs.w, c48, r9
            add r9.xyz, r9, -v2
            dp3 r1.y, r9, r9
            rsq r1.y, r1.y
            rcp r2.w, r1.y
            cmp r3.w, -r7_abs.x, c57.x, r1.z
            cmp r3.w, -r7_abs.y, c58.x, r3.w
            cmp r3.w, -r7_abs.z, c59.x, r3.w
            cmp r3.w, -r7_abs.w, c60.x, r3.w
            cmp r3.w, -r8_abs.x, c61.x, r3.w
            cmp r3.w, -r8_abs.y, c62.x, r3.w
            cmp r3.w, -r8_abs.z, c63.x, r3.w
            cmp r3.w, -r8_abs.w, c64.x, r3.w
            if_lt r2.w, r3.w
              cmp r3.w, -r7_abs.x, c65.x, r1.z
              cmp r3.w, -r7_abs.y, c66.x, r3.w
              cmp r3.w, -r7_abs.z, c67.x, r3.w
              cmp r3.w, -r7_abs.w, c68.x, r3.w
              cmp r3.w, -r8_abs.x, c69.x, r3.w
              cmp r3.w, -r8_abs.y, c70.x, r3.w
              cmp r3.w, -r8_abs.z, c71.x, r3.w
              cmp r3.w, -r8_abs.w, c72.x, r3.w
              cmp r4.w, -r7_abs.x, c73.x, r1.z
              cmp r4.w, -r7_abs.y, c74.x, r4.w
              cmp r4.w, -r7_abs.z, c75.x, r4.w
              cmp r4.w, -r7_abs.w, c76.x, r4.w
              cmp r4.w, -r8_abs.x, c77.x, r4.w
              cmp r4.w, -r8_abs.y, c78.x, r4.w
              cmp r4.w, -r8_abs.z, c79.x, r4.w
              cmp r4.w, -r8_abs.w, c80.x, r4.w
              mad r3.w, r4.w, r2.w, r3.w
              cmp r4.w, -r7_abs.x, c81.x, r1.z
              cmp r4.w, -r7_abs.y, c82.x, r4.w
              cmp r4.w, -r7_abs.z, c83.x, r4.w
              cmp r4.w, -r7_abs.w, c84.x, r4.w
              cmp r4.w, -r8_abs.x, c85.x, r4.w
              cmp r4.w, -r8_abs.y, c86.x, r4.w
              cmp r4.w, -r8_abs.z, c87.x, r4.w
              cmp r4.w, -r8_abs.w, c88.x, r4.w
              mul r2.w, r2.w, r2.w
              mad r2.w, r2.w, r4.w, r3.w
              rcp r2.w, r2.w
              mul r9.xyz, r1.y, r9
              cmp r10.xyz, -r7_abs.x, c17, r1.z
              cmp r10.xyz, -r7_abs.y, c18, r10
              cmp r10.xyz, -r7_abs.z, c19, r10
              cmp r10.xyz, -r7_abs.w, c20, r10
              cmp r10.xyz, -r8_abs.x, c21, r10
              cmp r10.xyz, -r8_abs.y, c22, r10
              cmp r10.xyz, -r8_abs.z, c23, r10
              cmp r10.xyz, -r8_abs.w, c24, r10
              mul r10.xyz, r2.w, r10
              dp3_sat r1.y, r9, r2
              mad r4.xyz, r10, r1.y, r4
              cmp r9.xyz, -r7_abs.x, c33, r1.z
              cmp r9.xyz, -r7_abs.y, c34, r9
              cmp r9.xyz, -r7_abs.z, c35, r9
              cmp r9.xyz, -r7_abs.w, c36, r9
              cmp r9.xyz, -r8_abs.x, c37, r9
              cmp r9.xyz, -r8_abs.y, c38, r9
              cmp r9.xyz, -r8_abs.z, c39, r9
              cmp r9.xyz, -r8_abs.w, c40, r9
              mad r5.xyz, r9, r2.w, r5
              cmp r9.xyz, -r7_abs.x, c25, r1.z
              cmp r9.xyz, -r7_abs.y, c26, r9
              cmp r9.xyz, -r7_abs.z, c27, r9
              cmp r9.xyz, -r7_abs.w, c28, r9
              cmp r9.xyz, -r8_abs.x, c29, r9
              cmp r9.xyz, -r8_abs.y, c30, r9
              cmp r9.xyz, -r8_abs.z, c31, r9
              cmp r9.xyz, -r8_abs.w, c32, r9
              cmp r10.xyz, -r7_abs.x, c49, r1.z
              cmp r10.xyz, -r7_abs.y, c50, r10
              cmp r7.xyz, -r7_abs.z, c51, r10
              cmp r7.xyz, -r7_abs.w, c52, r7
              cmp r7.xyz, -r8_abs.x, c53, r7
              cmp r7.xyz, -r8_abs.y, c54, r7
              cmp r7.xyz, -r8_abs.z, c55, r7
              cmp r7.xyz, -r8_abs.w, c56, r7
              mad r7.xyz, r3, r0.w, r7
              nrm r8.xyz, r7
              dp3_sat r1.y, r2, r8
              pow r3.w, r1.y, c100.x
              mul r7.xyz, r3.w, r9
              cmp r7.xyz, -c100.x, r1.z, r7
              mad r6.xyz, r7, r2.w, r6
            endif
          endif
        endif
        add r1.x, r1.x, c106.w
      endrep
      mul r1.xyz, r5, c98
      mad r1.xyz, r4, c97, r1
      max r2.xyz, r1, c106.z
      mov r1.xyz, c99
      mad r1.xyz, r6, r1, c101
      mad r1.xyz, r0, r2, r1
      mul r0.xyz, r1, c102.x
    endif
    mov r1.x, c3.x
    mad r0.xyz, r0, r1.x, c4
    mad r0.w, v2.w, c104.y, c104.x
    mul r1.x, c105.x, v2.w
    mul r1.y, r1.x, c109.x
    exp r1.y, r1.y
    rcp r1.y, r1.y
    mul r1.x, r1.x, r1.x
    mul r1.x, r1.x, c109.x
    exp r1.x, r1.x
    rcp r1.x, r1.x
    cmp r1.x, -c7.x, r1.x, r1.w
    cmp r1.x, -c6.x, r1.y, r1.x
    cmp_sat r0.w, -c5.x, r0.w, r1.x
    lrp oC0.xyz, r0.w, r0, c103
    mov oC0.w, c8.x

// approximately 226 instruction slots used (1 texture, 225 arithmetic)
