//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 CameraPosition;
//   float4x4 ViewProjectionMatrix;
//   float4x4 WorldMatrix;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   WorldMatrix          c0       4
//   ViewProjectionMatrix c4       4
//   CameraPosition       c8       1
//
//
// Default values:
//
//   WorldMatrix
//     c0   = { 0, 0, 0, 0 };
//     c1   = { 0, 0, 0, 0 };
//     c2   = { 0, 0, 0, 0 };
//     c3   = { 0, 0, 0, 0 };
//
//   ViewProjectionMatrix
//     c4   = { 0, 0, 0, 0 };
//     c5   = { 0, 0, 0, 0 };
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 0, 0, 0, 0 };
//
//   CameraPosition
//     c8   = { 0, 0, 0, 0 };
//

    vs_3_0
    def c9, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_texcoord1 o2.xyz
    dcl_texcoord2 o3.xyz
    dcl_texcoord3 o4.xyz
    dcl_texcoord4 o5.xyz
    dcl_texcoord5 o6
    mad r0, v0.xyzx, c9.xxxy, c9.yyyx
    dp4 r1.x, r0, c0
    dp4 r1.y, r0, c1
    dp4 r1.z, r0, c2
    dp4 r1.w, r0, c3
    add r0.xyz, -r1, c8
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o3.xyz, r0.w, r0
    dp4 o0.x, r1, c4
    dp4 o0.y, r1, c5
    dp4 o0.z, r1, c6
    dp4 o0.w, r1, c7
    dp3 r0.x, v1, c0
    dp3 r0.y, v1, c1
    dp3 r0.z, v1, c2
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o2.xyz, r0.w, r0
    mov o1.xy, v2
    mov o4.xyz, c9.y
    mov o5.xyz, c9.y
    mov o6, c9.y

// approximately 23 instruction slots used
