//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float3 ColorLimit;
//   float ColorRate;
//   float EmissiveMapThreshold;
//   float GlobalDiffuseAlpha;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float Sprinker;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   ColorLimit              c1       1
//   theAccumTime            c2       1
//   GlobalDiffuseAlpha      c3       1
//   TexturePanningVelocityU c4       1
//   TexturePanningVelocityV c5       1
//   ColorRate               c6       1
//   Sprinker                c7       1
//   MapEnableState          c8       1
//   EmissiveMapThreshold    c9       1
//   NoiseMapUVFlowSpeed     c10      1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   ColorLimit
//     c1   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c2   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c3   = { 1, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c4   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c5   = { 0, 0, 0, 0 };
//
//   ColorRate
//     c6   = { 0, 0, 0, 0 };
//
//   Sprinker
//     c7   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c8   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c9   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c10  = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c8.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c2.x, c10.xy
    mul c2.x, c2.x, c7.x
    neg r0.x, c7.x
    max c3.x, r0.x, c7.x
    mul c6.x, c2.x, c4.x
    mul c6.y, c2.x, c5.x
    mul c7.x, c2.x, (0.55)
    neg r0.x, c5.x
    max r1.x, r0.x, c5.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c4.x
    max r1.y, r0.x, c4.x
    neg r0.x, r1.y
    cmp c8.x, r0.x, (-0), r1.x
    neg r0.x, c9.x
    add c9.x, r0.x, (1)
    neg r0.x, c6.x
    add r1.x, r0.x, (0.6)
    add r1.y, r0.x, (1)
    mul r0.xyz, r1.y, c0.xyz
    max r0.w, r1.x, (0)
    min r1.x, r0.w, (1)
    mul r0.w, r1.x, (-2)
    mul r2.x, r1.x, r1.x
    add r1.x, r0.w, (3)
    mul r0.w, r2.x, r1.x
    mul c13.x, r0.w, (5)
    neg r1.x, r0.x
    add r2.x, r1.x, c1.x
    cmp c14.x, r2.x, c1.x, r0.x
    neg r1.x, r0.y
    add r2.x, r1.x, c1.y
    cmp c14.y, r2.x, c1.y, r0.y
    neg r1.x, r0.z
    add r2.x, r1.x, c1.z
    cmp c14.z, r2.x, c1.z, r0.z
    mov c15.xyz, r0.xyz
    mul r1.x, r0.w, r0.w
    mul r2.x, r0.w, r1.x
    mul r0.x, r2.x, (3)
    neg r0.y, c3.x
    add r1.x, r0.y, r0.x
    cmp r2.x, r1.x, c3.x, r0.x
    add c16.x, r2.x, c3.x

// approximately 47 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   sampler2D DiffuseMapSampler;
//   float EffectAlpha;
//   float EmissiveMapIntensity;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   bool IsGradation;
//   bool IsScanner;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D OverlayMapSampler;
//   sampler2D OverlayMapSampler2;
//   float Sprinker;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   IsGradation          b1       1
//   HightLightColor      c17      1
//   GlobalDiffuseAlpha   c18      1
//   IsScanner            c19      1
//   TextureTileX         c20      1
//   TextureTileY         c21      1
//   Sprinker             c22      1
//   EffectAlpha          c23      1
//   HightLightPower      c24      1
//   MapEnableState       c25      1
//   EmissiveMapIntensity c26      1
//   DiffuseMapSampler    s0       1
//   AlphaMapSampler2     s1       1
//   OverlayMapSampler    s2       1
//   OverlayMapSampler2   s3       1
//   MaskMapSampler       s4       1
//   NoiseMapSampler      s5       1
//
//
// Default values:
//
//   IsGradation
//     b1   = false;
//
//   HightLightColor
//     c17  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c18  = { 1, 0, 0, 0 };
//
//   IsScanner
//     c19  = { 0, 0, 0, 0 };
//
//   TextureTileX
//     c20  = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c21  = { 1, 0, 0, 0 };
//
//   Sprinker
//     c22  = { 0, 0, 0, 0 };
//
//   EffectAlpha
//     c23  = { 0, 0, 0, 0 };
//
//   HightLightPower
//     c24  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c25  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c26  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c27, 1, 0.5, 0, 0.300000012
    def c28, 0.150000006, 0.212599993, 0.715200007, 0.0722000003
    def c29, 4, 0.00100000005, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    texld r0, v0, s0
    if b0
      texld r1, v0, s4
      mov r1.x, r1.y
    else
      mov r1.x, c27.x
    endif
    add r1.yz, c1.xxyw, v0.xxyw
    texld r2, r1.yzzw, s5
    mov r3.xz, c27
    cmp r1.y, -c25.y, r3.x, r2.x
    add r2.x, -c2.x, v0.x
    mov r2.y, v0.y
    texld r2, r2, s3
    mul r2, r2, c22.x
    mul r2, r2, c27.xxxy
    cmp r2, -c22.x, r3.z, r2
    mad r3, r0, c27.y, c27.w
    max r4, r3, c27.z
    min r3, r4, c28.x
    add r3, r2, r3
    cmp r2, -c19.x, r2, r3
    mul r3.x, c20.x, v0.x
    mul r3.y, c21.x, v0.y
    add r1.zw, r3.xyxy, c6.xyxy
    add r3.xy, r3, c7.x
    cmp r1.zw, c8.x, r3.xyxy, r1
    texld r3, r1.zwzw, s2
    mad r3, r3, c23.x, r2
    cmp r2, -c3.x, r3, r2
    dp3 r1.z, r0, c28.yzww
    add r1.z, r1.z, -c9.x
    mul r1.x, r1.y, r1.x
    mul r1.x, r1.x, c26.x
    mul r1.xyw, r0.xyzz, r1.x
    cmp r1.xyz, r1.z, r1.xyww, c27.z
    mov r1.w, c27.x
    if b1
      texld r3, v0, s1
      mul r4.w, r3.y, c24.x
      mul r4.xyz, r4.w, c17
      cmp r4, -r3.y, c27.z, r4
      mul r5, r2, r3.z
      mul r3.x, r5.w, c29.x
      max r5.w, r3.z, c29.y
      mov r6.x, c29.x
      mad r6.xyz, r5, r6.x, c14
      mad r6.w, c13.x, r5.w, r3.x
      add r3, r4, r6
      mul oC0.w, r3.w, c18.x
      mov oC0.xyz, r3
      mov oC1, r1
    else
      add r0.xyz, r0, c15
      add oC0.xyz, r2, r0
      add r0.x, r2.w, c16.x
      mul oC0.w, r0.w, r0.x
      mov oC1, r1
    endif

// approximately 63 instruction slots used (6 texture, 57 arithmetic)
