//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   theAccumTime            c0       1
//   TexturePanningVelocityU c1       1
//   TexturePanningVelocityV c2       1
//
//
// Default values:
//
//   theAccumTime
//     c0   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c1   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c2   = { 0, 0, 0, 0 };
//

    preshader
    mul c12.x, c0.x, c1.x
    mul c12.y, c0.x, c2.x

// approximately 2 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 CameraPosition;
//   float4x4 ViewMatrix;
//   float4x4 ViewProjectionMatrix;
//   float4x4 WorldMatrix;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   WorldMatrix          c0       4
//   ViewProjectionMatrix c4       4
//   ViewMatrix           c8       3
//   CameraPosition       c11      1
//
//
// Default values:
//
//   WorldMatrix
//     c0   = { 0, 0, 0, 0 };
//     c1   = { 0, 0, 0, 0 };
//     c2   = { 0, 0, 0, 0 };
//     c3   = { 0, 0, 0, 0 };
//
//   ViewProjectionMatrix
//     c4   = { 0, 0, 0, 0 };
//     c5   = { 0, 0, 0, 0 };
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 0, 0, 0, 0 };
//
//   ViewMatrix
//     c8   = { 0, 0, 0, 0 };
//     c9   = { 0, 0, 0, 0 };
//     c10  = { 0, 0, 0, 0 };
//
//   CameraPosition
//     c11  = { 0, 0, 0, 0 };
//

    vs_3_0
    def c13, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dcl_texcoord1 v3
    dcl_texcoord2 v4
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_texcoord1 o2.xyz
    dcl_texcoord2 o3.xyz
    dcl_texcoord3 o4.xyz
    dcl_texcoord4 o5.xyz
    dcl_texcoord5 o6.xy
    dcl_texcoord6 o7
    mad r0, v0.xyzx, c13.xxxy, c13.yyyx
    dp4 r1.x, r0, c0
    dp4 r1.y, r0, c1
    dp4 r1.z, r0, c2
    dp4 r1.w, r0, c3
    add r0.xyz, -r1, c11
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o3.xyz, r0.w, r0
    dp4 o0.x, r1, c4
    dp4 o0.y, r1, c5
    dp4 o0.z, r1, c6
    dp4 o0.w, r1, c7
    add o6.xy, c12, v2
    dp3 r0.x, v1, c0
    dp3 r0.y, v1, c1
    dp3 r0.z, v1, c2
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o2.xyz, r0.w, r0
    dp3 r0.x, v3, c0
    dp3 r0.y, v3, c1
    dp3 r0.z, v3, c2
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o4.xyz, r0.w, r0
    dp3 r0.x, v4, c0
    dp3 r0.y, v4, c1
    dp3 r0.z, v4, c2
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    mul o5.xyz, r0.w, r0
    dp4 r0.x, r1, c8
    dp4 r0.y, r1, c9
    dp4 r0.z, r1, c10
    mov o7.xyz, r1
    dp3 r0.x, r0, r0
    rsq r0.x, r0.x
    rcp o7.w, r0.x
    mov o1.xy, v2

// approximately 40 instruction slots used
