//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float GlobalDiffuseAlpha;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float RefractionIndex;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float gOverrideAlpha;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   LightDirection      c0       1
//   GlobalDiffuseAlpha  c1       1
//   SpecularPower       c2       1
//   RefractionIndex     c3       1
//   MapEnableState      c4       1
//   gLightCount         c5       1
//   gOverrideColorRatio c6       1
//   gOverrideColor      c7       1
//   gOverrideAlpha      c8       1
//   gFogMode            c9       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c1   = { 1, 0, 0, 0 };
//
//   SpecularPower
//     c2   = { 8, 0, 0, 0 };
//
//   RefractionIndex
//     c3   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c4   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c5   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c6   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c7   = { 0, 0, 0, 0 };
//
//   gOverrideAlpha
//     c8   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c9   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c2.xyz, r0.w, r0.xyz
    add r0.x, c5.x, (-8)
    neg r0.y, c5.x
    cmp c0.x, r0.x, (-8), r0.y
    neg r0.x, c4.x
    cmp ob1.x, r0.x, (0), (1)
    mul c3.x, c2.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c4.xyz, r1.x, c0.xyz
    mul c5.x, c3.x, c3.x
    max r0.x, c6.x, (0)
    min r1.x, r0.x, (1)
    mul c8.xyz, r1.x, c7.xyz
    neg r0.x, r1.x
    add c7.x, r0.x, (1)
    mul c12.x, c1.x, c8.x
    add r0.x, c9.x, (-3)
    neg r1.x, r0.x
    max c9.x, r0.x, r1.x
    add r0.x, c9.x, (-1)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x
    add r0.x, c9.x, (-2)
    neg r1.x, r0.x
    max c11.x, r0.x, r1.x

// approximately 29 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   sampler2D MaskMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float ReflectionIndex;
//   float RefractionIndex;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b0       1
//   gLightType            c13      8
//   gLightDiffuse         c21      8
//   gLightAmbient         c29      8
//   gLightPos             c37      8
//   gLightDir             c45      8
//   gRange                c53      8
//   gAttenuation0         c61      8
//   gAttenuation1         c69      8
//   gAttenuation2         c77      8
//   SpecularBacklighting  c85      1
//   EnvCubeMapBrightness  c86      1
//   LightBrightness       c87      1
//   DiffuseBoost          c88      1
//   AmbientLightColor     c89      1
//   DiffuseMappingFactor  c90      1
//   NormalMappingFactor   c91      1
//   SpecularMappingFactor c92      1
//   EnvCubeMappingFactor  c93      1
//   HalfLambertPower      c94      1
//   HalfLambertBase       c95      1
//   ReflectionIndex       c96      1
//   RefractionIndex       c97      1
//   SpecularLength        c98      1
//   SpecularHighlight     c99      1
//   gFogColor             c100     1
//   gFogRange             c101     1
//   gFogDensity           c102     1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   MaskMapSampler        s4       1
//
//
// Default values:
//
//   gUseMapLight
//     b0   = false;
//
//   gLightType
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//
//   gRange
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//     c83  = { 0, 0, 0, 0 };
//     c84  = { 0, 0, 0, 0 };
//
//   SpecularBacklighting
//     c85  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c86  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c87  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c88  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c89  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c90  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c91  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c93  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c94  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c95  = { 0.5, 0, 0, 0 };
//
//   ReflectionIndex
//     c96  = { 0, 0, 0, 0 };
//
//   RefractionIndex
//     c97  = { 0, 0, 0, 0 };
//
//   SpecularLength
//     c98  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c99  = { 1, 0, 0, 0 };
//
//   gFogColor
//     c100 = { 0, 0, 0, 0 };
//
//   gFogRange
//     c101 = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c102 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c103, -4, -5, -6, -7
    def c104, 0.5, 1.44269502, 0, 0
    def c105, -0, -1, -2, -3
    def c106, 2, -1, 0, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c106.x, c106.y
    mul r1.yzw, r1.y, v4.xxyz
    mad r1.xyz, v3, r1.x, r1.yzww
    mad r1.xyz, r1, c91.x, v1
    nrm r2.xyz, r1
    if b0
      mov r1.xyz, c106.w
      mov r3.xyz, c106.w
      mov r0.w, c106.w
      rep i0
        add r1.w, r0.w, c0.x
        cmp r1.w, r1.w, c106_abs.y, c106_abs.w
        break_ne r1.w, -r1.w
        add r4, r0.w, c105
        add r5, r0.w, c103
        mov r1.w, c106.w
        cmp r2.w, -r4_abs.x, c13.x, r1.w
        cmp r2.w, -r4_abs.y, c14.x, r2.w
        cmp r2.w, -r4_abs.z, c15.x, r2.w
        cmp r2.w, -r4_abs.w, c16.x, r2.w
        cmp r2.w, -r5_abs.x, c17.x, r2.w
        cmp r2.w, -r5_abs.y, c18.x, r2.w
        cmp r2.w, -r5_abs.z, c19.x, r2.w
        cmp r2.w, -r5_abs.w, c20.x, r2.w
        if_eq r2.w, -c105.w
          cmp r6.xyz, -r4_abs.x, c45, r1.w
          cmp r6.xyz, -r4_abs.y, c46, r6
          cmp r6.xyz, -r4_abs.z, c47, r6
          cmp r6.xyz, -r4_abs.w, c48, r6
          cmp r6.xyz, -r5_abs.x, c49, r6
          cmp r6.xyz, -r5_abs.y, c50, r6
          cmp r6.xyz, -r5_abs.z, c51, r6
          cmp r6.xyz, -r5_abs.w, c52, r6
          dp3 r3.w, r6, r2
          mov r6.x, c104.x
          mad r3.w, r3.w, r6.x, c95.x
          pow r6.x, r3_abs.w, c94.x
          mul r3.w, r6.x, c87.x
          cmp r6.xyz, -r4_abs.x, c21, r1.w
          cmp r6.xyz, -r4_abs.y, c22, r6
          cmp r6.xyz, -r4_abs.z, c23, r6
          cmp r6.xyz, -r4_abs.w, c24, r6
          cmp r6.xyz, -r5_abs.x, c25, r6
          cmp r6.xyz, -r5_abs.y, c26, r6
          cmp r6.xyz, -r5_abs.z, c27, r6
          cmp r6.xyz, -r5_abs.w, c28, r6
          mad r1.xyz, r3.w, r6, r1
          cmp r6.xyz, -r4_abs.x, c29, r1.w
          cmp r6.xyz, -r4_abs.y, c30, r6
          cmp r6.xyz, -r4_abs.z, c31, r6
          cmp r6.xyz, -r4_abs.w, c32, r6
          cmp r6.xyz, -r5_abs.x, c33, r6
          cmp r6.xyz, -r5_abs.y, c34, r6
          cmp r6.xyz, -r5_abs.z, c35, r6
          cmp r6.xyz, -r5_abs.w, c36, r6
          add r3.xyz, r3, r6
        else
          add r2.w, r2.w, c106.y
          cmp r6.xyz, -r4_abs.x, c37, r1.w
          cmp r6.xyz, -r4_abs.y, c38, r6
          cmp r6.xyz, -r4_abs.z, c39, r6
          cmp r6.xyz, -r4_abs.w, c40, r6
          cmp r6.xyz, -r5_abs.x, c41, r6
          cmp r6.xyz, -r5_abs.y, c42, r6
          cmp r6.xyz, -r5_abs.z, c43, r6
          cmp r6.xyz, -r5_abs.w, c44, r6
          add r6.xyz, r6, -v5
          dp3 r3.w, r6, r6
          rsq r3.w, r3.w
          rcp r6.w, r3.w
          cmp r7.x, -r4_abs.x, c53.x, r1.w
          cmp r7.x, -r4_abs.y, c54.x, r7.x
          cmp r7.x, -r4_abs.z, c55.x, r7.x
          cmp r7.x, -r4_abs.w, c56.x, r7.x
          cmp r7.x, -r5_abs.x, c57.x, r7.x
          cmp r7.x, -r5_abs.y, c58.x, r7.x
          cmp r7.x, -r5_abs.z, c59.x, r7.x
          cmp r7.x, -r5_abs.w, c60.x, r7.x
          add r7.x, r6.w, -r7.x
          cmp r7.y, -r4_abs.x, c61.x, r1.w
          cmp r7.y, -r4_abs.y, c62.x, r7.y
          cmp r7.y, -r4_abs.z, c63.x, r7.y
          cmp r7.y, -r4_abs.w, c64.x, r7.y
          cmp r7.y, -r5_abs.x, c65.x, r7.y
          cmp r7.y, -r5_abs.y, c66.x, r7.y
          cmp r7.y, -r5_abs.z, c67.x, r7.y
          cmp r7.y, -r5_abs.w, c68.x, r7.y
          cmp r7.z, -r4_abs.x, c69.x, r1.w
          cmp r7.z, -r4_abs.y, c70.x, r7.z
          cmp r7.z, -r4_abs.z, c71.x, r7.z
          cmp r7.z, -r4_abs.w, c72.x, r7.z
          cmp r7.z, -r5_abs.x, c73.x, r7.z
          cmp r7.z, -r5_abs.y, c74.x, r7.z
          cmp r7.z, -r5_abs.z, c75.x, r7.z
          cmp r7.z, -r5_abs.w, c76.x, r7.z
          mad r7.y, r7.z, r6.w, r7.y
          cmp r7.z, -r4_abs.x, c77.x, r1.w
          cmp r7.z, -r4_abs.y, c78.x, r7.z
          cmp r7.z, -r4_abs.z, c79.x, r7.z
          cmp r7.z, -r4_abs.w, c80.x, r7.z
          cmp r7.z, -r5_abs.x, c81.x, r7.z
          cmp r7.z, -r5_abs.y, c82.x, r7.z
          cmp r7.z, -r5_abs.z, c83.x, r7.z
          cmp r7.z, -r5_abs.w, c84.x, r7.z
          mul r6.w, r6.w, r6.w
          mad r6.w, r6.w, r7.z, r7.y
          rcp r6.w, r6.w
          mul r6.xyz, r3.w, r6
          cmp r7.yzw, -r4_abs.x, c21.xxyz, r1.w
          cmp r7.yzw, -r4_abs.y, c22.xxyz, r7
          cmp r7.yzw, -r4_abs.z, c23.xxyz, r7
          cmp r7.yzw, -r4_abs.w, c24.xxyz, r7
          cmp r7.yzw, -r5_abs.x, c25.xxyz, r7
          cmp r7.yzw, -r5_abs.y, c26.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c27.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c28.xxyz, r7
          mul r7.yzw, r6.w, r7
          dp3_sat r3.w, r6, r2
          mad r6.xyz, r7.yzww, r3.w, r1
          cmp r7.yzw, -r4_abs.x, c29.xxyz, r1.w
          cmp r7.yzw, -r4_abs.y, c30.xxyz, r7
          cmp r4.xyz, -r4_abs.z, c31, r7.yzww
          cmp r4.xyz, -r4_abs.w, c32, r4
          cmp r4.xyz, -r5_abs.x, c33, r4
          cmp r4.xyz, -r5_abs.y, c34, r4
          cmp r4.xyz, -r5_abs.z, c35, r4
          cmp r4.xyz, -r5_abs.w, c36, r4
          mad r4.xyz, r4, r6.w, r3
          cmp r5.xyz, r7.x, r1, r6
          cmp r4.xyz, r7.x, r3, r4
          cmp r1.xyz, -r2_abs.w, r5, r1
          cmp r3.xyz, -r2_abs.w, r4, r3
        endif
        add r0.w, r0.w, -c106.y
      endrep
      if b1
        texld r4, v0, s4
        cmp r1.xyz, -r1_abs.x, r4.x, r1
      endif
    else
      dp3 r0.w, c2, r2
      mov r4.x, c104.x
      mad r0.w, r0.w, r4.x, c95.x
      pow r1.w, r0_abs.w, c94.x
      mul r1.xyz, r1.w, c87.x
      mov r3.xyz, c89.x
    endif
    mul r0.xyz, r0, c90.x
    add r4.xyz, r1, c88.x
    mad r0.xyz, r0, r4, r3
    add r0.w, r1.y, r1.x
    add r0.w, r1.z, r0.w
    dp3 r1.x, r2, c2
    mul r1.x, r1.x, -c103.x
    mad r1.xyz, r1.x, r2, -c2
    dp3 r1.x, r1, v2
    add r1.x, r1.x, -c98.x
    mov_sat r1.y, r1.x
    cmp r1.x, -c85.x, r1.y, r1.x
    mul r1.x, r1.x, c99.x
    pow r2.w, r1_abs.x, c3.x
    texld r1, v0, s1
    mul r1.xyz, r2.w, r1
    dp3 r1.w, c4, r2
    add r2.w, r1.w, r1.w
    mad r3.xyz, r2, -r2.w, c4
    mad r2.w, r1.w, -r1.w, -c106.y
    mov r4.y, c106.y
    mad r2.w, c5.x, -r2.w, -r4.y
    cmp r3.w, r2.w, c106_abs.y, c106_abs.w
    mul r2.w, r2.w, r3.w
    mul r3.w, r3.w, c97.x
    rsq r2.w, r2.w
    rcp r2.w, r2.w
    mad r1.w, r3.w, r1.w, r2.w
    mul r2.xyz, r2, r1.w
    mad r2.xyz, r3.w, c4, -r2
    mul r2.xyz, r2, c97.x
    mad r2.xyz, c96.x, r3, r2
    texld r2, r2, s2
    mul r2.xyz, r2, c86.x
    mul r2.xyz, r2, c93.x
    mad r1.xyz, r1, c92.x, r2
    add r1.xyz, r0, r1
    cmp r0.xyz, -r0.w, r0, r1
    mov r1.x, c7.x
    mad r0.xyz, r0, r1.x, c8
    mad r0.w, v5.w, c101.y, c101.x
    mul r1.x, c102.x, v5.w
    mul r1.y, r1.x, c104.y
    exp r1.y, r1.y
    rcp r1.y, r1.y
    mul r1.x, r1.x, r1.x
    mul r1.x, r1.x, c104.y
    exp r1.x, r1.x
    rcp r1.x, r1.x
    cmp r1.x, -c11.x, r1.x, -r4.y
    cmp r1.x, -c10.x, r1.y, r1.x
    cmp_sat r0.w, -c9.x, r0.w, r1.x
    lrp oC0.xyz, r0.w, r0, c100
    mov oC0.w, c12.x

// approximately 222 instruction slots used (5 texture, 217 arithmetic)
