//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float EmissiveMapThreshold;
//   float GlobalDiffuseAlpha;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float gOverrideAlpha;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   LightDirection       c0       1
//   theAccumTime         c1       1
//   GlobalDiffuseAlpha   c2       1
//   SpecularPower        c3       1
//   MapEnableState       c4       1
//   EmissiveMapThreshold c5       1
//   NoiseMapUVFlowSpeed  c6       1
//   gLightCount          c7       1
//   gOverrideColorRatio  c8       1
//   gOverrideColor       c9       1
//   gOverrideAlpha       c10      1
//   gFogMode             c11      1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c1   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c2   = { 1, 0, 0, 0 };
//
//   SpecularPower
//     c3   = { 8, 0, 0, 0 };
//
//   MapEnableState
//     c4   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c5   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c6   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c7   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c8   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c9   = { 0, 0, 0, 0 };
//
//   gOverrideAlpha
//     c10  = { 0, 0, 0, 0 };
//
//   gFogMode
//     c11  = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c4.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c1.x, c6.xy
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c3.xyz, r0.w, r0.xyz
    add r0.x, c7.x, (-8)
    neg r0.y, c7.x
    cmp c2.x, r0.x, (-8), r0.y
    mul c4.x, c3.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c5.xyz, r1.x, c0.xyz
    max r0.x, c8.x, (0)
    min r1.x, r0.x, (1)
    mul c8.xyz, r1.x, c9.xyz
    neg r0.x, r1.x
    add c7.x, r0.x, (1)
    mul c13.x, c2.x, c10.x
    add r0.x, c11.x, (-3)
    neg r1.x, r0.x
    max c9.x, r0.x, r1.x
    add r0.x, c11.x, (-1)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x
    add r0.x, c11.x, (-2)
    neg r1.x, r0.x
    max c11.x, r0.x, r1.x
    neg r0.x, c5.x
    add c12.x, r0.x, (1)

// approximately 31 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EmissiveMapIntensity;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b1       1
//   gLightType            c14      8
//   gLightDiffuse         c22      8
//   gLightAmbient         c30      8
//   gLightPos             c38      8
//   gLightDir             c46      8
//   gRange                c54      8
//   gAttenuation0         c62      8
//   gAttenuation1         c70      8
//   gAttenuation2         c78      8
//   SpecularBacklighting  c86      1
//   EnvCubeMapBrightness  c87      1
//   LightBrightness       c88      1
//   DiffuseBoost          c89      1
//   AmbientLightColor     c90      1
//   DiffuseMappingFactor  c91      1
//   NormalMappingFactor   c92      1
//   SpecularMappingFactor c93      1
//   EnvCubeMappingFactor  c94      1
//   HalfLambertPower      c95      1
//   HalfLambertBase       c96      1
//   SpecularLength        c97      1
//   SpecularHighlight     c98      1
//   MapEnableState        c99      1
//   EmissiveMapIntensity  c100     1
//   gFogColor             c101     1
//   gFogRange             c102     1
//   gFogDensity           c103     1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   MaskMapSampler        s4       1
//   NoiseMapSampler       s5       1
//
//
// Default values:
//
//   gUseMapLight
//     b1   = false;
//
//   gLightType
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//
//   gRange
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//     c83  = { 0, 0, 0, 0 };
//     c84  = { 0, 0, 0, 0 };
//     c85  = { 0, 0, 0, 0 };
//
//   SpecularBacklighting
//     c86  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c87  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c88  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c89  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c90  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c91  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c93  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c94  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c95  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c96  = { 0.5, 0, 0, 0 };
//
//   SpecularLength
//     c97  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c98  = { 1, 0, 0, 0 };
//
//   MapEnableState
//     c99  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c100 = { 0, 0, 0, 0 };
//
//   gFogColor
//     c101 = { 0, 0, 0, 0 };
//
//   gFogRange
//     c102 = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c103 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c104, 0, 1, 2, 3
    def c105, 0.5, 1.44269502, 0, 0
    def c106, 2, -1, 1, 0
    def c107, -4, -5, -6, -7
    def c108, 0.212599993, 0.715200007, 0.0722000003, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c106.x, c106.y
    if b0
      texld r2, v0, s4
      mov r0.w, r2.y
    else
      mov r2.x, c106.z
      mov r0.w, c106.z
    endif
    add r1.zw, c1.xyxy, v0.xyxy
    texld r3, r1.zwzw, s5
    mov r1.z, c106.z
    cmp r1.w, -c99.y, r1.z, r3.x
    mul r2.yzw, r1.y, v4.xxyz
    mad r2.yzw, v3.xxyz, r1.x, r2
    mad r2.yzw, r2, c92.x, v1.xxyz
    nrm r3.xyz, r2.yzww
    if b1
      mov r2.yzw, c104.x
      mov r4.xyz, c104.x
      mov r1.x, c104.x
      rep i0
        add r1.y, r1.x, c2.x
        cmp r1.y, r1.y, c104.y, c104.x
        break_ne r1.y, -r1.y
        add r5, r1.x, -c104
        add r6, r1.x, c107
        mov r7.x, c104.x
        cmp r1.y, -r5_abs.x, c14.x, r7.x
        cmp r1.y, -r5_abs.y, c15.x, r1.y
        cmp r1.y, -r5_abs.z, c16.x, r1.y
        cmp r1.y, -r5_abs.w, c17.x, r1.y
        cmp r1.y, -r6_abs.x, c18.x, r1.y
        cmp r1.y, -r6_abs.y, c19.x, r1.y
        cmp r1.y, -r6_abs.z, c20.x, r1.y
        cmp r1.y, -r6_abs.w, c21.x, r1.y
        if_eq r1.y, c104.w
          cmp r7.yzw, -r5_abs.x, c46.xxyz, r7.x
          cmp r7.yzw, -r5_abs.y, c47.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c48.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c49.xxyz, r7
          cmp r7.yzw, -r6_abs.x, c50.xxyz, r7
          cmp r7.yzw, -r6_abs.y, c51.xxyz, r7
          cmp r7.yzw, -r6_abs.z, c52.xxyz, r7
          cmp r7.yzw, -r6_abs.w, c53.xxyz, r7
          dp3 r3.w, r7.yzww, r3
          mov r8.x, c105.x
          mad r3.w, r3.w, r8.x, c96.x
          pow r4.w, r3_abs.w, c95.x
          mul r3.w, r4.w, c88.x
          cmp r7.yzw, -r5_abs.x, c22.xxyz, r7.x
          cmp r7.yzw, -r5_abs.y, c23.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c24.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c25.xxyz, r7
          cmp r7.yzw, -r6_abs.x, c26.xxyz, r7
          cmp r7.yzw, -r6_abs.y, c27.xxyz, r7
          cmp r7.yzw, -r6_abs.z, c28.xxyz, r7
          cmp r7.yzw, -r6_abs.w, c29.xxyz, r7
          mad r2.yzw, r3.w, r7, r2
          cmp r7.yzw, -r5_abs.x, c30.xxyz, r7.x
          cmp r7.yzw, -r5_abs.y, c31.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c32.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c33.xxyz, r7
          cmp r7.yzw, -r6_abs.x, c34.xxyz, r7
          cmp r7.yzw, -r6_abs.y, c35.xxyz, r7
          cmp r7.yzw, -r6_abs.z, c36.xxyz, r7
          cmp r7.yzw, -r6_abs.w, c37.xxyz, r7
          add r4.xyz, r4, r7.yzww
        else
          add r1.y, r1.y, c106.y
          cmp r7.yzw, -r5_abs.x, c38.xxyz, r7.x
          cmp r7.yzw, -r5_abs.y, c39.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c40.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c41.xxyz, r7
          cmp r7.yzw, -r6_abs.x, c42.xxyz, r7
          cmp r7.yzw, -r6_abs.y, c43.xxyz, r7
          cmp r7.yzw, -r6_abs.z, c44.xxyz, r7
          cmp r7.yzw, -r6_abs.w, c45.xxyz, r7
          add r7.yzw, r7, -v5.xxyz
          dp3 r3.w, r7.yzww, r7.yzww
          rsq r3.w, r3.w
          rcp r4.w, r3.w
          cmp r8.x, -r5_abs.x, c54.x, r7.x
          cmp r8.x, -r5_abs.y, c55.x, r8.x
          cmp r8.x, -r5_abs.z, c56.x, r8.x
          cmp r8.x, -r5_abs.w, c57.x, r8.x
          cmp r8.x, -r6_abs.x, c58.x, r8.x
          cmp r8.x, -r6_abs.y, c59.x, r8.x
          cmp r8.x, -r6_abs.z, c60.x, r8.x
          cmp r8.x, -r6_abs.w, c61.x, r8.x
          add r8.x, r4.w, -r8.x
          cmp r8.y, -r5_abs.x, c62.x, r7.x
          cmp r8.y, -r5_abs.y, c63.x, r8.y
          cmp r8.y, -r5_abs.z, c64.x, r8.y
          cmp r8.y, -r5_abs.w, c65.x, r8.y
          cmp r8.y, -r6_abs.x, c66.x, r8.y
          cmp r8.y, -r6_abs.y, c67.x, r8.y
          cmp r8.y, -r6_abs.z, c68.x, r8.y
          cmp r8.y, -r6_abs.w, c69.x, r8.y
          cmp r8.z, -r5_abs.x, c70.x, r7.x
          cmp r8.z, -r5_abs.y, c71.x, r8.z
          cmp r8.z, -r5_abs.z, c72.x, r8.z
          cmp r8.z, -r5_abs.w, c73.x, r8.z
          cmp r8.z, -r6_abs.x, c74.x, r8.z
          cmp r8.z, -r6_abs.y, c75.x, r8.z
          cmp r8.z, -r6_abs.z, c76.x, r8.z
          cmp r8.z, -r6_abs.w, c77.x, r8.z
          mad r8.y, r8.z, r4.w, r8.y
          cmp r8.z, -r5_abs.x, c78.x, r7.x
          cmp r8.z, -r5_abs.y, c79.x, r8.z
          cmp r8.z, -r5_abs.z, c80.x, r8.z
          cmp r8.z, -r5_abs.w, c81.x, r8.z
          cmp r8.z, -r6_abs.x, c82.x, r8.z
          cmp r8.z, -r6_abs.y, c83.x, r8.z
          cmp r8.z, -r6_abs.z, c84.x, r8.z
          cmp r8.z, -r6_abs.w, c85.x, r8.z
          mul r4.w, r4.w, r4.w
          mad r4.w, r4.w, r8.z, r8.y
          rcp r4.w, r4.w
          mul r7.yzw, r3.w, r7
          cmp r8.yzw, -r5_abs.x, c22.xxyz, r7.x
          cmp r8.yzw, -r5_abs.y, c23.xxyz, r8
          cmp r8.yzw, -r5_abs.z, c24.xxyz, r8
          cmp r8.yzw, -r5_abs.w, c25.xxyz, r8
          cmp r8.yzw, -r6_abs.x, c26.xxyz, r8
          cmp r8.yzw, -r6_abs.y, c27.xxyz, r8
          cmp r8.yzw, -r6_abs.z, c28.xxyz, r8
          cmp r8.yzw, -r6_abs.w, c29.xxyz, r8
          mul r8.yzw, r4.w, r8
          dp3_sat r3.w, r7.yzww, r3
          mad r7.yzw, r8, r3.w, r2
          cmp r8.yzw, -r5_abs.x, c30.xxyz, r7.x
          cmp r8.yzw, -r5_abs.y, c31.xxyz, r8
          cmp r5.xyz, -r5_abs.z, c32, r8.yzww
          cmp r5.xyz, -r5_abs.w, c33, r5
          cmp r5.xyz, -r6_abs.x, c34, r5
          cmp r5.xyz, -r6_abs.y, c35, r5
          cmp r5.xyz, -r6_abs.z, c36, r5
          cmp r5.xyz, -r6_abs.w, c37, r5
          mad r5.xyz, r5, r4.w, r4
          cmp r6.xyz, r8.x, r2.yzww, r7.yzww
          cmp r5.xyz, r8.x, r4, r5
          cmp r2.yzw, -r1_abs.y, r6.xxyz, r2
          cmp r4.xyz, -r1_abs.y, r5, r4
        endif
        add r1.x, r1.x, c106.z
      endrep
      cmp r5.xyz, -r2_abs.y, r2.x, r2.yzww
      cmp r2.xyz, -c99.x, r2.yzww, r5
    else
      dp3 r1.x, c3, r3
      mov r5.x, c105.x
      mad r1.x, r1.x, r5.x, c96.x
      pow r2.w, r1_abs.x, c95.x
      mul r2.xyz, r2.w, c88.x
      mov r4.xyz, c90.x
    endif
    mul r5.xyz, r0, c91.x
    add r6.xyz, r2, c89.x
    mad r4.xyz, r5, r6, r4
    add r1.x, r2.y, r2.x
    add r1.x, r2.z, r1.x
    dp3 r1.y, r3, c3
    mul r1.y, r1.y, -c107.x
    mad r2.xyz, r1.y, r3, -c3
    dp3 r1.y, r2, v2
    add r1.y, r1.y, -c97.x
    mov_sat r2.x, r1.y
    cmp r1.y, -c86.x, r2.x, r1.y
    mul r1.y, r1.y, c98.x
    pow r2.x, r1_abs.y, c4.x
    texld r5, v0, s1
    mul r2.xyz, r2.x, r5
    dp3 r1.y, c5, r3
    add r1.y, r1.y, r1.y
    mad r3.xyz, r3, -r1.y, c5
    texld r3, r3, s2
    mul r3.xyz, r3, c87.x
    mul r3.xyz, r3, c94.x
    mad r2.xyz, r2, c93.x, r3
    add r2.xyz, r2, r4
    cmp r2.xyz, -r1.x, r4, r2
    mov r1.x, c7.x
    mad r2.xyz, r2, r1.x, c8
    mad r1.x, v5.w, c102.y, c102.x
    mul r1.y, c103.x, v5.w
    mul r2.w, r1.y, c105.y
    exp r2.w, r2.w
    rcp r2.w, r2.w
    mul r1.y, r1.y, r1.y
    mul r1.y, r1.y, c105.y
    exp r1.y, r1.y
    rcp r1.y, r1.y
    cmp r1.y, -c11.x, r1.y, r1.z
    cmp r1.y, -c10.x, r2.w, r1.y
    cmp_sat r1.x, -c9.x, r1.x, r1.y
    lrp oC0.xyz, r1.x, r2, c101
    dp3 r1.x, r0, c108
    add r1.x, r1.x, -c12.x
    mul r0.w, r0.w, r1.w
    mul r0.w, r0.w, c100.x
    mul r0.xyz, r0.w, r0
    cmp oC1.xyz, r1.x, r0, c104.x
    mov oC1.w, c106.z
    mov oC0.w, c13.x

// approximately 225 instruction slots used (6 texture, 219 arithmetic)
