//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float GlobalDiffuseAlpha;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float gOverrideAlpha;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   LightDirection      c0       1
//   GlobalDiffuseAlpha  c1       1
//   SpecularPower       c2       1
//   MapEnableState      c3       1
//   gLightCount         c4       1
//   gOverrideColorRatio c5       1
//   gOverrideColor      c6       1
//   gOverrideAlpha      c7       1
//   gFogMode            c8       1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c1   = { 1, 0, 0, 0 };
//
//   SpecularPower
//     c2   = { 8, 0, 0, 0 };
//
//   MapEnableState
//     c3   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c4   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c5   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c6   = { 0, 0, 0, 0 };
//
//   gOverrideAlpha
//     c7   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c8   = { 0, 0, 0, 0 };
//

    preshader
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c2.xyz, r0.w, r0.xyz
    add r0.x, c4.x, (-8)
    neg r0.y, c4.x
    cmp c0.x, r0.x, (-8), r0.y
    neg r0.x, c3.x
    cmp ob1.x, r0.x, (0), (1)
    mul c3.x, c2.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c4.xyz, r1.x, c0.xyz
    max r0.x, c5.x, (0)
    min r1.x, r0.x, (1)
    mul c7.xyz, r1.x, c6.xyz
    neg r0.x, r1.x
    add c6.x, r0.x, (1)
    mul c11.x, c1.x, c7.x
    add r0.x, c8.x, (-3)
    neg r1.x, r0.x
    max c8.x, r0.x, r1.x
    add r0.x, c8.x, (-1)
    neg r1.x, r0.x
    max c9.x, r0.x, r1.x
    add r0.x, c8.x, (-2)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x

// approximately 28 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   sampler2D MaskMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b0       1
//   gLightType            c12      8
//   gLightDiffuse         c20      8
//   gLightAmbient         c28      8
//   gLightPos             c36      8
//   gLightDir             c44      8
//   gRange                c52      8
//   gAttenuation0         c60      8
//   gAttenuation1         c68      8
//   gAttenuation2         c76      8
//   SpecularBacklighting  c84      1
//   EnvCubeMapBrightness  c85      1
//   LightBrightness       c86      1
//   DiffuseBoost          c87      1
//   AmbientLightColor     c88      1
//   DiffuseMappingFactor  c89      1
//   NormalMappingFactor   c90      1
//   SpecularMappingFactor c91      1
//   EnvCubeMappingFactor  c92      1
//   HalfLambertPower      c93      1
//   HalfLambertBase       c94      1
//   SpecularLength        c95      1
//   SpecularHighlight     c96      1
//   gFogColor             c97      1
//   gFogRange             c98      1
//   gFogDensity           c99      1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   MaskMapSampler        s4       1
//
//
// Default values:
//
//   gUseMapLight
//     b0   = false;
//
//   gLightType
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//
//   gRange
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//     c83  = { 0, 0, 0, 0 };
//
//   SpecularBacklighting
//     c84  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c85  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c86  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c87  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c88  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c89  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c90  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c91  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c93  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c94  = { 0.5, 0, 0, 0 };
//
//   SpecularLength
//     c95  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c96  = { 1, 0, 0, 0 };
//
//   gFogColor
//     c97  = { 0, 0, 0, 0 };
//
//   gFogRange
//     c98  = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c99  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c100, -4, -5, -6, -7
    def c101, 0.5, 1.44269502, 0, 0
    def c102, -0, -1, -2, -3
    def c103, 2, -1, 0, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c103.x, c103.y
    mul r1.yzw, r1.y, v4.xxyz
    mad r1.xyz, v3, r1.x, r1.yzww
    mad r1.xyz, r1, c90.x, v1
    nrm r2.xyz, r1
    if b0
      mov r1.xyz, c103.w
      mov r3.xyz, c103.w
      mov r0.w, c103.w
      rep i0
        add r1.w, r0.w, c0.x
        cmp r1.w, r1.w, c103_abs.y, c103_abs.w
        break_ne r1.w, -r1.w
        add r4, r0.w, c102
        add r5, r0.w, c100
        mov r1.w, c103.w
        cmp r2.w, -r4_abs.x, c12.x, r1.w
        cmp r2.w, -r4_abs.y, c13.x, r2.w
        cmp r2.w, -r4_abs.z, c14.x, r2.w
        cmp r2.w, -r4_abs.w, c15.x, r2.w
        cmp r2.w, -r5_abs.x, c16.x, r2.w
        cmp r2.w, -r5_abs.y, c17.x, r2.w
        cmp r2.w, -r5_abs.z, c18.x, r2.w
        cmp r2.w, -r5_abs.w, c19.x, r2.w
        if_eq r2.w, -c102.w
          cmp r6.xyz, -r4_abs.x, c44, r1.w
          cmp r6.xyz, -r4_abs.y, c45, r6
          cmp r6.xyz, -r4_abs.z, c46, r6
          cmp r6.xyz, -r4_abs.w, c47, r6
          cmp r6.xyz, -r5_abs.x, c48, r6
          cmp r6.xyz, -r5_abs.y, c49, r6
          cmp r6.xyz, -r5_abs.z, c50, r6
          cmp r6.xyz, -r5_abs.w, c51, r6
          dp3 r3.w, r6, r2
          mov r6.x, c101.x
          mad r3.w, r3.w, r6.x, c94.x
          pow r6.x, r3_abs.w, c93.x
          mul r3.w, r6.x, c86.x
          cmp r6.xyz, -r4_abs.x, c20, r1.w
          cmp r6.xyz, -r4_abs.y, c21, r6
          cmp r6.xyz, -r4_abs.z, c22, r6
          cmp r6.xyz, -r4_abs.w, c23, r6
          cmp r6.xyz, -r5_abs.x, c24, r6
          cmp r6.xyz, -r5_abs.y, c25, r6
          cmp r6.xyz, -r5_abs.z, c26, r6
          cmp r6.xyz, -r5_abs.w, c27, r6
          mad r1.xyz, r3.w, r6, r1
          cmp r6.xyz, -r4_abs.x, c28, r1.w
          cmp r6.xyz, -r4_abs.y, c29, r6
          cmp r6.xyz, -r4_abs.z, c30, r6
          cmp r6.xyz, -r4_abs.w, c31, r6
          cmp r6.xyz, -r5_abs.x, c32, r6
          cmp r6.xyz, -r5_abs.y, c33, r6
          cmp r6.xyz, -r5_abs.z, c34, r6
          cmp r6.xyz, -r5_abs.w, c35, r6
          add r3.xyz, r3, r6
        else
          add r2.w, r2.w, c103.y
          cmp r6.xyz, -r4_abs.x, c36, r1.w
          cmp r6.xyz, -r4_abs.y, c37, r6
          cmp r6.xyz, -r4_abs.z, c38, r6
          cmp r6.xyz, -r4_abs.w, c39, r6
          cmp r6.xyz, -r5_abs.x, c40, r6
          cmp r6.xyz, -r5_abs.y, c41, r6
          cmp r6.xyz, -r5_abs.z, c42, r6
          cmp r6.xyz, -r5_abs.w, c43, r6
          add r6.xyz, r6, -v5
          dp3 r3.w, r6, r6
          rsq r3.w, r3.w
          rcp r6.w, r3.w
          cmp r7.x, -r4_abs.x, c52.x, r1.w
          cmp r7.x, -r4_abs.y, c53.x, r7.x
          cmp r7.x, -r4_abs.z, c54.x, r7.x
          cmp r7.x, -r4_abs.w, c55.x, r7.x
          cmp r7.x, -r5_abs.x, c56.x, r7.x
          cmp r7.x, -r5_abs.y, c57.x, r7.x
          cmp r7.x, -r5_abs.z, c58.x, r7.x
          cmp r7.x, -r5_abs.w, c59.x, r7.x
          add r7.x, r6.w, -r7.x
          cmp r7.y, -r4_abs.x, c60.x, r1.w
          cmp r7.y, -r4_abs.y, c61.x, r7.y
          cmp r7.y, -r4_abs.z, c62.x, r7.y
          cmp r7.y, -r4_abs.w, c63.x, r7.y
          cmp r7.y, -r5_abs.x, c64.x, r7.y
          cmp r7.y, -r5_abs.y, c65.x, r7.y
          cmp r7.y, -r5_abs.z, c66.x, r7.y
          cmp r7.y, -r5_abs.w, c67.x, r7.y
          cmp r7.z, -r4_abs.x, c68.x, r1.w
          cmp r7.z, -r4_abs.y, c69.x, r7.z
          cmp r7.z, -r4_abs.z, c70.x, r7.z
          cmp r7.z, -r4_abs.w, c71.x, r7.z
          cmp r7.z, -r5_abs.x, c72.x, r7.z
          cmp r7.z, -r5_abs.y, c73.x, r7.z
          cmp r7.z, -r5_abs.z, c74.x, r7.z
          cmp r7.z, -r5_abs.w, c75.x, r7.z
          mad r7.y, r7.z, r6.w, r7.y
          cmp r7.z, -r4_abs.x, c76.x, r1.w
          cmp r7.z, -r4_abs.y, c77.x, r7.z
          cmp r7.z, -r4_abs.z, c78.x, r7.z
          cmp r7.z, -r4_abs.w, c79.x, r7.z
          cmp r7.z, -r5_abs.x, c80.x, r7.z
          cmp r7.z, -r5_abs.y, c81.x, r7.z
          cmp r7.z, -r5_abs.z, c82.x, r7.z
          cmp r7.z, -r5_abs.w, c83.x, r7.z
          mul r6.w, r6.w, r6.w
          mad r6.w, r6.w, r7.z, r7.y
          rcp r6.w, r6.w
          mul r6.xyz, r3.w, r6
          cmp r7.yzw, -r4_abs.x, c20.xxyz, r1.w
          cmp r7.yzw, -r4_abs.y, c21.xxyz, r7
          cmp r7.yzw, -r4_abs.z, c22.xxyz, r7
          cmp r7.yzw, -r4_abs.w, c23.xxyz, r7
          cmp r7.yzw, -r5_abs.x, c24.xxyz, r7
          cmp r7.yzw, -r5_abs.y, c25.xxyz, r7
          cmp r7.yzw, -r5_abs.z, c26.xxyz, r7
          cmp r7.yzw, -r5_abs.w, c27.xxyz, r7
          mul r7.yzw, r6.w, r7
          dp3_sat r3.w, r6, r2
          mad r6.xyz, r7.yzww, r3.w, r1
          cmp r7.yzw, -r4_abs.x, c28.xxyz, r1.w
          cmp r7.yzw, -r4_abs.y, c29.xxyz, r7
          cmp r4.xyz, -r4_abs.z, c30, r7.yzww
          cmp r4.xyz, -r4_abs.w, c31, r4
          cmp r4.xyz, -r5_abs.x, c32, r4
          cmp r4.xyz, -r5_abs.y, c33, r4
          cmp r4.xyz, -r5_abs.z, c34, r4
          cmp r4.xyz, -r5_abs.w, c35, r4
          mad r4.xyz, r4, r6.w, r3
          cmp r5.xyz, r7.x, r1, r6
          cmp r4.xyz, r7.x, r3, r4
          cmp r1.xyz, -r2_abs.w, r5, r1
          cmp r3.xyz, -r2_abs.w, r4, r3
        endif
        add r0.w, r0.w, -c103.y
      endrep
      if b1
        texld r4, v0, s4
        cmp r1.xyz, -r1_abs.x, r4.x, r1
      endif
    else
      dp3 r0.w, c2, r2
      mov r4.x, c101.x
      mad r0.w, r0.w, r4.x, c94.x
      pow r1.w, r0_abs.w, c93.x
      mul r1.xyz, r1.w, c86.x
      mov r3.xyz, c88.x
    endif
    mul r0.xyz, r0, c89.x
    add r4.xyz, r1, c87.x
    mad r0.xyz, r0, r4, r3
    add r0.w, r1.y, r1.x
    add r0.w, r1.z, r0.w
    dp3 r1.x, r2, c2
    mul r1.x, r1.x, -c100.x
    mad r1.xyz, r1.x, r2, -c2
    dp3 r1.x, r1, v2
    add r1.x, r1.x, -c95.x
    mov_sat r1.y, r1.x
    cmp r1.x, -c84.x, r1.y, r1.x
    mul r1.x, r1.x, c96.x
    pow r2.w, r1_abs.x, c3.x
    texld r1, v0, s1
    mul r1.xyz, r2.w, r1
    dp3 r1.w, c4, r2
    add r1.w, r1.w, r1.w
    mad r2.xyz, r2, -r1.w, c4
    texld r2, r2, s2
    mul r2.xyz, r2, c85.x
    mul r2.xyz, r2, c92.x
    mad r1.xyz, r1, c91.x, r2
    add r1.xyz, r0, r1
    cmp r0.xyz, -r0.w, r0, r1
    mov r1.x, c6.x
    mad r0.xyz, r0, r1.x, c7
    mad r0.w, v5.w, c98.y, c98.x
    mul r1.x, c99.x, v5.w
    mul r1.y, r1.x, c101.y
    exp r1.y, r1.y
    rcp r1.y, r1.y
    mul r1.x, r1.x, r1.x
    mul r1.x, r1.x, c101.y
    exp r1.x, r1.x
    rcp r1.x, r1.x
    mov r2.y, c103.y
    cmp r1.x, -c10.x, r1.x, -r2.y
    cmp r1.x, -c9.x, r1.y, r1.x
    cmp_sat r0.w, -c8.x, r0.w, r1.x
    lrp oC0.xyz, r0.w, r0, c97
    mov oC0.w, c11.x

// approximately 210 instruction slots used (5 texture, 205 arithmetic)
