//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float EmissiveMapThreshold;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float RefractionIndex;
//   float SpecularPower;
//   int gFogMode;
//   int gLightCount;
//   float3 gOverrideColor;
//   float gOverrideColorRatio;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   LightDirection       c0       1
//   theAccumTime         c1       1
//   SpecularPower        c2       1
//   RefractionIndex      c3       1
//   MapEnableState       c4       1
//   EmissiveMapThreshold c5       1
//   NoiseMapUVFlowSpeed  c6       1
//   gLightCount          c7       1
//   gOverrideColorRatio  c8       1
//   gOverrideColor       c9       1
//   gFogMode             c10      1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c1   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c2   = { 8, 0, 0, 0 };
//
//   RefractionIndex
//     c3   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c4   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c5   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c6   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c7   = { 0, 0, 0, 0 };
//
//   gOverrideColorRatio
//     c8   = { 0, 0, 0, 0 };
//
//   gOverrideColor
//     c9   = { 0, 0, 0, 0 };
//
//   gFogMode
//     c10  = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c4.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c1.x, c6.xy
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c3.xyz, r0.w, r0.xyz
    add r0.x, c7.x, (-8)
    neg r0.y, c7.x
    cmp c2.x, r0.x, (-8), r0.y
    mul c4.x, c2.x, (0.25)
    dot r0.xyz, c0.xyz, c0.xyz
    rsq r1.x, r0.x
    mul c5.xyz, r1.x, c0.xyz
    mul c6.x, c3.x, c3.x
    max r0.x, c8.x, (0)
    min r1.x, r0.x, (1)
    mul c9.xyz, r1.x, c9.xyz
    neg r0.x, r1.x
    add c8.x, r0.x, (1)
    add r0.x, c10.x, (-3)
    neg r1.x, r0.x
    max c10.x, r0.x, r1.x
    add r0.x, c10.x, (-1)
    neg r1.x, r0.x
    max c11.x, r0.x, r1.x
    add r0.x, c10.x, (-2)
    neg r1.x, r0.x
    max c12.x, r0.x, r1.x
    neg r0.x, c5.x
    add c13.x, r0.x, (1)

// approximately 31 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EmissiveMapIntensity;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float RefractionIndex;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float3 gFogColor;
//   float gFogDensity;
//   float2 gFogRange;
//   float4 gLightAmbient[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gOverrideAlpha;
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b1       1
//   gLightType            c14      8
//   gLightDiffuse         c22      8
//   gLightAmbient         c30      8
//   gLightPos             c38      8
//   gLightDir             c46      8
//   gRange                c54      8
//   gAttenuation0         c62      8
//   gAttenuation1         c70      8
//   gAttenuation2         c78      8
//   GlobalDiffuseAlpha    c86      1
//   SpecularBacklighting  c87      1
//   EnvCubeMapBrightness  c88      1
//   LightBrightness       c89      1
//   DiffuseBoost          c90      1
//   AmbientLightColor     c91      1
//   DiffuseMappingFactor  c92      1
//   NormalMappingFactor   c93      1
//   SpecularMappingFactor c94      1
//   EnvCubeMappingFactor  c95      1
//   HalfLambertPower      c96      1
//   HalfLambertBase       c97      1
//   RefractionIndex       c98      1
//   SpecularLength        c99      1
//   SpecularHighlight     c100     1
//   MapEnableState        c101     1
//   EmissiveMapIntensity  c102     1
//   gOverrideAlpha        c103     1
//   gFogColor             c104     1
//   gFogRange             c105     1
//   gFogDensity           c106     1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   AlphaMapSampler       s4       1
//   MaskMapSampler        s5       1
//   NoiseMapSampler       s6       1
//
//
// Default values:
//
//   gUseMapLight
//     b1   = false;
//
//   gLightType
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//
//   gLightAmbient
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//
//   gRange
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c78  = { 0, 0, 0, 0 };
//     c79  = { 0, 0, 0, 0 };
//     c80  = { 0, 0, 0, 0 };
//     c81  = { 0, 0, 0, 0 };
//     c82  = { 0, 0, 0, 0 };
//     c83  = { 0, 0, 0, 0 };
//     c84  = { 0, 0, 0, 0 };
//     c85  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c86  = { 1, 0, 0, 0 };
//
//   SpecularBacklighting
//     c87  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c88  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c89  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c90  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c91  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c92  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c93  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c94  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c95  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c96  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c97  = { 0.5, 0, 0, 0 };
//
//   RefractionIndex
//     c98  = { 0, 0, 0, 0 };
//
//   SpecularLength
//     c99  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c100 = { 1, 0, 0, 0 };
//
//   MapEnableState
//     c101 = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c102 = { 0, 0, 0, 0 };
//
//   gOverrideAlpha
//     c103 = { 0, 0, 0, 0 };
//
//   gFogColor
//     c104 = { 0, 0, 0, 0 };
//
//   gFogRange
//     c105 = { 0, 0, 0, 0 };
//
//   gFogDensity
//     c106 = { 0, 0, 0, 0 };
//

    ps_3_0
    def c107, 0, 1, 2, 3
    def c108, 0.5, 1.44269502, 0, 0
    def c109, -4, -5, -6, -7
    def c110, 2, -1, 1, 0
    def c111, 0.212599993, 0.715200007, 0.0722000003, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c110.x, c110.y
    texld r2, v0, s4
    if b0
      texld r3, v0, s5
      mov r0.w, r3.y
    else
      mov r3.x, c110.z
      mov r0.w, c110.z
    endif
    add r1.zw, c1.xyxy, v0.xyxy
    texld r4, r1.zwzw, s6
    mov r1.z, c110.z
    cmp r1.w, -c101.y, r1.z, r4.x
    mul r3.yzw, r1.y, v4.xxyz
    mad r3.yzw, v3.xxyz, r1.x, r3
    mad r3.yzw, r3, c93.x, v1.xxyz
    nrm r4.xyz, r3.yzww
    if b1
      mov r3.yzw, c107.x
      mov r5.xyz, c107.x
      mov r1.x, c107.x
      rep i0
        add r1.y, r1.x, c2.x
        cmp r1.y, r1.y, c107.y, c107.x
        break_ne r1.y, -r1.y
        add r6, r1.x, -c107
        add r7, r1.x, c109
        mov r8.x, c107.x
        cmp r1.y, -r6_abs.x, c14.x, r8.x
        cmp r1.y, -r6_abs.y, c15.x, r1.y
        cmp r1.y, -r6_abs.z, c16.x, r1.y
        cmp r1.y, -r6_abs.w, c17.x, r1.y
        cmp r1.y, -r7_abs.x, c18.x, r1.y
        cmp r1.y, -r7_abs.y, c19.x, r1.y
        cmp r1.y, -r7_abs.z, c20.x, r1.y
        cmp r1.y, -r7_abs.w, c21.x, r1.y
        if_eq r1.y, c107.w
          cmp r8.yzw, -r6_abs.x, c46.xxyz, r8.x
          cmp r8.yzw, -r6_abs.y, c47.xxyz, r8
          cmp r8.yzw, -r6_abs.z, c48.xxyz, r8
          cmp r8.yzw, -r6_abs.w, c49.xxyz, r8
          cmp r8.yzw, -r7_abs.x, c50.xxyz, r8
          cmp r8.yzw, -r7_abs.y, c51.xxyz, r8
          cmp r8.yzw, -r7_abs.z, c52.xxyz, r8
          cmp r8.yzw, -r7_abs.w, c53.xxyz, r8
          dp3 r2.w, r8.yzww, r4
          mov r9.x, c108.x
          mad r2.w, r2.w, r9.x, c97.x
          pow r4.w, r2_abs.w, c96.x
          mul r2.w, r4.w, c89.x
          cmp r8.yzw, -r6_abs.x, c22.xxyz, r8.x
          cmp r8.yzw, -r6_abs.y, c23.xxyz, r8
          cmp r8.yzw, -r6_abs.z, c24.xxyz, r8
          cmp r8.yzw, -r6_abs.w, c25.xxyz, r8
          cmp r8.yzw, -r7_abs.x, c26.xxyz, r8
          cmp r8.yzw, -r7_abs.y, c27.xxyz, r8
          cmp r8.yzw, -r7_abs.z, c28.xxyz, r8
          cmp r8.yzw, -r7_abs.w, c29.xxyz, r8
          mad r3.yzw, r2.w, r8, r3
          cmp r8.yzw, -r6_abs.x, c30.xxyz, r8.x
          cmp r8.yzw, -r6_abs.y, c31.xxyz, r8
          cmp r8.yzw, -r6_abs.z, c32.xxyz, r8
          cmp r8.yzw, -r6_abs.w, c33.xxyz, r8
          cmp r8.yzw, -r7_abs.x, c34.xxyz, r8
          cmp r8.yzw, -r7_abs.y, c35.xxyz, r8
          cmp r8.yzw, -r7_abs.z, c36.xxyz, r8
          cmp r8.yzw, -r7_abs.w, c37.xxyz, r8
          add r5.xyz, r5, r8.yzww
        else
          add r1.y, r1.y, c110.y
          cmp r8.yzw, -r6_abs.x, c38.xxyz, r8.x
          cmp r8.yzw, -r6_abs.y, c39.xxyz, r8
          cmp r8.yzw, -r6_abs.z, c40.xxyz, r8
          cmp r8.yzw, -r6_abs.w, c41.xxyz, r8
          cmp r8.yzw, -r7_abs.x, c42.xxyz, r8
          cmp r8.yzw, -r7_abs.y, c43.xxyz, r8
          cmp r8.yzw, -r7_abs.z, c44.xxyz, r8
          cmp r8.yzw, -r7_abs.w, c45.xxyz, r8
          add r8.yzw, r8, -v5.xxyz
          dp3 r2.w, r8.yzww, r8.yzww
          rsq r2.w, r2.w
          rcp r4.w, r2.w
          cmp r5.w, -r6_abs.x, c54.x, r8.x
          cmp r5.w, -r6_abs.y, c55.x, r5.w
          cmp r5.w, -r6_abs.z, c56.x, r5.w
          cmp r5.w, -r6_abs.w, c57.x, r5.w
          cmp r5.w, -r7_abs.x, c58.x, r5.w
          cmp r5.w, -r7_abs.y, c59.x, r5.w
          cmp r5.w, -r7_abs.z, c60.x, r5.w
          cmp r5.w, -r7_abs.w, c61.x, r5.w
          add r5.w, r4.w, -r5.w
          cmp r9.x, -r6_abs.x, c62.x, r8.x
          cmp r9.x, -r6_abs.y, c63.x, r9.x
          cmp r9.x, -r6_abs.z, c64.x, r9.x
          cmp r9.x, -r6_abs.w, c65.x, r9.x
          cmp r9.x, -r7_abs.x, c66.x, r9.x
          cmp r9.x, -r7_abs.y, c67.x, r9.x
          cmp r9.x, -r7_abs.z, c68.x, r9.x
          cmp r9.x, -r7_abs.w, c69.x, r9.x
          cmp r9.y, -r6_abs.x, c70.x, r8.x
          cmp r9.y, -r6_abs.y, c71.x, r9.y
          cmp r9.y, -r6_abs.z, c72.x, r9.y
          cmp r9.y, -r6_abs.w, c73.x, r9.y
          cmp r9.y, -r7_abs.x, c74.x, r9.y
          cmp r9.y, -r7_abs.y, c75.x, r9.y
          cmp r9.y, -r7_abs.z, c76.x, r9.y
          cmp r9.y, -r7_abs.w, c77.x, r9.y
          mad r9.x, r9.y, r4.w, r9.x
          cmp r9.y, -r6_abs.x, c78.x, r8.x
          cmp r9.y, -r6_abs.y, c79.x, r9.y
          cmp r9.y, -r6_abs.z, c80.x, r9.y
          cmp r9.y, -r6_abs.w, c81.x, r9.y
          cmp r9.y, -r7_abs.x, c82.x, r9.y
          cmp r9.y, -r7_abs.y, c83.x, r9.y
          cmp r9.y, -r7_abs.z, c84.x, r9.y
          cmp r9.y, -r7_abs.w, c85.x, r9.y
          mul r4.w, r4.w, r4.w
          mad r4.w, r4.w, r9.y, r9.x
          rcp r4.w, r4.w
          mul r8.yzw, r2.w, r8
          cmp r9.xyz, -r6_abs.x, c22, r8.x
          cmp r9.xyz, -r6_abs.y, c23, r9
          cmp r9.xyz, -r6_abs.z, c24, r9
          cmp r9.xyz, -r6_abs.w, c25, r9
          cmp r9.xyz, -r7_abs.x, c26, r9
          cmp r9.xyz, -r7_abs.y, c27, r9
          cmp r9.xyz, -r7_abs.z, c28, r9
          cmp r9.xyz, -r7_abs.w, c29, r9
          mul r9.xyz, r4.w, r9
          dp3_sat r2.w, r8.yzww, r4
          mad r8.yzw, r9.xxyz, r2.w, r3
          cmp r9.xyz, -r6_abs.x, c30, r8.x
          cmp r9.xyz, -r6_abs.y, c31, r9
          cmp r6.xyz, -r6_abs.z, c32, r9
          cmp r6.xyz, -r6_abs.w, c33, r6
          cmp r6.xyz, -r7_abs.x, c34, r6
          cmp r6.xyz, -r7_abs.y, c35, r6
          cmp r6.xyz, -r7_abs.z, c36, r6
          cmp r6.xyz, -r7_abs.w, c37, r6
          mad r6.xyz, r6, r4.w, r5
          cmp r7.xyz, r5.w, r3.yzww, r8.yzww
          cmp r6.xyz, r5.w, r5, r6
          cmp r3.yzw, -r1_abs.y, r7.xxyz, r3
          cmp r5.xyz, -r1_abs.y, r6, r5
        endif
        add r1.x, r1.x, c110.z
      endrep
      cmp r6.xyz, -r3_abs.y, r3.x, r3.yzww
      cmp r3.xyz, -c101.x, r3.yzww, r6
    else
      dp3 r1.x, c3, r4
      mov r6.x, c108.x
      mad r1.x, r1.x, r6.x, c97.x
      pow r2.w, r1_abs.x, c96.x
      mul r3.xyz, r2.w, c89.x
      mov r5.xyz, c91.x
    endif
    mul r6.xyz, r0, c92.x
    add r7.xyz, r3, c90.x
    mad r5.xyz, r6, r7, r5
    mul r1.x, r2.x, c86.x
    add r1.y, r3.y, r3.x
    add r1.y, r3.z, r1.y
    dp3 r2.x, r4, c3
    mul r2.x, r2.x, -c109.x
    mad r3.xyz, r2.x, r4, -c3
    dp3 r2.x, r3, v2
    add r2.x, r2.x, -c99.x
    mov_sat r2.w, r2.x
    cmp r2.x, -c87.x, r2.w, r2.x
    mul r2.x, r2.x, c100.x
    pow r3.x, r2_abs.x, c4.x
    texld r6, v0, s1
    mul r3.xyz, r3.x, r6
    dp3 r2.x, c5, r4
    mad r2.w, r2.x, -r2.x, c110.z
    mad r2.w, c6.x, -r2.w, r1.z
    cmp r3.w, r2.w, c107.y, c107.x
    mul r2.w, r2.w, r3.w
    mul r3.w, r3.w, c98.x
    rsq r2.w, r2.w
    rcp r2.w, r2.w
    mad r2.x, r3.w, r2.x, r2.w
    mul r4.xyz, r4, r2.x
    mad r4.xyz, r3.w, c5, -r4
    texld r4, r4, s2
    mul r3.xyz, r3, c94.x
    mul r4.xyz, r4, c88.x
    mul r4.xyz, r4, c95.x
    mul r2.xzw, r2.z, r4.xyyz
    mad r2.xyz, r3, r2.y, r2.xzww
    add r2.xyz, r2, r5
    cmp r2.xyz, -r1.y, r5, r2
    mov r3.x, c8.x
    mad r2.xyz, r2, r3.x, c9
    mul oC0.w, r1.x, c103.x
    mad r1.x, v5.w, c105.y, c105.x
    mul r1.y, c106.x, v5.w
    mul r2.w, r1.y, c108.y
    exp r2.w, r2.w
    rcp r2.w, r2.w
    mul r1.y, r1.y, r1.y
    mul r1.y, r1.y, c108.y
    exp r1.y, r1.y
    rcp r1.y, r1.y
    cmp r1.y, -c12.x, r1.y, r1.z
    cmp r1.y, -c11.x, r2.w, r1.y
    cmp_sat r1.x, -c10.x, r1.x, r1.y
    lrp oC0.xyz, r1.x, r2, c104
    dp3 r1.x, r0, c111
    add r1.x, r1.x, -c13.x
    mul r0.w, r0.w, r1.w
    mul r0.w, r0.w, c102.x
    mul r0.xyz, r0.w, r0
    cmp oC1.xyz, r1.x, r0, c107.x
    mov oC1.w, c110.z

// approximately 237 instruction slots used (7 texture, 230 arithmetic)
