//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 Color;
//   float3 ColorLimit;
//   float TexturePanningVelocityU;
//   float TexturePanningVelocityV;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   Color                   c0       1
//   ColorLimit              c1       1
//   theAccumTime            c2       1
//   TexturePanningVelocityU c3       1
//   TexturePanningVelocityV c4       1
//
//
// Default values:
//
//   Color
//     c0   = { 0, 0, 0, 0 };
//
//   ColorLimit
//     c1   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c2   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityU
//     c3   = { 0, 0, 0, 0 };
//
//   TexturePanningVelocityV
//     c4   = { 0, 0, 0, 0 };
//

    preshader
    mul c0.x, c2.x, c3.x
    mul c0.y, c2.x, c4.x
    mul c1.x, c2.x, (0.55)
    neg r0.x, c4.x
    max r1.x, r0.x, c4.x
    neg r0.x, r1.x
    cmp r1.x, r0.x, (-0), (-1)
    neg r0.x, c3.x
    max r1.y, r0.x, c3.x
    neg r0.x, r1.y
    cmp c2.x, r0.x, (-0), r1.x
    neg r0.x, c0.x
    add r1.x, r0.x, c1.x
    cmp c3.x, r1.x, c1.x, c0.x
    neg r0.x, c0.y
    add r1.x, r0.x, c1.y
    cmp c3.y, r1.x, c1.y, c0.y
    neg r0.x, c0.z
    add r1.x, r0.x, c1.z
    cmp c3.z, r1.x, c1.z, c0.z

// approximately 20 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler2;
//   float GlobalDiffuseAlpha;
//   float3 HightLightColor;
//   float HightLightPower;
//   sampler2D OverlayMapSampler;
//   float TextureTileX;
//   float TextureTileY;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   HightLightColor    c4       1
//   GlobalDiffuseAlpha c5       1
//   TextureTileX       c6       1
//   TextureTileY       c7       1
//   HightLightPower    c8       1
//   AlphaMapSampler2   s1       1
//   OverlayMapSampler  s2       1
//
//
// Default values:
//
//   HightLightColor
//     c4   = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c5   = { 1, 0, 0, 0 };
//
//   TextureTileX
//     c6   = { 1, 0, 0, 0 };
//
//   TextureTileY
//     c7   = { 1, 0, 0, 0 };
//
//   HightLightPower
//     c8   = { 0, 0, 0, 0 };
//

    ps_3_0
    def c9, 0, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s1
    dcl_2d s2
    mul r0.x, c6.x, v0.x
    mul r0.y, c7.x, v0.y
    add r0.zw, r0.xyxy, c0.xyxy
    add r0.xy, r0, c1.x
    cmp r0.xy, c2.x, r0, r0.zwzw
    texld r0, r0, s2
    texld r1, v0, s1
    mul r1.x, r1.y, c8.x
    mul r2.xyz, r1.x, c4
    cmp r1.xyw, -r1.y, c9.x, r2.xyzz
    mul r0.w, r0.w, r1.z
    mul oC0.w, r0.w, c5.x
    add r1.xyz, r1.xyww, c3
    add oC0.xyz, r0, r1

// approximately 14 instruction slots used (2 texture, 12 arithmetic)
