//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float EmissiveMapThreshold;
//   float3 LightDirection;
//   float4 MapEnableState;
//   float2 NoiseMapUVFlowSpeed;
//   float RefractionIndex;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   float SpecularPower;
//   float3 TransformedLitDirection;
//   int gLightCount;
//   float theAccumTime;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   LightDirection          c0       1
//   TransformedLitDirection c1       1
//   theAccumTime            c2       1
//   SpecularPower           c3       1
//   RefractionIndex         c4       1
//   RefractionParam         c5       1
//   RimLightParam           c6       1
//   MapEnableState          c7       1
//   EmissiveMapThreshold    c8       1
//   NoiseMapUVFlowSpeed     c9       1
//   gLightCount             c10      1
//
//
// Default values:
//
//   LightDirection
//     c0   = { 0, 0, 0, 0 };
//
//   TransformedLitDirection
//     c1   = { 0, 0, 0, 0 };
//
//   theAccumTime
//     c2   = { 0, 0, 0, 0 };
//
//   SpecularPower
//     c3   = { 8, 0, 0, 0 };
//
//   RefractionIndex
//     c4   = { 0, 0, 0, 0 };
//
//   RefractionParam
//     c5   = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c6   = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c7   = { 0, 0, 0, 0 };
//
//   EmissiveMapThreshold
//     c8   = { 0, 0, 0, 0 };
//
//   NoiseMapUVFlowSpeed
//     c9   = { 0, 0, 0, 0 };
//
//   gLightCount
//     c10  = { 0, 0, 0, 0 };
//

    preshader
    neg r0.x, c7.x
    cmp ob0.x, r0.x, (0), (1)
    mul c1.xy, c2.x, c9.xy
    neg r0.xyz, c0.xyz
    dot r1.xyz, r0.xyz, r0.xyz
    rsq r0.w, r1.x
    mul c2.xyz, r0.w, r0.xyz
    add r0.x, c10.x, (-8)
    neg r0.y, c10.x
    cmp c3.x, r0.x, (-8), r0.y
    mul c4.x, c3.x, (0.25)
    dot r0.xyz, c1.xyz, c1.xyz
    rsq r1.x, r0.x
    mul c5.xyz, r1.x, c1.xyz
    mul c6.x, c4.x, c4.x
    mul c7.x, c5.y, (0.015625)
    neg r0.x, c6.w
    add r1.x, r0.x, (1)
    neg r0.x, r1.x
    mov c8.x, r1.x
    add r1.x, r0.x, (1)
    rcp c9.x, r1.x
    neg r0.x, c8.x
    add c10.x, r0.x, (1)

// approximately 24 instructions used
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D AlphaMapSampler;
//   float AmbientLightColor;
//   samplerCUBE CubeMapSampler;
//   float DiffuseBoost;
//   sampler2D DiffuseMapSampler;
//   float DiffuseMappingFactor;
//   float EmissiveMapIntensity;
//   float EnvCubeMapBrightness;
//   float EnvCubeMappingFactor;
//   float GlobalDiffuseAlpha;
//   float HalfLambertBase;
//   float HalfLambertPower;
//   float LightBrightness;
//   float4 MapEnableState;
//   sampler2D MaskMapSampler;
//   sampler2D NoiseMapSampler;
//   sampler2D NormalMapSampler;
//   float NormalMappingFactor;
//   float ReflectionIndex;
//   float RefractionIndex;
//   float2 RefractionParam;
//   float4 RimLightParam;
//   bool SpecularBacklighting;
//   float SpecularHighlight;
//   float SpecularLength;
//   sampler2D SpecularMapSampler;
//   float SpecularMappingFactor;
//   float4x4 ViewProjectionMatrix;
//   float gAttenuation0[8];
//   float gAttenuation1[8];
//   float gAttenuation2[8];
//   float4 gLightDiffuse[8];
//   float3 gLightDir[8];
//   float3 gLightPos[8];
//   int gLightType[8];
//   float gRange[8];
//   bool gUseMapLight;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gUseMapLight          b1       1
//   gLightType            c11      8
//   gLightDiffuse         c19      8
//   gLightPos             c27      8
//   gLightDir             c35      8
//   gRange                c43      8
//   gAttenuation0         c51      8
//   gAttenuation1         c59      8
//   gAttenuation2         c67      8
//   ViewProjectionMatrix  c75      4
//   GlobalDiffuseAlpha    c79      1
//   SpecularBacklighting  c80      1
//   EnvCubeMapBrightness  c81      1
//   LightBrightness       c82      1
//   DiffuseBoost          c83      1
//   AmbientLightColor     c84      1
//   DiffuseMappingFactor  c85      1
//   NormalMappingFactor   c86      1
//   SpecularMappingFactor c87      1
//   EnvCubeMappingFactor  c88      1
//   HalfLambertPower      c89      1
//   HalfLambertBase       c90      1
//   ReflectionIndex       c91      1
//   RefractionIndex       c92      1
//   SpecularLength        c93      1
//   SpecularHighlight     c94      1
//   RefractionParam       c95      1
//   RimLightParam         c96      1
//   MapEnableState        c97      1
//   EmissiveMapIntensity  c98      1
//   DiffuseMapSampler     s0       1
//   SpecularMapSampler    s1       1
//   CubeMapSampler        s2       1
//   NormalMapSampler      s3       1
//   AlphaMapSampler       s4       1
//   MaskMapSampler        s5       1
//   NoiseMapSampler       s6       1
//
//
// Default values:
//
//   gUseMapLight
//     b1   = false;
//
//   gLightType
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//
//   gLightDiffuse
//     c19  = { 0, 0, 0, 0 };
//     c20  = { 0, 0, 0, 0 };
//     c21  = { 0, 0, 0, 0 };
//     c22  = { 0, 0, 0, 0 };
//     c23  = { 0, 0, 0, 0 };
//     c24  = { 0, 0, 0, 0 };
//     c25  = { 0, 0, 0, 0 };
//     c26  = { 0, 0, 0, 0 };
//
//   gLightPos
//     c27  = { 0, 0, 0, 0 };
//     c28  = { 0, 0, 0, 0 };
//     c29  = { 0, 0, 0, 0 };
//     c30  = { 0, 0, 0, 0 };
//     c31  = { 0, 0, 0, 0 };
//     c32  = { 0, 0, 0, 0 };
//     c33  = { 0, 0, 0, 0 };
//     c34  = { 0, 0, 0, 0 };
//
//   gLightDir
//     c35  = { 0, 0, 0, 0 };
//     c36  = { 0, 0, 0, 0 };
//     c37  = { 0, 0, 0, 0 };
//     c38  = { 0, 0, 0, 0 };
//     c39  = { 0, 0, 0, 0 };
//     c40  = { 0, 0, 0, 0 };
//     c41  = { 0, 0, 0, 0 };
//     c42  = { 0, 0, 0, 0 };
//
//   gRange
//     c43  = { 0, 0, 0, 0 };
//     c44  = { 0, 0, 0, 0 };
//     c45  = { 0, 0, 0, 0 };
//     c46  = { 0, 0, 0, 0 };
//     c47  = { 0, 0, 0, 0 };
//     c48  = { 0, 0, 0, 0 };
//     c49  = { 0, 0, 0, 0 };
//     c50  = { 0, 0, 0, 0 };
//
//   gAttenuation0
//     c51  = { 0, 0, 0, 0 };
//     c52  = { 0, 0, 0, 0 };
//     c53  = { 0, 0, 0, 0 };
//     c54  = { 0, 0, 0, 0 };
//     c55  = { 0, 0, 0, 0 };
//     c56  = { 0, 0, 0, 0 };
//     c57  = { 0, 0, 0, 0 };
//     c58  = { 0, 0, 0, 0 };
//
//   gAttenuation1
//     c59  = { 0, 0, 0, 0 };
//     c60  = { 0, 0, 0, 0 };
//     c61  = { 0, 0, 0, 0 };
//     c62  = { 0, 0, 0, 0 };
//     c63  = { 0, 0, 0, 0 };
//     c64  = { 0, 0, 0, 0 };
//     c65  = { 0, 0, 0, 0 };
//     c66  = { 0, 0, 0, 0 };
//
//   gAttenuation2
//     c67  = { 0, 0, 0, 0 };
//     c68  = { 0, 0, 0, 0 };
//     c69  = { 0, 0, 0, 0 };
//     c70  = { 0, 0, 0, 0 };
//     c71  = { 0, 0, 0, 0 };
//     c72  = { 0, 0, 0, 0 };
//     c73  = { 0, 0, 0, 0 };
//     c74  = { 0, 0, 0, 0 };
//
//   ViewProjectionMatrix
//     c75  = { 0, 0, 0, 0 };
//     c76  = { 0, 0, 0, 0 };
//     c77  = { 0, 0, 0, 0 };
//     c78  = { 0, 0, 0, 0 };
//
//   GlobalDiffuseAlpha
//     c79  = { 1, 0, 0, 0 };
//
//   SpecularBacklighting
//     c80  = { 0, 0, 0, 0 };
//
//   EnvCubeMapBrightness
//     c81  = { 0.05, 0, 0, 0 };
//
//   LightBrightness
//     c82  = { 1, 0, 0, 0 };
//
//   DiffuseBoost
//     c83  = { 0.2, 0, 0, 0 };
//
//   AmbientLightColor
//     c84  = { 0.2, 0, 0, 0 };
//
//   DiffuseMappingFactor
//     c85  = { 1, 0, 0, 0 };
//
//   NormalMappingFactor
//     c86  = { 1, 0, 0, 0 };
//
//   SpecularMappingFactor
//     c87  = { 1, 0, 0, 0 };
//
//   EnvCubeMappingFactor
//     c88  = { 1, 0, 0, 0 };
//
//   HalfLambertPower
//     c89  = { 2, 0, 0, 0 };
//
//   HalfLambertBase
//     c90  = { 0.5, 0, 0, 0 };
//
//   ReflectionIndex
//     c91  = { 0, 0, 0, 0 };
//
//   RefractionIndex
//     c92  = { 0, 0, 0, 0 };
//
//   SpecularLength
//     c93  = { 0, 0, 0, 0 };
//
//   SpecularHighlight
//     c94  = { 1, 0, 0, 0 };
//
//   RefractionParam
//     c95  = { 0, 0, 0, 0 };
//
//   RimLightParam
//     c96  = { 0, 0, 0, 0 };
//
//   MapEnableState
//     c97  = { 0, 0, 0, 0 };
//
//   EmissiveMapIntensity
//     c98  = { 0, 0, 0, 0 };
//

    ps_3_0
    def c99, 0.5, 0, 0, 1
    def c100, -0, -1, -2, -3
    def c101, -4, -5, -6, -7
    def c102, 2, -1, 1, 4
    def c103, -2, 3, 0, 0
    def c104, 0.212599993, 0.715200007, 0.0722000003, 0
    defi i0, 8, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_cube s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    texld r0, v0, s0
    texld r1, v0, s3
    mad r1.xy, r1, c102.x, c102.y
    texld r2, v0, s4
    texld r3, v0, s5
    if b0
      mov r0.w, r3.y
    else
      mov r0.w, r3.y
    endif
    add r1.zw, c1.xyxy, v0.xyxy
    texld r4, r1.zwzw, s6
    mov r1.z, c102.z
    cmp r1.w, -c97.y, r1.z, r4.x
    mul r3.yzw, r1.y, v4.xxyz
    mad r3.yzw, v3.xxyz, r1.x, r3
    mad r3.yzw, r3, c86.x, v1.xxyz
    nrm r4.xyz, r3.yzww
    dp3 r1.x, c2, r4
    mul r1.y, r1.x, c102.w
    mov r5.xz, c99
    mad r1.x, r1.x, r5.x, c90.x
    pow r2.w, r1_abs.x, c89.x
    mul r3.yzw, r2.w, c82.x
    if b1
      mov r6.xyz, c99.z
      mov r1.x, c99.z
      rep i0
        add r4.w, r1.x, c3.x
        cmp r4.w, r4.w, c99.w, c99.z
        break_ne r4.w, -r4.w
        add r7, r1.x, c100
        add r8, r1.x, c101
        cmp r4.w, -r7_abs.x, c11.x, r5.z
        cmp r4.w, -r7_abs.y, c12.x, r4.w
        cmp r4.w, -r7_abs.z, c13.x, r4.w
        cmp r4.w, -r7_abs.w, c14.x, r4.w
        cmp r4.w, -r8_abs.x, c15.x, r4.w
        cmp r4.w, -r8_abs.y, c16.x, r4.w
        cmp r4.w, -r8_abs.z, c17.x, r4.w
        cmp r4.w, -r8_abs.w, c18.x, r4.w
        if_eq r4.w, -c100.w
          cmp r9.xyz, -r7_abs.x, c35, r5.z
          cmp r9.xyz, -r7_abs.y, c36, r9
          cmp r9.xyz, -r7_abs.z, c37, r9
          cmp r9.xyz, -r7_abs.w, c38, r9
          cmp r9.xyz, -r8_abs.x, c39, r9
          cmp r9.xyz, -r8_abs.y, c40, r9
          cmp r9.xyz, -r8_abs.z, c41, r9
          cmp r9.xyz, -r8_abs.w, c42, r9
          dp3 r5.y, r9, r4
          mad r5.y, r5.y, r5.x, c90.x
          pow r6.w, r5_abs.y, c89.x
          mul r5.y, r6.w, c82.x
          cmp r9.xyz, -r7_abs.x, c19, r5.z
          cmp r9.xyz, -r7_abs.y, c20, r9
          cmp r9.xyz, -r7_abs.z, c21, r9
          cmp r9.xyz, -r7_abs.w, c22, r9
          cmp r9.xyz, -r8_abs.x, c23, r9
          cmp r9.xyz, -r8_abs.y, c24, r9
          cmp r9.xyz, -r8_abs.z, c25, r9
          cmp r9.xyz, -r8_abs.w, c26, r9
          mad r6.xyz, r5.y, r9, r6
        else
          add r4.w, r4.w, c102.y
          cmp r9.xyz, -r7_abs.x, c27, r5.z
          cmp r9.xyz, -r7_abs.y, c28, r9
          cmp r9.xyz, -r7_abs.z, c29, r9
          cmp r9.xyz, -r7_abs.w, c30, r9
          cmp r9.xyz, -r8_abs.x, c31, r9
          cmp r9.xyz, -r8_abs.y, c32, r9
          cmp r9.xyz, -r8_abs.z, c33, r9
          cmp r9.xyz, -r8_abs.w, c34, r9
          add r9.xyz, r9, -v5
          dp3 r5.y, r9, r9
          rsq r5.y, r5.y
          rcp r5.w, r5.y
          cmp r6.w, -r7_abs.x, c43.x, r5.z
          cmp r6.w, -r7_abs.y, c44.x, r6.w
          cmp r6.w, -r7_abs.z, c45.x, r6.w
          cmp r6.w, -r7_abs.w, c46.x, r6.w
          cmp r6.w, -r8_abs.x, c47.x, r6.w
          cmp r6.w, -r8_abs.y, c48.x, r6.w
          cmp r6.w, -r8_abs.z, c49.x, r6.w
          cmp r6.w, -r8_abs.w, c50.x, r6.w
          add r6.w, r5.w, -r6.w
          cmp r9.w, -r7_abs.x, c51.x, r5.z
          cmp r9.w, -r7_abs.y, c52.x, r9.w
          cmp r9.w, -r7_abs.z, c53.x, r9.w
          cmp r9.w, -r7_abs.w, c54.x, r9.w
          cmp r9.w, -r8_abs.x, c55.x, r9.w
          cmp r9.w, -r8_abs.y, c56.x, r9.w
          cmp r9.w, -r8_abs.z, c57.x, r9.w
          cmp r9.w, -r8_abs.w, c58.x, r9.w
          cmp r10.x, -r7_abs.x, c59.x, r5.z
          cmp r10.x, -r7_abs.y, c60.x, r10.x
          cmp r10.x, -r7_abs.z, c61.x, r10.x
          cmp r10.x, -r7_abs.w, c62.x, r10.x
          cmp r10.x, -r8_abs.x, c63.x, r10.x
          cmp r10.x, -r8_abs.y, c64.x, r10.x
          cmp r10.x, -r8_abs.z, c65.x, r10.x
          cmp r10.x, -r8_abs.w, c66.x, r10.x
          mad r9.w, r10.x, r5.w, r9.w
          cmp r10.x, -r7_abs.x, c67.x, r5.z
          cmp r10.x, -r7_abs.y, c68.x, r10.x
          cmp r10.x, -r7_abs.z, c69.x, r10.x
          cmp r10.x, -r7_abs.w, c70.x, r10.x
          cmp r10.x, -r8_abs.x, c71.x, r10.x
          cmp r10.x, -r8_abs.y, c72.x, r10.x
          cmp r10.x, -r8_abs.z, c73.x, r10.x
          cmp r10.x, -r8_abs.w, c74.x, r10.x
          mul r5.w, r5.w, r5.w
          mad r5.w, r5.w, r10.x, r9.w
          rcp r5.w, r5.w
          mul r9.xyz, r5.y, r9
          cmp r10.xyz, -r7_abs.x, c19, r5.z
          cmp r10.xyz, -r7_abs.y, c20, r10
          cmp r7.xyz, -r7_abs.z, c21, r10
          cmp r7.xyz, -r7_abs.w, c22, r7
          cmp r7.xyz, -r8_abs.x, c23, r7
          cmp r7.xyz, -r8_abs.y, c24, r7
          cmp r7.xyz, -r8_abs.z, c25, r7
          cmp r7.xyz, -r8_abs.w, c26, r7
          mul r7.xyz, r5.w, r7
          dp3_sat r5.y, r9, r4
          mad r7.xyz, r7, r5.y, r6
          cmp r7.xyz, r6.w, r6, r7
          cmp r6.xyz, -r4_abs.w, r7, r6
        endif
        add r1.x, r1.x, c102.z
      endrep
      cmp r5.xyz, -r6_abs.x, r3.x, r6
      cmp r3.yzw, -c97.x, r6.xxyz, r5.xxyz
    endif
    mul r5.xyz, r0, c85.x
    mov r1.x, c82.x
    mad r1.x, r2.w, r1.x, c83.x
    mad r5.xyz, r5, r1.x, c84.x
    mul r1.x, r2.x, c79.x
    add r2.x, r3.z, r3.y
    add r2.x, r3.w, r2.x
    mad r3.xyz, r1.y, r4, -c2
    dp3 r1.y, r3, v2
    add r1.y, r1.y, -c93.x
    mov_sat r2.w, r1.y
    cmp r1.y, -c80.x, r2.w, r1.y
    mul r1.y, r1.y, c94.x
    pow r2.w, r1_abs.y, c4.x
    texld r3, v0, s1
    mul r3.xyz, r2.w, r3
    dp3 r1.y, c5, r4
    add r2.w, r1.y, r1.y
    mad r6.xyz, r4, -r2.w, c5
    mad r2.w, r1.y, -r1.y, c102.z
    mad r2.w, c6.x, -r2.w, r1.z
    cmp r3.w, r2.w, c99.w, c99.z
    mul r2.w, r2.w, r3.w
    mul r3.w, r3.w, c92.x
    rsq r2.w, r2.w
    rcp r2.w, r2.w
    mad r1.y, r3.w, r1.y, r2.w
    mul r7.xyz, r4, r1.y
    mad r7.xyz, r3.w, c5, -r7
    mul r7.xyz, r7, c92.x
    mad r6.xyz, c91.x, r6, r7
    texld r6, r6, s2
    mul r6.xyz, r6, c81.x
    mul r6.xyz, r6, c88.x
    mul r6.xyz, r2.z, r6
    mad r3.xyz, r3, c87.x, r6
    add r3.xyz, r3, r5
    cmp oC0.xyz, -r2.x, r5, r3
    mad r1.y, c95.x, -r2.y, r1.z
    mul r1.y, r1.y, r1.x
    dp3 r3.x, r4, c75
    dp3 r3.y, r4, c76
    dp3 r1.z, r4, c78
    rcp r1.z, r1.z
    mad r2.xz, r3.xyyw, r1.z, c102.z
    mul r3.xy, r2.xzzw, c99.x
    mul r3.z, r2.y, c7.x
    dp3 r1.z, v2, r4
    add r2.x, -r1.z, c102.z
    cmp r1.z, r1.z, r2.x, c102.z
    add r1.z, r1.z, -c8.x
    mul_sat r1.z, r1.z, c9.x
    mad r2.x, r1.z, c103.x, c103.y
    mul r1.z, r1.z, r1.z
    mul r1.z, r1.z, r2.x
    mul r4.xyz, r1.z, c96
    mov r3.w, c7.x
    cmp oC1, -r2.y, c99.z, r3
    mov r4.w, c99.x
    cmp oC2, -r2.y, c99.z, r4
    cmp oC0.w, -r2.y, r1.x, r1.y
    dp3 r1.x, r0, c104
    add r1.x, r1.x, -c10.x
    mul r0.w, r0.w, r1.w
    mul r0.w, r0.w, c98.x
    mul r0.xyz, r0.w, r0
    cmp oC3.xyz, r1.x, r0, c99.z
    mov oC3.w, c102.z

// approximately 221 instruction slots used (7 texture, 214 arithmetic)
